### ISSUE TITLE
[Bug]: 数据从rdbms  写入到Doris  报错

### ISSUE THREAD

**Issue by suiquantong** [wgzhao/Addax#1026]
### What happened?

```json
{
	"job": {
		"setting": {
			"speed": {
				"channel": 1
			},
			"errorLimit": {
				"record": 0,
				"percentage": 0.02
			}
		},
		"content": {
			"reader": {
				"name": "rdbmsreader",
				"parameter": {
					"username": "yhy",
					"password": "Y2022",
					"column": [
						"dept_id",
						"parent_id",
						"unit_id",
						"ancestors",
						"dept_name",
						"dept_code",
						"base_dept_id",
						"order_num",
						"leader",
						"administrative_division",
						"manage_dept",
						"phone",
						"email",
						"status",
						"del_flag",
						"create_by",
						"create_time",
						"update_by",
						"update_time",
						"p_id_province",
						"rs_code",
						"rs_name",
						"rs_level",
						"rs_sq_code",
						"rs_sq_name"
					],
					"splitPk": "",
					"connection": [
						{
							"table": [
								"sys_dept"
							],
							"jdbcUrl": [
								"jdbc:highgo://140.219.114.177:5833/bz_verify_exchange_dev"
							]
						}
					]
				}
			},
			"writer": {
				"name": "doriswriter",
				"parameter": {
					"loadUrl": [
						"153.139.211.213:8030"
					],
					"username": "admin",
					"password": "Yawei@1234",
					"column": [
						"dept_id",
						"parent_id",
						"unit_id",
						"ancestors",
						"dept_name",
						"dept_code",
						"base_dept_id",
						"order_num",
						"leader",
						"administrative_division",
						"manage_dept",
						"phone",
						"email",
						"status",
						"del_flag",
						"create_by",
						"create_time",
						"update_by",
						"update_time",
						"p_id_province",
						"rs_code",
						"rs_name",
						"rs_level",
						"rs_sq_code",
						"rs_sq_name"
					],
					"loadProps": {
						"format": "json",
						"strip_outer_array": true
					},
					"connection": [
						{
							"database": "ibdp_ods",
							"table": [
								"sys_dept_rdhs2g"
							],
							"jdbcUrl": "jdbc:mysql://153.139.211.213:9030/ibdp_ods"
						}
					]
				}
			}
		}
	}
}
```

执行的Json 如上 读取插件没有问题 我已经使用streamwriter 将数据打印出来了 ，但是无法写入到doris 里面 的日志已经发出来了 ，期待您的回复！

### Version

4.1.3 (Default)

### OS Type

Linux (Default), Windows

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
16:29:39.416 [reader-0-0] INFO com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task -- Begin reading records by executing SQL query: [select dept_id,parent_id,unit_id,ancestors,dept_name,dept_code,base_dept_id,order_num,leader,administrative_division,manage_dept,phone,email,status,del_flag,create_by,create_time,update_by,update_time,p_id_province,rs_code,rs_name,rs_level,rs_sq_code,rs_sq_name from sys_dept ].
16:29:39.426 [writer-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.WriterRunner -- task writer starts to do prepare ...
16:29:39.426 [writer-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.WriterRunner -- task writer starts to write ...
16:29:41.876 [writer-0-0] DEBUG com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager -- Doris buffer Sinking triggered: rows[2048] label[addax_doris_writer_f5e5d31f-4cf6-484c-ad68-7c0f414a9bb5].
16:29:41.894 [Thread-2] DEBUG com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager -- Async stream load: rows[2048] bytes[718132] label[addax_doris_writer_f5e5d31f-4cf6-484c-ad68-7c0f414a9bb5].
16:29:41.918 [Thread-2] INFO com.wgzhao.addax.plugin.writer.doriswriter.DorisStreamLoadObserver -- Start to join batch data: rows[2048] bytes[718132] label[addax_doris_writer_f5e5d31f-4cf6-484c-ad68-7c0f414a9bb5].
16:29:41.919 [Thread-2] INFO com.wgzhao.addax.plugin.writer.doriswriter.DorisStreamLoadObserver -- 正在执行流加载到: http://153.139.211.213:8030/api/ibdp_ods/sys_dept_rdhs2g/_stream_load'，大小: '720181'
Exception in thread "Thread-2" java.lang.NoSuchMethodError: org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()[Ljava/lang/ClassLoader;
	at org.apache.logging.log4j.core.util.WatchManager.getEventServices(WatchManager.java:160)
	at org.apache.logging.log4j.core.util.WatchManager.<init>(WatchManager.java:137)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:140)
	at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
	at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
	at org.apache.commons.logging.impl.Log4jApiLogFactory$LogAdapter.getContext(Log4jApiLogFactory.java:161)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
	at org.apache.commons.logging.impl.Log4jApiLogFactory.getInstance(Log4jApiLogFactory.java:203)
	at org.apache.commons.logging.impl.Log4jApiLogFactory.getInstance(Log4jApiLogFactory.java:198)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:987)
	at org.apache.http.impl.client.DefaultRedirectStrategy.<init>(DefaultRedirectStrategy.java:75)
	at org.apache.http.impl.client.DefaultRedirectStrategy.<init>(DefaultRedirectStrategy.java:90)
	at org.apache.http.impl.client.DefaultRedirectStrategy.<clinit>(DefaultRedirectStrategy.java:85)
	at com.wgzhao.addax.plugin.writer.doriswriter.DorisStreamLoadObserver.put(DorisStreamLoadObserver.java:187)
	at com.wgzhao.addax.plugin.writer.doriswriter.DorisStreamLoadObserver.streamLoad(DorisStreamLoadObserver.java:95)
	at com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager.asyncFlush(DorisWriterManager.java:178)
	at com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager.access$000(DorisWriterManager.java:39)
	at com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager$1.run(DorisWriterManager.java:149)
	at java.lang.Thread.run(Thread.java:750)
16:29:42.404 [writer-0-0] DEBUG com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager -- Doris buffer Sinking triggered: rows[2048] label[addax_doris_writer_db901fce-b712-4836-ab01-760bef2c7e90].
16:29:42.449 [reader-0-0] INFO com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task -- Finished reading records by executing SQL query: [select dept_id,parent_id,unit_id,ancestors,dept_name,dept_code,base_dept_id,order_num,leader,administrative_division,manage_dept,phone,email,status,del_flag,create_by,create_time,update_by,update_time,p_id_province,rs_code,rs_name,rs_level,rs_sq_code,rs_sq_name from sys_dept ].
16:29:42.451 [reader-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.ReaderRunner -- task reader starts to do post ...
16:29:42.451 [reader-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.ReaderRunner -- task reader starts to do destroy ...
16:29:42.479 [writer-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.WriterRunner -- task writer starts to do post ...
16:29:42.479 [writer-0-0] DEBUG com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager -- Doris Sink is about to close: label[addax_doris_writer_d9acb317-0a32-4cad-879f-58edecd11eca].
16:29:49.414 [job-0] DEBUG com.wgzhao.addax.core.job.scheduler.AbstractScheduler -- com.wgzhao.addax.core.statistics.communication.Communication@9f6e406[
  counter={writeSucceedRecords=0, totalErrorBytes=0, percentage=0.0, totalReadRecords=0, writeSucceedBytes=0, byteSpeed=0, totalErrorRecords=0, recordSpeed=0, totalReadBytes=0}
  message={}
  state=RUNNING
  throwable=<null>
  timestamp=1711009789413
]
```

**Comment by wgzhao** [comment]
你这个还是报没有相应的 `log4j` 的包，你是下载的 4.1.3 版本吗？你的日志没有给全，看不到你运行的版本

**Comment by suiquantong** [comment]
已接受到你的信息或文件

**Comment by suiquantong** [comment]
我用的是4.1.5 版本 我已经将 这些包上传了 但是还是这个样子
![image](https://github.com/wgzhao/Addax/assets/37520861/3411d3b6-d4fd-49d8-977f-f74275521f07)

**Comment by wgzhao** [comment]
请粘贴任务运行的完整日志

**Comment by suiquantong** [comment]
```
10:27:28.932 [main] INFO com.wgzhao.addax.core.job.JobContainer -- The jobContainer begins to process the job.
10:27:28.947 [main] DEBUG com.wgzhao.addax.core.job.JobContainer -- The jobContainer begins to perform pre-handle ...
10:27:28.947 [main] DEBUG com.wgzhao.addax.core.job.JobContainer -- The jobContainer begins to perform init ...
10:27:29.334 [job-0] INFO com.wgzhao.addax.rdbms.reader.util.OriginalConfPretreatmentUtil -- Available jdbcUrl [jdbc:postgresql://151.138.115.56:5432/yawei_ibdp?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=tru].
10:27:29.621 [job-0] INFO com.wgzhao.addax.rdbms.reader.util.OriginalConfPretreatmentUtil -- The table [test_demo] has columns [id,dept_id,user_id,order_num,test_key,value,version,create_time,create_by,update_time,update_by,del_flag].
10:27:29.622 [job-0] DEBUG com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Job -- After the job is initialized, the job configuration is now as follows::[
{"username":"postgres","password":"Yawei@2224","column":"id,dept_id,user_id,order_num,test_key,value,version,create_time,create_by,update_time,update_by,del_flag","splitPk":"","connection":[{"table":["test_demo"],"jdbcUrl":"jdbc:postgresql://151.138.115.56:5432/ibdp?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=tru"}],"fetchSize":2048,"isTableMode":true,"tableNumber":1,"columnList":["id","dept_id","user_id","order_num","test_key","value","version","create_time","create_by","update_time","update_by","del_flag"]}
]
10:27:29.628 [job-0] DEBUG com.wgzhao.addax.core.job.JobContainer -- The jobContainer begins to perform prepare ...
10:27:29.628 [job-0] INFO com.wgzhao.addax.core.job.JobContainer -- The Reader.Job [postgresqlreader] perform prepare work .
10:27:29.628 [job-0] INFO com.wgzhao.addax.core.job.JobContainer -- The Writer.Job [doriswriter] perform prepare work .
10:27:29.630 [job-0] DEBUG com.wgzhao.addax.core.job.JobContainer -- The jobContainer begins to perform split ...
10:27:29.631 [job-0] INFO com.wgzhao.addax.core.job.JobContainer -- Job set Channel-Number to 2 channel(s).
10:27:29.633 [job-0] INFO com.wgzhao.addax.core.job.JobContainer -- The Reader.Job [postgresqlreader] is divided into [1] task(s).
10:27:29.633 [job-0] INFO com.wgzhao.addax.core.job.JobContainer -- The Writer.Job [doriswriter] is divided into [1] task(s).
10:27:29.633 [job-0] DEBUG com.wgzhao.addax.core.job.JobContainer -- The transformer configuration:[] 
10:27:29.658 [job-0] DEBUG com.wgzhao.addax.core.job.JobContainer -- The contentConfig configuration:[{"internal":{"reader":{"parameter":{"username":"postgres","password":"Yawei@2224","column":"id,dept_id,user_id,order_num,test_key,value,version,create_time,create_by,update_time,update_by,del_flag","splitPk":"","fetchSize":2048,"isTableMode":true,"tableNumber":1,"columnList":["id","dept_id","user_id","order_num","test_key","value","version","create_time","create_by","update_time","update_by","del_flag"],"jdbcUrl":"jdbc:postgresql://151.138.115.56:5432/yai_ibdp?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=tru","loadBalanceResourceMark":"151.138.115.56","table":"test_demo","querySql":"select id,dept_id,user_id,order_num,test_key,value,version,create_time,create_by,update_time,update_by,del_flag from test_demo "},"name":"postgresqlreader"},"writer":{"parameter":{"loadUrl":["151.139.217.213:8030"],"username":"ywei","password":"Yawei@2224","batchSize":1024,"column":["id","dept_id","user_id","order_num","test_key","value","version","create_time","create_by","update_time","update_by","del_flag"],"connection":[{"table":["test_demo"],"database":"example_db","jdbcUrl":"jdbc:mysql://151.139.217.213:9030/example_db"}],"loadProps":{"format":"json","strip_outer_array":true}},"name":"doriswriter"},"taskId":0},"keys":["reader.parameter.columnList[4]","writer.parameter.connection[0].database","writer.parameter.column[11]","reader.parameter.columnList[2]","reader.parameter.columnList[0]","writer.parameter.column[1]","reader.parameter.columnList[11]","writer.parameter.connection[0].table[0]","reader.parameter.splitPk","writer.parameter.loadProps.strip_outer_array","reader.parameter.fetchSize","reader.parameter.password","writer.name","reader.parameter.querySql","reader.parameter.loadBalanceResourceMark","writer.parameter.password","reader.name","writer.parameter.column[5]","writer.parameter.column[3]","reader.parameter.columnList[9]","writer.parameter.column[9]","reader.parameter.columnList[7]","writer.parameter.column[7]","reader.parameter.columnList[5]","writer.parameter.column[10]","reader.parameter.columnList[3]","reader.parameter.columnList[1]","writer.parameter.column[2]","reader.parameter.column","writer.parameter.column[0]","writer.parameter.connection[0].jdbcUrl","reader.parameter.columnList[10]","reader.parameter.jdbcUrl","writer.parameter.batchSize","writer.parameter.loadProps.format","reader.parameter.tableNumber","reader.parameter.table","writer.parameter.column[6]","writer.parameter.loadUrl[0]","writer.parameter.column[4]","reader.parameter.isTableMode","reader.parameter.columnList[8]","reader.parameter.username","reader.parameter.columnList[6]","taskId","writer.parameter.username","writer.parameter.column[8]"],"secretKeyPathSet":[]}] 
10:27:29.658 [job-0] DEBUG com.wgzhao.addax.core.job.JobContainer -- The jobContainer begins to perform schedule ...
10:27:29.662 [job-0] INFO com.wgzhao.addax.core.job.JobContainer -- The Scheduler launches [1] taskGroup(s).
10:27:29.669 [job-0] INFO com.wgzhao.addax.common.statistics.VMInfo -- VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
10:27:29.686 [taskGroup-0] DEBUG com.wgzhao.addax.core.taskgroup.TaskGroupContainer -- The task configuration [0 for taskGroup[[{"internal":{"reader":{"parameter":{"username":"postgres","password":"Yawei@1234","column":"id,dept_id,user_id,order_num,test_key,value,version,create_time,create_by,update_time,update_by,del_flag","splitPk":"","fetchSize":2048,"isTableMode":true,"tableNumber":1,"columnList":["id","dept_id","user_id","order_num","test_key","value","version","create_time","create_by","update_time","update_by","del_flag"],"jdbcUrl":"jdbc:postgresql://151.138.115.56:5432/yawei_ibdp?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=tru","loadBalanceResourceMark":"151.138.115.56","table":"test_demo","querySql":"select id,dept_id,user_id,order_num,test_key,value,version,create_time,create_by,update_time,update_by,del_flag from test_demo "},"name":"postgresqlreader"},"writer":{"parameter":{"loadUrl":["151.139.217.213:8030"],"username":"yaiwei","password":"Yawei@1234","batchSize":1024,"column":["id","dept_id","user_id","order_num","test_key","value","version","create_time","create_by","update_time","update_by","del_flag"],"connection":[{"table":["test_demo"],"database":"example_db","jdbcUrl":"jdbc:mysql://151.139.217.213:9030/exmple_db"}],"loadProps":{"format":"json","strip_outer_array":true}},"name":"doriswriter"},"taskId":0},"keys":["reader.parameter.columnList[4]","writer.parameter.connection[0].database","writer.parameter.column[11]","reader.parameter.columnList[2]","reader.parameter.columnList[0]","writer.parameter.column[1]","reader.parameter.columnList[11]","writer.parameter.connection[0].table[0]","reader.parameter.splitPk","writer.parameter.loadProps.strip_outer_array","reader.parameter.fetchSize","reader.parameter.password","writer.name","reader.parameter.querySql","reader.parameter.loadBalanceResourceMark","writer.parameter.password","reader.name","writer.parameter.column[5]","writer.parameter.column[3]","reader.parameter.columnList[9]","writer.parameter.column[9]","reader.parameter.columnList[7]","writer.parameter.column[7]","reader.parameter.columnList[5]","writer.parameter.column[10]","reader.parameter.columnList[3]","reader.parameter.columnList[1]","writer.parameter.column[2]","reader.parameter.column","writer.parameter.column[0]","writer.parameter.connection[0].jdbcUrl","reader.parameter.columnList[10]","reader.parameter.jdbcUrl","writer.parameter.batchSize","writer.parameter.loadProps.format","reader.parameter.tableNumber","reader.parameter.table","writer.parameter.column[6]","writer.parameter.loadUrl[0]","writer.parameter.column[4]","reader.parameter.isTableMode","reader.parameter.columnList[8]","reader.parameter.username","reader.parameter.columnList[6]","taskId","writer.parameter.username","writer.parameter.column[8]"],"secretKeyPathSet":[]}]]
10:27:29.686 [taskGroup-0] INFO com.wgzhao.addax.core.taskgroup.TaskGroupContainer -- The taskGroupId=[0] started [1] channels for [1] tasks.
10:27:29.692 [taskGroup-0] INFO com.wgzhao.addax.core.transport.channel.Channel -- The Channel set byte_speed_limit to -1, No bps activated.
10:27:29.692 [taskGroup-0] INFO com.wgzhao.addax.core.transport.channel.Channel -- The Channel set record_speed_limit to -1, No tps activated.
10:27:29.703 [job-0] DEBUG com.wgzhao.addax.core.job.scheduler.AbstractScheduler -- com.wgzhao.addax.core.statistics.communication.Communication@58fe0499[
  counter={}
  message={}
  state=RUNNING
  throwable=<null>
  timestamp=1712802449684
]
10:27:29.709 [taskGroup-0] DEBUG com.wgzhao.addax.core.taskgroup.TaskGroupContainer -- TaskGroup[0] TaskId[0] AttemptCount[1] has started
10:27:29.709 [writer-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.WriterRunner -- task writer starts to do init ...
10:27:29.709 [reader-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.ReaderRunner -- task reader starts to do init ...
10:27:29.718 [reader-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.ReaderRunner -- task reader starts to do prepare ...
10:27:29.718 [reader-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.ReaderRunner -- task reader starts to read ...
10:27:29.718 [reader-0-0] INFO com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task -- Begin reading records by executing SQL query: [select id,dept_id,user_id,order_num,test_key,value,version,create_time,create_by,update_time,update_by,del_flag from test_demo ].
10:27:29.733 [writer-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.WriterRunner -- task writer starts to do prepare ...
10:27:29.733 [writer-0-0] DEBUG com.wgzhao.addax.core.taskgroup.runner.WriterRunner -- task writer starts to write ...
10:27:33.155 [Doris-interval-flush] INFO com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager -- Doris interval Sinking triggered: label[addax_doris_writer_dd30c692-85fc-497e-953c-593553259ee4].
10:27:34.063 [writer-0-0] DEBUG com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager -- Doris buffer Sinking triggered: rows[1024] label[addax_doris_writer_5086f452-fe9d-4aac-a556-02b67b13e19e].
10:27:34.070 [Thread-2] DEBUG com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager -- Async stream load: rows[1024] bytes[271688] label[addax_doris_writer_5086f452-fe9d-4aac-a556-02b67b13e19e].
10:27:34.083 [Thread-2] INFO com.wgzhao.addax.plugin.writer.doriswriter.DorisStreamLoadObserver -- Start to join batch data: rows[1024] bytes[271688] label[addax_doris_writer_5086f452-fe9d-4aac-a556-02b67b13e19e].
10:27:41.980 [job-0] DEBUG com.wgzhao.addax.core.job.scheduler.AbstractScheduler -- com.wgzhao.addax.core.statistics.communication.Communication@29df4d43[
  counter={writeSucceedRecords=0, totalErrorBytes=0, percentage=0.0, totalReadRecords=0, writeSucceedBytes=0, byteSpeed=0, totalErrorRecords=0, recordSpeed=0, totalReadBytes=0}
  message={}
  state=RUNNING
  throwable=<null>
  timestamp=1712802461979
]
10:27:41.980 [Thread-2] INFO com.wgzhao.addax.plugin.writer.doriswriter.DorisStreamLoadObserver -- 正在执行流加载到: http://151.139.217.213:8030/api/example_db/test_demo/_stream_load'，大小: '272713'
10:27:42.380 [writer-0-0] DEBUG com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager -- Doris buffer Sinking triggered: rows[1024] label[addax_doris_writer_8db0596e-da09-48aa-9872-c56143c19ac3].
10:27:42.382 [job-0] INFO com.wgzhao.addax.core.statistics.container.communicator.job.StandAloneJobContainerCommunicator -- Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
10:27:42.391 [writer-0-0] DEBUG com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager -- Doris buffer Sinking triggered: rows[1024] label[addax_doris_writer_64d700bd-db13-43f0-846d-22ea28c44ade].
Exception in thread "Thread-2" java.lang.NoSuchMethodError: org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()[Ljava/lang/ClassLoader;
	at org.apache.logging.log4j.core.util.WatchManager.getEventServices(WatchManager.java:160)
	at org.apache.logging.log4j.core.util.WatchManager.<init>(WatchManager.java:137)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:140)
	at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
	at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
	at org.apache.commons.logging.impl.Log4jApiLogFactory$LogAdapter.getContext(Log4jApiLogFactory.java:161)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
	at org.apache.commons.logging.impl.Log4jApiLogFactory.getInstance(Log4jApiLogFactory.java:203)
	at org.apache.commons.logging.impl.Log4jApiLogFactory.getInstance(Log4jApiLogFactory.java:198)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:987)
	at org.apache.http.impl.client.DefaultRedirectStrategy.<init>(DefaultRedirectStrategy.java:75)
	at org.apache.http.impl.client.DefaultRedirectStrategy.<init>(DefaultRedirectStrategy.java:90)
	at org.apache.http.impl.client.DefaultRedirectStrategy.<clinit>(DefaultRedirectStrategy.java:85)
	at com.wgzhao.addax.plugin.writer.doriswriter.DorisStreamLoadObserver.put(DorisStreamLoadObserver.java:186)
	at com.wgzhao.addax.plugin.writer.doriswriter.DorisStreamLoadObserver.streamLoad(DorisStreamLoadObserver.java:94)
	at com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager.asyncFlush(DorisWriterManager.java:178)
	at com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager.access$000(DorisWriterManager.java:39)
	at com.wgzhao.addax.plugin.writer.doriswriter.DorisWriterManager$1.run(DorisWriterManager.java:149)
	at java.lang.Thread.run(Thread.java:750)
10:27:52.382 [job-0] DEBUG com.wgzhao.addax.core.job.scheduler.AbstractScheduler -- com.wgzhao.addax.core.statistics.communication.Communication@75390459[
  counter={writeSucceedRecords=3072, readSucceedRecords=3584, totalErrorBytes=0, writeSucceedBytes=252178, byteSpeed=12930, totalErrorRecords=0, recordSpeed=156, waitReaderTime=12579989900, writeReceivedBytes=252178, waitWriterTime=1643300, percentage=0.0, totalReadRecords=3584, writeReceivedRecords=3072, readSucceedBytes=294395, totalReadBytes=294395}
  message={}
  state=RUNNING
  throwable=<null>
  timestamp=1712802472382
]
```
