### ISSUE TITLE
[Bug]: influxdbreader error

### ISSUE THREAD

**Issue by lordk911** [wgzhao/Addax#1071]
### What happened?

bin/addax.sh job/influxdb2stream.json

```
{
  "job": {
    "content": [
      {
        "reader": {
          "name": "influxdbreader",
          "parameter": {
            "column": [
              "*"
            ],
            "connection": [
              {
                "endpoint": "http://xxx:8086",
                "database": "devops",
                "table": "job"
              }
            ],
            "username": "xx",
            "password": "xxxx"
          }
        },
        "writer": {
          "name": "streamwriter",
          "parameter": {
            "print": "true"
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "bytes": -1,
        "channel": 1
      }
    }
  }
}
```

### Version

4.1.5

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### influxdb Version

influxdb 1.x

### Relevant log output

```shell-script
2024-08-16 10:45:04.976 [       job-0] ERROR Engine               - com.wgzhao.addax.common.exception.AddaxException: java.lang.ClassNotFoundException: com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReader$Job
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.wgzhao.addax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:153)
        at com.wgzhao.addax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:92)
        at com.wgzhao.addax.core.job.JobContainer.initJobReader(JobContainer.java:580)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:265)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:122)
        at com.wgzhao.addax.core.Engine.start(Engine.java:62)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:113)
        at com.wgzhao.addax.core.Engine.main(Engine.java:139)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:157)
        at com.wgzhao.addax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:92)
        at com.wgzhao.addax.core.job.JobContainer.initJobReader(JobContainer.java:580)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:265)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:122)
        at com.wgzhao.addax.core.Engine.start(Engine.java:62)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:113)
        at com.wgzhao.addax.core.Engine.main(Engine.java:139)
Caused by: java.lang.ClassNotFoundException: com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReader$Job
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.wgzhao.addax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:153)
        ... 7 more
```

**Comment by lordk911** [comment]
```
jar -tvf influxdbreader-4.1.5.jar 
     0 Tue Jun 11 21:31:40 CST 2024 META-INF/
   130 Tue Jun 11 21:31:38 CST 2024 META-INF/MANIFEST.MF
     0 Tue Jun 11 21:31:40 CST 2024 com/
     0 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/
     0 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/addax/
     0 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/addax/plugin/
     0 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/addax/plugin/reader/
     0 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/addax/plugin/reader/influxdb2reader/
   175 Tue Jun 11 21:31:40 CST 2024 plugin.json
   392 Tue Jun 11 21:31:40 CST 2024 plugin_job_template.json
   812 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/addax/plugin/reader/influxdb2reader/InfluxDBKey.class
  7270 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/addax/plugin/reader/influxdb2reader/InfluxDBReaderTask.class
  2874 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/addax/plugin/reader/influxdb2reader/InfluxDBReader$Job.class
  1618 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/addax/plugin/reader/influxdb2reader/InfluxDBReader$Task.class
   574 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/addax/plugin/reader/influxdb2reader/InfluxDBReader.class
  2074 Tue Jun 11 21:31:40 CST 2024 com/wgzhao/addax/plugin/reader/influxdb2reader/InfluxDBReaderErrorCode.class
     0 Tue Jun 11 21:31:40 CST 2024 META-INF/maven/
     0 Tue Jun 11 21:31:40 CST 2024 META-INF/maven/com.wgzhao.addax/
     0 Tue Jun 11 21:31:40 CST 2024 META-INF/maven/com.wgzhao.addax/influxdbreader/
  3042 Tue Jun 11 21:17:16 CST 2024 META-INF/maven/com.wgzhao.addax/influxdbreader/pom.xml
   115 Tue Jun 11 21:31:40 CST 2024 META-INF/maven/com.wgzhao.addax/influxdbreader/pom.properties
```

**Comment by lordk911** [comment]
if I change plugin.json to use `com.wgzhao.addax.plugin.reader. influxdb2reader.InfluxDBReader` will got error:

```
2024-08-16 10:54:55.091 [  reader-0-0] ERROR ReaderRunner         - Reader runner Received Exceptions:
java.lang.NullPointerException: null
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReaderTask.<init>(InfluxDBReaderTask.java:61)
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReader$Task.init(InfluxDBReader.java:100)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:70)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "reader-0-0" java.lang.NullPointerException
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReader$Task.destroy(InfluxDBReader.java:118)
        at com.wgzhao.addax.core.taskgroup.runner.AbstractRunner.destroy(AbstractRunner.java:47)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:105)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: java.lang.NullPointerException
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReaderTask.<init>(InfluxDBReaderTask.java:61)
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReader$Task.init(InfluxDBReader.java:100)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:70)
        at java.lang.Thread.run(Thread.java:748)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:188)
        at com.wgzhao.addax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReaderTask.<init>(InfluxDBReaderTask.java:61)
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReader$Task.init(InfluxDBReader.java:100)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:70)
        ... 1 more
2024-08-16 10:54:58.087 [       job-0] ERROR JobContainer         - The scheduler failed to run.
2024-08-16 10:54:58.089 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2024-08-16 10:54:58.089 [       job-0] ERROR Engine               - com.wgzhao.addax.common.exception.AddaxException: java.lang.NullPointerException
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReaderTask.<init>(InfluxDBReaderTask.java:61)
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReader$Task.init(InfluxDBReader.java:100)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:70)
        at java.lang.Thread.run(Thread.java:748)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:63)
        at com.wgzhao.addax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:107)
        at com.wgzhao.addax.core.job.JobContainer.schedule(JobContainer.java:440)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:128)
        at com.wgzhao.addax.core.Engine.start(Engine.java:62)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:113)
        at com.wgzhao.addax.core.Engine.main(Engine.java:139)
Caused by: java.lang.NullPointerException
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReaderTask.<init>(InfluxDBReaderTask.java:61)
        at com.wgzhao.addax.plugin.reader.influxdb2reader.InfluxDBReader$Task.init(InfluxDBReader.java:100)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:70)
        at java.lang.Thread.run(Thread.java:748)
```
