### ISSUE TITLE
[Bug]: Mysql到HDFS parquet，Decimal字段的值存在空时写Parquet报长度不匹配。

### ISSUE THREAD

**Issue by svea-vip** [wgzhao/Addax#1109]
### What happened?

我自己修改代码做过微量调整，异常栈抛出的行数可能有差异。

```

[INFO] 2024-09-04 18:03:14.745 +0800 -  -> 2024-09-04 18:03:13.967 [  writer-0-1] ERROR WriterRunner         - Writer Runner Received Exceptions:
	java.lang.IllegalArgumentException: Fixed Binary size 0 does not match field type length 16
		at org.apache.parquet.column.values.plain.FixedLenByteArrayPlainValuesWriter.writeBytes(FixedLenByteArrayPlainValuesWriter.java:56)
		at org.apache.parquet.column.impl.ColumnWriterBase.write(ColumnWriterBase.java:241)
		at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.addBinary(MessageColumnIO.java:476)
		at org.apache.parquet.example.data.simple.BinaryValue.writeValue(BinaryValue.java:45)
		at org.apache.parquet.example.data.simple.SimpleGroup.writeValue(SimpleGroup.java:233)
		at org.apache.parquet.example.data.GroupWriter.writeGroup(GroupWriter.java:51)
		at org.apache.parquet.example.data.GroupWriter.write(GroupWriter.java:37)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:85)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:35)
		at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:138)
		at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:310)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:614)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:411)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:77)
		at java.lang.Thread.run(Thread.java:745)
	Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: java.lang.IllegalArgumentException: Fixed Binary size 0 does not match field type length 16
		at org.apache.parquet.column.values.plain.FixedLenByteArrayPlainValuesWriter.writeBytes(FixedLenByteArrayPlainValuesWriter.java:56)
		at org.apache.parquet.column.impl.ColumnWriterBase.write(ColumnWriterBase.java:241)
		at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.addBinary(MessageColumnIO.java:476)
		at org.apache.parquet.example.data.simple.BinaryValue.writeValue(BinaryValue.java:45)
		at org.apache.parquet.example.data.simple.SimpleGroup.writeValue(SimpleGroup.java:233)
		at org.apache.parquet.example.data.GroupWriter.writeGroup(GroupWriter.java:51)
		at org.apache.parquet.example.data.GroupWriter.write(GroupWriter.java:37)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:85)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:35)
		at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:138)
		at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:310)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:614)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:411)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:77)
		at java.lang.Thread.run(Thread.java:745)
	
		at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
		at com.wgzhao.addax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:188)
		at com.wgzhao.addax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:44)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.lang.IllegalArgumentException: Fixed Binary size 0 does not match field type length 16
		at org.apache.parquet.column.values.plain.FixedLenByteArrayPlainValuesWriter.writeBytes(FixedLenByteArrayPlainValuesWriter.java:56)
		at org.apache.parquet.column.impl.ColumnWriterBase.write(ColumnWriterBase.java:241)
		at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.addBinary(MessageColumnIO.java:476)
		at org.apache.parquet.example.data.simple.BinaryValue.writeValue(BinaryValue.java:45)
		at org.apache.parquet.example.data.simple.SimpleGroup.writeValue(SimpleGroup.java:233)
		at org.apache.parquet.example.data.GroupWriter.writeGroup(GroupWriter.java:51)
		at org.apache.parquet.example.data.GroupWriter.write(GroupWriter.java:37)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:85)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:35)
		at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:138)
		at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:310)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:614)
	2024-09-04 18:03:13.978 [  writer-0-0] ERROR WriterRunner         - Writer Runner Received Exceptions:
	java.lang.IllegalArgumentException: Fixed Binary size 0 does not match field type length 16
		at org.apache.parquet.column.values.plain.FixedLenByteArrayPlainValuesWriter.writeBytes(FixedLenByteArrayPlainValuesWriter.java:56)
		at org.apache.parquet.column.impl.ColumnWriterBase.write(ColumnWriterBase.java:241)
		at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.addBinary(MessageColumnIO.java:476)
		at org.apache.parquet.example.data.simple.BinaryValue.writeValue(BinaryValue.java:45)
		at org.apache.parquet.example.data.simple.SimpleGroup.writeValue(SimpleGroup.java:233)
		at org.apache.parquet.example.data.GroupWriter.writeGroup(GroupWriter.java:51)
		at org.apache.parquet.example.data.GroupWriter.write(GroupWriter.java:37)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:85)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:35)
		at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:138)
		at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:310)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:614)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:411)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:77)
		at java.lang.Thread.run(Thread.java:745)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:411)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:77)
		... 1 more
	2024-09-04 18:03:14.504 [       job-0] ERROR JobContainer         - The scheduler failed to run.
	2024-09-04 18:03:14.508 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 128 records, 19368 bytes | Speed 18.91KB/s, 128 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.001s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
	2024-09-04 18:03:14.513 [       job-0] ERROR Engine               - com.wgzhao.addax.common.exception.AddaxException: java.lang.IllegalArgumentException: Fixed Binary size 0 does not match field type length 16
		at org.apache.parquet.column.values.plain.FixedLenByteArrayPlainValuesWriter.writeBytes(FixedLenByteArrayPlainValuesWriter.java:56)
		at org.apache.parquet.column.impl.ColumnWriterBase.write(ColumnWriterBase.java:241)
		at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.addBinary(MessageColumnIO.java:476)
		at org.apache.parquet.example.data.simple.BinaryValue.writeValue(BinaryValue.java:45)
		at org.apache.parquet.example.data.simple.SimpleGroup.writeValue(SimpleGroup.java:233)
		at org.apache.parquet.example.data.GroupWriter.writeGroup(GroupWriter.java:51)
		at org.apache.parquet.example.data.GroupWriter.write(GroupWriter.java:37)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:85)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:35)
		at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:138)
		at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:310)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:614)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:411)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:77)
		at java.lang.Thread.run(Thread.java:745)
	
		at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
		at com.wgzhao.addax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:63)
		at com.wgzhao.addax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:107)
		at com.wgzhao.addax.core.job.JobContainer.schedule(JobContainer.java:440)
		at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:128)
		at com.wgzhao.addax.core.Engine.start(Engine.java:62)
		at com.wgzhao.addax.core.Engine.entry(Engine.java:113)
		at com.wgzhao.addax.core.Engine.main(Engine.java:139)
	Caused by: java.lang.IllegalArgumentException: Fixed Binary size 0 does not match field type length 16
		at org.apache.parquet.column.values.plain.FixedLenByteArrayPlainValuesWriter.writeBytes(FixedLenByteArrayPlainValuesWriter.java:56)
		at org.apache.parquet.column.impl.ColumnWriterBase.write(ColumnWriterBase.java:241)
		at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.addBinary(MessageColumnIO.java:476)
		at org.apache.parquet.example.data.simple.BinaryValue.writeValue(BinaryValue.java:45)
		at org.apache.parquet.example.data.simple.SimpleGroup.writeValue(SimpleGroup.java:233)
		at org.apache.parquet.example.data.GroupWriter.writeGroup(GroupWriter.java:51)
		at org.apache.parquet.example.data.GroupWriter.write(GroupWriter.java:37)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:85)
		at org.apache.parquet.hadoop.example.GroupWriteSupport.write(GroupWriteSupport.java:35)
		at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:138)
		at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:310)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:614)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:411)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:77)
		at java.lang.Thread.run(Thread.java:745)
	
	err:	 exit status 2
	exit status 2

```

### Version

4.1.6 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
[hdfswriter-4.1.7-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16915117/hdfswriter-4.1.7-SNAPSHOT.jar.zip)

试下用上面的 jar 文件（需解压）替换当前的 jar 文件后，看能否解决你的问题，我在本地测试是可以的，不过我还需要进行更多场景的测试。
