### ISSUE TITLE
[Bug]: Mysql Reader 如果列名中包含关键字名，比如year、year_month之类的报语法检查错误

### ISSUE THREAD

**Issue by svea-vip** [wgzhao/Addax#1124]
### What happened?

Mysql Reader 如果列名中包含关键字名，比如year、year_month之类的报语法检查错误

### Version

4.1.7 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
com.wgzhao.addax.common.exception.AddaxException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'dec,update_time,id,year,jygs,update_man FROM bi.tb_r_xvyb_target' at line 1
		at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
		at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
		at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:245)
		at com.wgzhao.addax.plugin.reader.mysqlreader.MysqlReader$Task.startRead(MysqlReader.java:126)
		at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
		at java.lang.Thread.run(Thread.java:745)
```

**Comment by wgzhao** [comment]
请看文档说明 https://wgzhao.github.io/Addax/latest/reader/rdbmsreader/#column

**Comment by svea-vip** [comment]
是新版本的改动，之前4.0.12的版本，我看所有列的拼装都加了``

**Comment by wgzhao** [comment]
用新版本吧

**Comment by liuyitian0** [comment]
咱们有交流群吗?
