### ISSUE TITLE
[Bug]: influxdbreader 官方demo读取配置bug

### ISSUE THREAD

**Issue by Xm-Cui** [wgzhao/Addax#1157]
### What happened?

4.1.8版本，完全使用官网demo
https://wgzhao.github.io/Addax/4.1.8/reader/influxdbreader/

我修改后的配置文件
![image](https://github.com/user-attachments/assets/1b42317b-b5ff-482e-ae59-6b8346f1b84d)
注意，connection是数组的形式

然后启动
bin/addax.sh job/influxdb2stream.json

![image](https://github.com/user-attachments/assets/49964f90-8de4-4f41-9cd0-3b849050f2c5)
注意，connection已经变成对象了

然后就报错了
![image](https://github.com/user-attachments/assets/f1a37dba-00d3-4578-892d-1d44431e5349)

![image](https://github.com/user-attachments/assets/aa5782fc-f83d-43d2-84a2-1b8db3161d3c)

debug了一下
这里需要
![image](https://github.com/user-attachments/assets/31288e1f-07e2-4f76-ba16-5bdbe2f3ba4f)

解析出来是JSONObject
![image](https://github.com/user-attachments/assets/29c0d8a7-0f0e-4f63-8302-51fa9a01a8b8)

布出过程中在这行执行后报错
![image](https://github.com/user-attachments/assets/f89e65f0-039d-422e-80bc-674baa2eb9dc)

### Version

4.1.8 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
___      _     _            
 / _ \    | |   | |           
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  < 
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.1.8)

2024-10-09 17:34:42.690 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2024-10-09 17:34:42.705 [        main] INFO  Engine               - 
{
        "content":{
                "reader":{
                        "name":"influxdbreader",
                        "parameter":{
                                "column":[
                                        "*"
                                ],
                                "connection":{
                                        "endpoint":"http://192.168.0.87:8086",
                                        "database":"NOAA_water_database",
                                        "table":"h2o_feet"
                                },
                                "username":"admin",
                                "password":"*****"
                        }
                },
                "writer":{
                        "name":"streamwriter",
                        "parameter":{
                                "print":"true"
                        }
                }
        },
        "setting":{
                "speed":{
                        "bytes":-1,
                        "channel":1
                }
        }
}

2024-10-09 17:34:42.722 [        main] INFO  JobContainer         - The jobContainer begins to process the job.
2024-10-09 17:34:42.730 [       job-0] INFO  JobContainer         - The Reader.Job [influxdbreader] perform prepare work .
2024-10-09 17:34:42.731 [       job-0] INFO  JobContainer         - The Writer.Job [streamwriter] perform prepare work .
2024-10-09 17:34:42.731 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2024-10-09 17:34:42.731 [       job-0] INFO  JobContainer         - The Reader.Job [influxdbreader] is divided into [1] task(s).
2024-10-09 17:34:42.731 [       job-0] INFO  JobContainer         - The Writer.Job [streamwriter] is divided into [1] task(s).
2024-10-09 17:34:42.755 [       job-0] INFO  JobContainer         - The Scheduler launches [1] taskGroup(s).
2024-10-09 17:34:42.761 [ taskGroup-0] INFO  TaskGroupContainer   - The taskGroupId=[0] started [1] channels for [1] tasks.
2024-10-09 17:34:42.765 [ taskGroup-0] INFO  Channel              - The Channel set byte_speed_limit to -1, No bps activated.
2024-10-09 17:34:42.765 [ taskGroup-0] INFO  Channel              - The Channel set record_speed_limit to -1, No tps activated.
2024-10-09 17:38:00.772 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2024-10-09 17:38:00.770 [  reader-0-0] ERROR ReaderRunner         - Reader runner Received Exceptions:
java.lang.ClassCastException: com.alibaba.fastjson2.JSONObject cannot be cast to java.util.List
        at com.wgzhao.addax.common.util.Configuration.getList(Configuration.java:501)
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReaderTask.<init>(InfluxDBReaderTask.java:60)
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReader$Task.init(InfluxDBReader.java:100)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:70)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "reader-0-0" java.lang.NullPointerException
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReader$Task.destroy(InfluxDBReader.java:118)
        at com.wgzhao.addax.core.taskgroup.runner.AbstractRunner.destroy(AbstractRunner.java:47)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:105)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: java.lang.ClassCastException: com.alibaba.fastjson2.JSONObject cannot be cast to java.util.List
        at com.wgzhao.addax.common.util.Configuration.getList(Configuration.java:501)
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReaderTask.<init>(InfluxDBReaderTask.java:60)
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReader$Task.init(InfluxDBReader.java:100)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:70)
        at java.lang.Thread.run(Thread.java:748)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:188)
        at com.wgzhao.addax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: com.alibaba.fastjson2.JSONObject cannot be cast to java.util.List
        at com.wgzhao.addax.common.util.Configuration.getList(Configuration.java:501)
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReaderTask.<init>(InfluxDBReaderTask.java:60)
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReader$Task.init(InfluxDBReader.java:100)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:70)
        ... 1 more
2024-10-09 17:38:03.773 [       job-0] ERROR JobContainer         - The scheduler failed to run.
2024-10-09 17:38:03.776 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2024-10-09 17:38:03.777 [       job-0] ERROR Engine               - com.wgzhao.addax.common.exception.AddaxException: java.lang.ClassCastException: com.alibaba.fastjson2.JSONObject cannot be cast to java.util.List
        at com.wgzhao.addax.common.util.Configuration.getList(Configuration.java:501)
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReaderTask.<init>(InfluxDBReaderTask.java:60)
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReader$Task.init(InfluxDBReader.java:100)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:70)
        at java.lang.Thread.run(Thread.java:748)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:63)
        at com.wgzhao.addax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:107)
        at com.wgzhao.addax.core.job.JobContainer.schedule(JobContainer.java:440)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:128)
        at com.wgzhao.addax.core.Engine.start(Engine.java:62)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:113)
        at com.wgzhao.addax.core.Engine.main(Engine.java:139)
Caused by: java.lang.ClassCastException: com.alibaba.fastjson2.JSONObject cannot be cast to java.util.List
        at com.wgzhao.addax.common.util.Configuration.getList(Configuration.java:501)
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReaderTask.<init>(InfluxDBReaderTask.java:60)
        at com.wgzhao.addax.plugin.reader.influxdbreader.InfluxDBReader$Task.init(InfluxDBReader.java:100)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:70)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by wgzhao** [comment]
刚好今天已经修复了这个问题 b9faed6152317988b3c37ae

**Comment by Xm-Cui** [comment]
哈哈哈，这也太巧了，期待近期有定板

**Comment by wgzhao** [comment]
最近打算要发一个大版本，在回归测试时候，发现了没有改完的bug，其实还有几个插件也是这个问题，今天一并都修改了。
