### ISSUE TITLE
Oracle的date类型写入HDFS报错参数值不合法

### ISSUE THREAD

**Issue by XhivaW** [wgzhao/Addax#222]
release中下载3.2.5版本 自行编译 执行oracle导入hdfs的orc文件 报错如下：

=====START=====
2021-07-08 10:24:25.144 [0-0-0-writer] ERROR WriterRunner - Writer Runner Received Exceptions:
com.wgzhao.datax.common.exception.DataXException: Code:[HdfsWriter-02], Description:[您填写的参数值不合法.]. - 设置Orc数据行失败，源列类型: DATE, 目的原始类型:TIMESTAMP, 目的列Hive类型: timestamp, 字段名称: xxxxx, 源值: null
        at com.wgzhao.datax.common.exception.DataXException.asDataXException(DataXException.java:50)
        at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.setRow(HdfsHelper.java:769)
        at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.orcFileStartWrite(HdfsHelper.java:803)
        at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:499)
        at com.wgzhao.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "taskGroup-0" com.wgzhao.datax.common.exception.DataXException: Code:[HdfsWriter-02], Description:[您填写的参数值不合法.]. - 设置Orc数据行失败，源列类型: DATE, 目的原始类型:TIMESTAMP, 目的列Hive类型: timestamp, 字段名称: xxxxx, 源值: null
        at com.wgzhao.datax.common.exception.DataXException.asDataXException(DataXException.java:50)
        at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.setRow(HdfsHelper.java:769)
        at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.orcFileStartWrite(HdfsHelper.java:803)
        at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:499)
        at com.wgzhao.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
2021-07-08 10:24:25.322 [job-0] ERROR JobContainer - 运行scheduler出错.
=====END=====

使用原版开源datax正常执行

系统：centos 7
Java版本：1.8
addax版本：3.2.5

**Comment by XhivaW** [comment]
另外最新的代码版本编译后bin路径下没有可执行的datax.py或者addax.py文件 不知道是遗漏了还是迁移未完成

**Comment by wgzhao** [comment]
是空值处理不当导致的，`3.2.5` 版本重写了 HDFS 写入代码，空值处理和之前逻辑不同，我出一个补丁，稍晚发到这里。
感谢反馈

**Comment by wgzhao** [comment]
请下载这个版本[hdfswriter-3.2.5.jar.zip](https://github.com/wgzhao/Addax/files/6781213/hdfswriter-3.2.5.jar.zip)，解压后替换现在的版本，再测试是否正常

**Comment by XhivaW** [comment]
> 请下载这个版本[hdfswriter-3.2.5.jar.zip](https://github.com/wgzhao/Addax/files/6781213/hdfswriter-3.2.5.jar.zip)，解压后替换现在的版本，再测试是否正常

你好 这个版本测试正常 谢谢 我先把issue关闭了
顺便问下这次修改名称大概多久完成？

**Comment by wgzhao** [comment]
改名基本完成了，我正在做整体测试，希望这周能发布一个“大”版本。
