### ISSUE TITLE
hdfswriter写入Parquet文件任意数据格式均报错

### ISSUE THREAD

**Issue by XhivaW** [wgzhao/Addax#223]
执行如下测试脚本：

```json
{
  "job": {
      "content": [
          {
              "writer": {
                  "parameter": {
                      "writeMode": "overwrite", 
                      "column": [
                          {
                              "type": "string", 
                              "name": "a"
                          }
                      ], 
                      "fieldDelimiter": "\u0001", 
                      "fileType": "parquet", 
                      "compress": "NONE", 
                      "fileName": "sample_", 
                      "path": "/tmp/target", 
                      "defaultFS": "hdfs://xxxx:8020"
                  }, 
                  "name": "hdfswriter"
              }, 
              "reader": {
                "name": "streamreader",
                "parameter": {
                  "column": [
                    {
                      "value": "abcde",
                      "type": "string"
                    }
                  ],
                  "sliceRecordCount": 1000
                }
              }
            }
          ], 
      "setting": {
          "speed": {
              "channel": 1
          }
      }
  }
}
```

执行报错如下：

```code
java.lang.IllegalArgumentException: No enum constant com.wgzhao.datax.plugin.writer.hdfswriter.SupportHiveDataType.string
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.wgzhao.datax.plugin.writer.hdfswriter.SupportHiveDataType.valueOf(SupportHiveDataType.java:22)
        at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.transportParRecord(HdfsHelper.java:222)
        at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:701)
        at com.wgzhao.datax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:504)
        at com.wgzhao.datax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
```

测试脚本中string改为任意parquet支持的其他数据格式均报一样的格式错误 但使用orc格式可以顺利执行

 - OS: CentOS 7
 - JDK Version 1.8
 - Addax Version 3.2.5

**Comment by wgzhao** [comment]
感谢反馈

`parquet` 这部份代码是有一些问题，因为在我实际使用中，绝大部分都是使用 ORC 格式，所以重点测试了 ORC 格式。
发布 `3.2.5` 后， 整个 hdfswriter 插件基本重写了，你反馈的这个问题在 master 分支上已经解决。
如果你着急使用当前版本，可以稍晚点我上传一个补丁包上来。

**Comment by XhivaW** [comment]
> 感谢反馈
> 
> `parquet` 这部份代码是有一些问题，因为在我实际使用中，绝大部分都是使用 ORC 格式，所以重点测试了 ORC 格式。
> 发布 `3.2.5` 后， 整个 hdfswriter 插件基本重写了，你反馈的这个问题在 master 分支上已经解决。
> 如果你着急使用当前版本，可以稍晚点我上传一个补丁包上来。

谢谢回复 如果方便的话 麻烦传下临时补丁哈
我等下个版本发布的时候再关闭这个issue
再次感谢

**Comment by wgzhao** [comment]
好的，要稍晚一点

**Comment by wgzhao** [comment]
请使用附件替换有问题的jar文件，在进行测试。
[hdfswriter-3.2.5.jar.zip](https://github.com/wgzhao/Addax/files/6782755/hdfswriter-3.2.5.jar.zip)

下面是本地测试情况：

```json
[root@gitback 3.2.5]# bin/datax.py test.json
2021-07-08 16:03:45.143 [main] INFO  Engine - DataX version 3.2.5
2021-07-08 16:03:45.264 [main] INFO  VMInfo - VMInfo# operatingSystem class => com.sun.management.internal.OperatingSystemImpl
2021-07-08 16:03:45.283 [main] INFO  Engine -
{
	"content":[
		{
			"reader":{
				"parameter":{
					"column":[
						{
							"type":"string",
							"value":"abcde"
						}
					],
					"sliceRecordCount":1000
				},
				"name":"streamreader"
			},
			"writer":{
				"parameter":{
					"column":[
						{
							"name":"a",
							"type":"string"
						}
					],
                                  "fieldDelimiter": "\u0001", 
                                  "fileType": "parquet", 
                                  "compress": "NONE", 
                                  "fileName": "sample_", 
                                  "path": "/tmp/target", 
                                  "defaultFS": "hdfs://xxxx:8020"
				},
				"name":"hdfswriter"
			}
		}
	],
	"setting":{
		"speed":{
			"channel":1
		}
	}
}

2021-07-08 16:03:45.297 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2021-07-08 16:03:45.297 [main] INFO  JobContainer - DataX jobContainer starts job.
2021-07-08 16:03:45.298 [main] INFO  JobContainer - Set jobId = 0
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-07-08 16:03:46.097 [job-0] INFO  JobContainer - DataX Reader.Job [streamreader] do prepare work .
2021-07-08 16:03:46.098 [job-0] INFO  JobContainer - DataX Writer.Job [hdfswriter] do prepare work .
2021-07-08 16:03:46.320 [job-0] INFO  JobContainer - Job set Channel-Number to 1 channels.
2021-07-08 16:03:46.321 [job-0] INFO  JobContainer - DataX Reader.Job [streamreader] splits to [1] tasks.
2021-07-08 16:03:46.322 [job-0] INFO  HdfsWriter$Job - begin do split...
2021-07-08 16:03:46.330 [job-0] INFO  HdfsWriter$Job - splited write file name:[hdfs://xxxxx:8020/tmp/target/.5d06bcf4_a082_4702_ba89_31f9a8f2ea0b/sample___9f690b1d_eefe_4119_ac3f_12694f110ca8]
2021-07-08 16:03:46.331 [job-0] INFO  HdfsWriter$Job - end do split.
2021-07-08 16:03:46.331 [job-0] INFO  JobContainer - DataX Writer.Job [hdfswriter] splits to [1] tasks.
2021-07-08 16:03:46.369 [job-0] INFO  JobContainer - Scheduler starts [1] taskGroups.
2021-07-08 16:03:46.379 [taskGroup-0] INFO  TaskGroupContainer - taskGroupId=[0] start [1] channels for [1] tasks.
2021-07-08 16:03:46.388 [taskGroup-0] INFO  Channel - Channel set byte_speed_limit to -1, No bps activated.
2021-07-08 16:03:46.389 [taskGroup-0] INFO  Channel - Channel set record_speed_limit to -1, No tps activated.
2021-07-08 16:03:46.441 [0-0-0-writer] INFO  HdfsWriter$Task - write to file : [hdfs://xxxxx:8020/tmp/target/.5d06bcf4_a082_4702_ba89_31f9a8f2ea0b/sample___9f690b1d_eefe_4119_ac3f_12694f110ca8]
2021-07-08 16:03:46.442 [0-0-0-writer] INFO  HdfsHelper - write parquet file hdfs://xxxx:8020/tmp/target/.5d06bcf4_a082_4702_ba89_31f9a8f2ea0b/sample___9f690b1d_eefe_4119_ac3f_12694f110ca8
2021-07-08 16:03:47.161 [0-0-0-writer] INFO  HdfsWriter$Task - end do write
2021-07-08 16:03:49.389 [job-0] INFO  AbstractScheduler - Scheduler accomplished all tasks.
2021-07-08 16:03:49.391 [job-0] INFO  JobContainer - DataX Writer.Job [hdfswriter] do post work.
2021-07-08 16:03:49.395 [job-0] INFO  HdfsHelper - Delete all files that DO NOT start with a dot (.) in specified path
2021-07-08 16:03:49.405 [job-0] INFO  HdfsHelper - start rename file [hdfs://xxxx:8020/tmp/target/.5d06bcf4_a082_4702_ba89_31f9a8f2ea0b/sample___9f690b1d_eefe_4119_ac3f_12694f110ca8] to file [hdfs://xxxxx:8020/tmp/target/sample___9f690b1d_eefe_4119_ac3f_12694f110ca8].
2021-07-08 16:03:49.414 [job-0] INFO  HdfsHelper - finish rename file.
2021-07-08 16:03:49.415 [job-0] INFO  HdfsHelper - ONLY delete files that starts with a dot (.)
2021-07-08 16:03:49.419 [job-0] INFO  JobContainer - DataX Reader.Job [streamreader] do post work.
2021-07-08 16:03:49.423 [job-0] INFO  JobContainer - PerfTrace not enable!
2021-07-08 16:03:49.426 [job-0] INFO  StandAloneJobContainerCommunicator - Total 1000 records, 5000 bytes | Speed 1.63KB/s, 333 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.511s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2021-07-08 16:03:49.428 [job-0] INFO  JobContainer -
任务启动时刻                    : 2021-07-08 16:03:45
任务结束时刻                    : 2021-07-08 16:03:49
任务总计耗时                    :                  4s
任务平均流量                    :            1.63KB/s
记录写入速度                    :            333rec/s
读出记录总数                    :                1000
读写失败总数                    :                   0
```

**Comment by XhivaW** [comment]
> 请使用附件替换有问题的jar文件，在进行测试。
> [hdfswriter-3.2.5.jar.zip](https://github.com/wgzhao/Addax/files/6782755/hdfswriter-3.2.5.jar.zip)
> 
> 下面是本地测试情况：
> 
> ```shell
> [root@gitback 3.2.5]# bin/datax.py test.json
> 2021-07-08 16:03:45.143 [main] INFO  Engine - DataX version 3.2.5
> 2021-07-08 16:03:45.264 [main] INFO  VMInfo - VMInfo# operatingSystem class => com.sun.management.internal.OperatingSystemImpl
> 2021-07-08 16:03:45.283 [main] INFO  Engine -
> {
> 	"content":[
> 		{
> 			"reader":{
> 				"parameter":{
> 					"column":[
> 						{
> 							"type":"string",
> 							"value":"abcde"
> 						}
> 					],
> 					"sliceRecordCount":1000
> 				},
> 				"name":"streamreader"
> 			},
> 			"writer":{
> 				"parameter":{
> 					"column":[
> 						{
> 							"name":"a",
> 							"type":"string"
> 						}
> 					],
>                                   "fieldDelimiter": "\u0001", 
>                                   "fileType": "parquet", 
>                                   "compress": "NONE", 
>                                   "fileName": "sample_", 
>                                   "path": "/tmp/target", 
>                                   "defaultFS": "hdfs://xxxx:8020"
> 				},
> 				"name":"hdfswriter"
> 			}
> 		}
> 	],
> 	"setting":{
> 		"speed":{
> 			"channel":1
> 		}
> 	}
> }
> 
> 2021-07-08 16:03:45.297 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
> 2021-07-08 16:03:45.297 [main] INFO  JobContainer - DataX jobContainer starts job.
> 2021-07-08 16:03:45.298 [main] INFO  JobContainer - Set jobId = 0
> WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 2021-07-08 16:03:46.097 [job-0] INFO  JobContainer - DataX Reader.Job [streamreader] do prepare work .
> 2021-07-08 16:03:46.098 [job-0] INFO  JobContainer - DataX Writer.Job [hdfswriter] do prepare work .
> 2021-07-08 16:03:46.320 [job-0] INFO  JobContainer - Job set Channel-Number to 1 channels.
> 2021-07-08 16:03:46.321 [job-0] INFO  JobContainer - DataX Reader.Job [streamreader] splits to [1] tasks.
> 2021-07-08 16:03:46.322 [job-0] INFO  HdfsWriter$Job - begin do split...
> 2021-07-08 16:03:46.330 [job-0] INFO  HdfsWriter$Job - splited write file name:[hdfs://xxxxx:8020/tmp/target/.5d06bcf4_a082_4702_ba89_31f9a8f2ea0b/sample___9f690b1d_eefe_4119_ac3f_12694f110ca8]
> 2021-07-08 16:03:46.331 [job-0] INFO  HdfsWriter$Job - end do split.
> 2021-07-08 16:03:46.331 [job-0] INFO  JobContainer - DataX Writer.Job [hdfswriter] splits to [1] tasks.
> 2021-07-08 16:03:46.369 [job-0] INFO  JobContainer - Scheduler starts [1] taskGroups.
> 2021-07-08 16:03:46.379 [taskGroup-0] INFO  TaskGroupContainer - taskGroupId=[0] start [1] channels for [1] tasks.
> 2021-07-08 16:03:46.388 [taskGroup-0] INFO  Channel - Channel set byte_speed_limit to -1, No bps activated.
> 2021-07-08 16:03:46.389 [taskGroup-0] INFO  Channel - Channel set record_speed_limit to -1, No tps activated.
> 2021-07-08 16:03:46.441 [0-0-0-writer] INFO  HdfsWriter$Task - write to file : [hdfs://xxxxx:8020/tmp/target/.5d06bcf4_a082_4702_ba89_31f9a8f2ea0b/sample___9f690b1d_eefe_4119_ac3f_12694f110ca8]
> 2021-07-08 16:03:46.442 [0-0-0-writer] INFO  HdfsHelper - write parquet file hdfs://xxxx:8020/tmp/target/.5d06bcf4_a082_4702_ba89_31f9a8f2ea0b/sample___9f690b1d_eefe_4119_ac3f_12694f110ca8
> 2021-07-08 16:03:47.161 [0-0-0-writer] INFO  HdfsWriter$Task - end do write
> 2021-07-08 16:03:49.389 [job-0] INFO  AbstractScheduler - Scheduler accomplished all tasks.
> 2021-07-08 16:03:49.391 [job-0] INFO  JobContainer - DataX Writer.Job [hdfswriter] do post work.
> 2021-07-08 16:03:49.395 [job-0] INFO  HdfsHelper - Delete all files that DO NOT start with a dot (.) in specified path
> 2021-07-08 16:03:49.405 [job-0] INFO  HdfsHelper - start rename file [hdfs://xxxx:8020/tmp/target/.5d06bcf4_a082_4702_ba89_31f9a8f2ea0b/sample___9f690b1d_eefe_4119_ac3f_12694f110ca8] to file [hdfs://xxxxx:8020/tmp/target/sample___9f690b1d_eefe_4119_ac3f_12694f110ca8].
> 2021-07-08 16:03:49.414 [job-0] INFO  HdfsHelper - finish rename file.
> 2021-07-08 16:03:49.415 [job-0] INFO  HdfsHelper - ONLY delete files that starts with a dot (.)
> 2021-07-08 16:03:49.419 [job-0] INFO  JobContainer - DataX Reader.Job [streamreader] do post work.
> 2021-07-08 16:03:49.423 [job-0] INFO  JobContainer - PerfTrace not enable!
> 2021-07-08 16:03:49.426 [job-0] INFO  StandAloneJobContainerCommunicator - Total 1000 records, 5000 bytes | Speed 1.63KB/s, 333 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.511s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
> 2021-07-08 16:03:49.428 [job-0] INFO  JobContainer -
> 任务启动时刻                    : 2021-07-08 16:03:45
> 任务结束时刻                    : 2021-07-08 16:03:49
> 任务总计耗时                    :                  4s
> 任务平均流量                    :            1.63KB/s
> 记录写入速度                    :            333rec/s
> 读出记录总数                    :                1000
> 读写失败总数                    :                   0
> ```

谢谢回复 本地测试可以了 等下个版本发我再关闭issue哈

**Comment by XhivaW** [comment]
4.0.0版本已验证修复
