### ISSUE TITLE
rdbmreader无法识别DB2访问链接

### ISSUE THREAD

**Issue by XhivaW** [wgzhao/Addax#231]
rdbmreader无法正常识别DB2访问jdbc，原版datax可以

运行如下json时报错：

```json
{
    "job": {
        "content": [
            {
                "writer": {
                    "name": "txtfilewriter",
                    "parameter": {
                        "path": "./result",
                        "fileName": "db2_sample",
                        "writeMode": "truncate",
                        "dateFormat": "yyyy-MM-dd",
                        "compress":"gzip",
                        "fileFormat":"csv"
                    }
                },
                "reader": {
                    "parameter": {
                        "username": "AAAAAA",
                        "connection": [
                            {
                                "querySql": [
                                    "select * from table"
                                ],
                                "jdbcUrl": [
                                    "jdbc:db2://[ip]:[port]/[database]"
                                ]
                            }
                        ],
                        "password": "XXXXXX"
                    },
                    "name": "rdbmsreader"
                }
            }
        ],
        "setting": {
            "speed": {
                "channel": 4
            }
        }
    }
}
```

```text
2021-07-12 13:50:15.360 [job-0] ERROR Engine - 
Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  
- Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  - 
- 数据库连接失败. 因为根据您配置的连接信息,无法从:jdbc:db2://[ip]:[port]/[database] 中找到可连接的jdbcUrl. 
- 请检查您的配置并作出修改. - java.lang.Exception: DataX无法连接对应的数据库，可能原因是：1) 配置的ip/port/database/jdbc错误，无法连接。2) 配置的username/password错误，鉴权失败。请和DBA确认该数据库的连接信息是否正确。
        at com.wgzhao.datax.plugin.rdbms.util.DBUtil.lambda$chooseJdbcUrl$1(DBUtil.java:83)
        at com.wgzhao.datax.common.util.RetryUtil$Retry.call(RetryUtil.java:202)
        at com.wgzhao.datax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:147)
        at com.wgzhao.datax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:59)
        at com.wgzhao.datax.plugin.rdbms.util.DBUtil.chooseJdbcUrl(DBUtil.java:68)
        at com.wgzhao.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.dealJdbcAndTable(OriginalConfPretreatmentUtil.java:123)
        at com.wgzhao.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:88)
        at com.wgzhao.datax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:58)
        at com.wgzhao.datax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:75)
        at com.wgzhao.datax.plugin.reader.rdbmsreader.RdbmsReader$Job.init(RdbmsReader.java:62)
        at com.wgzhao.datax.core.job.JobContainer.initJobReader(JobContainer.java:680)
        at com.wgzhao.datax.core.job.JobContainer.init(JobContainer.java:325)
        at com.wgzhao.datax.core.job.JobContainer.start(JobContainer.java:132)
        at com.wgzhao.datax.core.Engine.start(Engine.java:107)
        at com.wgzhao.datax.core.Engine.entry(Engine.java:167)
        at com.wgzhao.datax.core.Engine.main(Engine.java:197)

```

 - OS: CentOS 7
 - JDK Version 1.8
 - Addax Version >=3.2.5

**Comment by wgzhao** [comment]
感谢反馈。

这是完整的报错的信息吗？请检查DB2的JDBC包是否存在

**Comment by XhivaW** [comment]
> 感谢反馈。
> 
> 这是完整的报错的信息吗？请检查DB2的JDBC包是否存在

是的 包括重试重复了3次

```text
2021-07-12 14:28:48.629 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2021-07-12 14:28:48.631 [job-0] ERROR Engine - Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  - Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  - 数据库连接失败. 因为根据您配置的连接信息,无法从:jdbc:db2://11.38.42.230:51000/edwdb 中找到可连接的jdbcUrl. 请检查您的配置并作出修改. - java.lang.Exception: DataX无法连接对应的数据库，可能原因是：1) 配置的ip/port/database/jdbc错误，无法连接。2) 配置的username/password错误，鉴权失败。请和DBA确认该数据库的连接信息是否正确。
        at com.wgzhao.addax.plugin.rdbms.util.DBUtil.lambda$chooseJdbcUrl$1(DBUtil.java:83)
        at com.wgzhao.addax.common.util.RetryUtil$Retry.call(RetryUtil.java:202)
        at com.wgzhao.addax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:147)
        at com.wgzhao.addax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:59)
        at com.wgzhao.addax.plugin.rdbms.util.DBUtil.chooseJdbcUrl(DBUtil.java:68)
        at com.wgzhao.addax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.dealJdbcAndTable(OriginalConfPretreatmentUtil.java:123)
        at com.wgzhao.addax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.simplifyConf(OriginalConfPretreatmentUtil.java:88)
        at com.wgzhao.addax.plugin.rdbms.reader.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:58)
        at com.wgzhao.addax.plugin.rdbms.reader.CommonRdbmsReader$Job.init(CommonRdbmsReader.java:77)
        at com.wgzhao.addax.plugin.reader.rdbmsreader.RdbmsReader$Job.init(RdbmsReader.java:62)
        at com.wgzhao.addax.core.job.JobContainer.initJobReader(JobContainer.java:680)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:325)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:132)
        at com.wgzhao.addax.core.Engine.start(Engine.java:107)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:167)
        at com.wgzhao.addax.core.Engine.main(Engine.java:197)
```

另外检查了打包后的`${ADDAX_HOME}/plugin/reader/rdbmsreader/libs/`路径 已经存在db2的JDBC包`db2jcc-db2jcc4.jar`

**Comment by XhivaW** [comment]
另外相同的任务 在原版datax下是可以正常运行的

**Comment by wgzhao** [comment]
好的，我尝试在本地复现这个问题

**Comment by wgzhao** [comment]
尝试在 `connection` 配置项里增加 `driver` 配置，类似如下：
```json
  "connection": [
      {
          "querySql": ["select * from table"],
          "jdbcUrl": ["jdbc:db2://127.0.0.1:50000/testdb"],
       "driver": "com.ibm.db2.jcc.DB2Driver"
      }
  ]
```

然后再测试看是否已经解决

**Comment by XhivaW** [comment]
> 尝试在 `connection` 配置项里增加 `driver` 配置，类似如下：
> 
> ```json
>   "connection": [
>       {
>           "querySql": ["select * from table"],
>           "jdbcUrl": ["jdbc:db2://127.0.0.1:50000/testdb"],
>        "driver": "com.ibm.db2.jcc.DB2Driver"
>       }
>   ]
> ```
> 
> 然后再测试看是否已经解决

这样可以了！ 我先关闭issue
请问这个部分以后应当手动声明 还是可以加入默认配置中？

**Comment by wgzhao** [comment]
原因是 rdbms 插件里的 `plugin.json` 文件没有明确写明 DB2 的驱动类名，可以加入默认配置中。
后面版本我会修复这个问题
