### ISSUE TITLE
mysqlreader 和 postgresqlwriter 时报No suitable driver

### ISSUE THREAD

**Issue by t291436520** [wgzhao/Addax#255]
### 在使用mysqlreader 和 postgresqlwriter 出现错误
```
16:54:45.134 [job-0] ERROR com.wgzhao.addax.common.util.RetryUtil - Exception when calling callable, 异常Msg:Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot create JDBC driver of class '' for connect URL 'jdbc:postgresql://192.168.102.118:5000/addax'
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot create JDBC driver of class '' for connect URL 'jdbc:postgresql://192.168.102.118:5000/addax'
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asConnException(RdbmsException.java:61)
	at com.wgzhao.addax.rdbms.util.DBUtil.connect(DBUtil.java:295)
	at com.wgzhao.addax.rdbms.util.DBUtil.lambda$getConnection$2(DBUtil.java:231)
	at com.wgzhao.addax.common.util.RetryUtil$Retry.call(RetryUtil.java:202)
	at com.wgzhao.addax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:147)
	at com.wgzhao.addax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:59)
	at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:231)
	at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:224)
	at com.wgzhao.addax.rdbms.util.JdbcConnectionFactory.getConnection(JdbcConnectionFactory.java:52)
	at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:145)
	at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:184)
	at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:66)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:68)
	at com.wgzhao.addax.plugin.writer.postgresqlwriter.PostgresqlWriter$Job.init(PostgresqlWriter.java:62)
	at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:710)
	at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:326)
	at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:132)
	at com.wgzhao.addax.core.Engine.start(Engine.java:79)
	at com.wgzhao.addax.core.Engine.entry(Engine.java:137)
	at EngineTests.engineMainTest(EngineTests.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```
debug 发现在 DBUtil 跳转到 DriverManager.class 中 registeredDrivers 没有postgres相关的driver 注册
但是如果reader使用streamreader 那么这种情况就不会出现上述错误

问题是在本地运行时出现，环境  jdk 1.8   编译器 idea 

mysql2postgres的配置是 

```{
  "job": {
    "content": [
      {
        "writer": {
          "name": "postgresqlwriter",
          "parameter": {
            "column": [
              "id","subid","msg"
            ],
            "connection": [
              {
                "jdbcUrl": "jdbc:postgresql://**.**.**.**:5000/addax",
                "table": [
                  "\"tmp_cdc_test\".\"autoinc\""
                ]
              }
            ],
            "username": "postgres",
            "password": "postgres",
            "writeMode": "insert"
          }
        },
        "reader": {
          "name": "mysqlreader",
          "parameter": {
            "username": "root",
            "password": "mysqlHolder",
            "splitPk": "",
            "connection": [
              {
                "jdbcUrl": [
                  "jdbc:mysql://**.**.**.**:3306"
                ],
                "querySql": [
                  "SELECT `id`,`name`,`gmt_create`,`gmt_modified`,`comment` FROM `tmp_cdc_test`.`autoinc`"
                ]
              }
            ]
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "byte": -1,
        "channel": 1
      },
      "errorLimit": {
        "record": 0,
        "percentage": 0.02
      }
    }
  }
}
```

**Comment by wgzhao** [comment]
`plugin/reader/mysqlreader/libs` 目录下有对应的jdbc驱动吗？

我尝试在本次看能否复现

**Comment by wgzhao** [comment]
如果是从 `master`  分支的话，我这边测试是没有问题的，或者你可以使用我编译的插件替换你的再测试看看

[mysqlreader-4.0.1-SNAPSHOT.zip](https://github.com/wgzhao/Addax/files/6861159/mysqlreader-4.0.1-SNAPSHOT.zip)

**Comment by t291436520** [comment]
我是直接使用的master，mysqlreader 和 postgreswriter中都是有相对应的驱动

**Comment by t291436520** [comment]
但是 报错的是 postgreswriter ， mysqlreader是正常的

**Comment by t291436520** [comment]
如果我是mysqlreader和 mysqlwriter 这样的方式时， writer是可以正常连接到数据库中,
但是如果我用两个不一样的 reader 、writer时 就会出现上面的那个问题， 我刚刚测试了一下orcale，也是同样的错误

**Comment by wgzhao** [comment]
> 如果我是mysqlreader和 mysqlwriter 这样的方式时， writer是可以正常连接到数据库中,
> 但是如果我用两个不一样的 reader 、writer时 就会出现上面的那个问题， 我刚刚测试了一下orcale，也是同样的错误

已经修复，请拉取最新代码后，重新编译 `addax-rdbms` 模块，并替换 `addax-rdbms-<version>jar` 文件，然后进行测试。

感谢反馈
