### ISSUE TITLE
nullPointerException@tdenginereader.TDengineReader$Task.startRead(TDengineReader.java:101)

### ISSUE THREAD

**Issue by zyyang-taosdata** [wgzhao/Addax#270]
**Describe the bug**
我尝试使用addax从TDengine中读取数据到streamreader，下面是日志信息。

```
2021-08-03 10:40:11.100 [main] INFO  Engine - Addax version 4.0.1
2021-08-03 10:40:11.228 [main] INFO  VMInfo - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2021-08-03 10:40:11.241 [main] INFO  Engine -
{
        "content":[
                {
                        "reader":{
                                "parameter":{
                                        "password":"*****",
                                        "connection":[
                                                {
                                                        "querySql":[
                                                                "select * from test.meters limit 10"
                                                        ],
                                                        "jdbcUrl":[
                                                                "jdbc:TAOS://127.0.0.1:6030/test"
                                                        ]
                                                }
                                        ],
                                        "username":"root"
                                },
                                "name":"tdenginereader"
                        },
                        "writer":{
                                "parameter":{
                                        "print":true
                                },
                                "name":"streamwriter"
                        }
                }
        ],
        "setting":{
                "errorLimit":{
                        "record":0,
                        "percentage":0.02
                },
                "speed":{
                        "channel":3
                }
        }
}

2021-08-03 10:40:11.254 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2021-08-03 10:40:11.254 [main] INFO  JobContainer - Addax jobContainer starts job.
2021-08-03 10:40:11.255 [main] INFO  JobContainer - Set jobId = 0
2021-08-03 10:40:11.355 [job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:TAOS://127.0.0.1:6030/test.
2021-08-03 10:40:11.359 [job-0] INFO  JobContainer - Addax Reader.Job [tdenginereader] do prepare work .
2021-08-03 10:40:11.359 [job-0] INFO  JobContainer - Addax Writer.Job [streamwriter] do prepare work .
2021-08-03 10:40:11.359 [job-0] INFO  JobContainer - Job set Channel-Number to 3 channels.
2021-08-03 10:40:11.360 [job-0] INFO  JobContainer - Addax Reader.Job [tdenginereader] splits to [1] tasks.
2021-08-03 10:40:11.361 [job-0] INFO  JobContainer - Addax Writer.Job [streamwriter] splits to [1] tasks.
2021-08-03 10:40:11.374 [job-0] INFO  JobContainer - Scheduler starts [1] taskGroups.
2021-08-03 10:40:11.378 [taskGroup-0] INFO  TaskGroupContainer - taskGroupId=[0] start [1] channels for [1] tasks.
2021-08-03 10:40:11.381 [taskGroup-0] INFO  Channel - Channel set byte_speed_limit to -1, No bps activated.
2021-08-03 10:40:11.381 [taskGroup-0] INFO  Channel - Channel set record_speed_limit to -1, No tps activated.
2021-08-03 10:40:11.389 [0-0-0-reader] ERROR ReaderRunner - Reader runner Received Exceptions:
java.lang.NullPointerException: null
        at com.wgzhao.addax.plugin.reader.tdenginereader.TDengineReader$Task.startRead(TDengineReader.java:101)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
2021-08-03 10:40:14.387 [job-0] ERROR JobContainer - 运行scheduler出错.
2021-08-03 10:40:14.388 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2021-08-03 10:40:14.388 [job-0] ERROR Engine - Code:[Framework-13], Description:[Addax 插件运行时出错, 具体原因请参看Addax 运行结束时的错误诊断信息 .].  - Code:[Framework-13], Description:[Addax 插件运行时出错, 具体原因请参看Addax 运行结束时的错误诊断信息 .].  - java.lang.NullPointerException
        at com.wgzhao.addax.plugin.reader.tdenginereader.TDengineReader$Task.startRead(TDengineReader.java:101)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
 - java.lang.NullPointerException
        at com.wgzhao.addax.plugin.reader.tdenginereader.TDengineReader$Task.startRead(TDengineReader.java:101)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
`

**Desktop (please complete the following information):**
 - OS: centos-7
 - JDK Version [1.8]
 - Addax Version [4.0.1]

**Comment by zyyang-taosdata** [comment]
在TDengineReader里添加了
`
int fetchSize = 1;
if (readerSliceConfig.getKeys().contains(Key.FETCH_SIZE)) {
    fetchSize = this.readerSliceConfig.getInt(Key.FETCH_SIZE);
}
`
可以跑了。

**Comment by wgzhao** [comment]
感谢反馈
