### ISSUE TITLE
plugin ftpreader missing org.apache.hadoop.io.compress.CompressionCodec class

### ISSUE THREAD

**Issue by milton4code** [wgzhao/Addax#292]
配置好ftpreader ,mysql writer ,执行后报错

```
2021-08-16 16:08:50 [JobThread.run-130] <br>----------- datax-web job execute start -----------<br>----------- Param:
2021-08-16 16:08:50 [ExecutorJobHandler.execute-66] ------------------DataX process id: -1
2021-08-16 16:08:50 [ProcessCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish.
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53]   ___      _     _            
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53]  / _ \    | |   | |           
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] / /_\ \ __| | __| | __ ___  __
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] |  _  |/ _` |/ _` |/ _` \ \/ /
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] | | | | (_| | (_| | (_| |>  < 
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] \_| |_/\__,_|\__,_|\__,_/_/\_\
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] :: Addax version ::    (v4.0.2)
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] [36m2021-08-16 16:08:51.663[0;39m [32m[        main][0;39m [34mINFO [0;39m [35mVMInfo              [0;39m - VMInfo# operatingSystem class => com.sun.management.internal.OperatingSystemImpl
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] [36m2021-08-16 16:08:51.689[0;39m [32m[        main][0;39m [34mINFO [0;39m [35mEngine              [0;39m - 
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] {
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 	"content":[
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 		{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 			"reader":{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 				"parameter":{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"compress":"",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"column":[
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 							"index":"0",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 							"type":"string"
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						}
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"skipHeader":false,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"encoding":"UTF-8",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"fieldDelimiter":"",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"path":"/home/ftptest/test3",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"protocol":"ftp",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"password":"*****",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"port":21,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"host":"192.168.105.27",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"csvReaderConfig":{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"captureRawRecord":true,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"safetySwitch":false,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"recordDelimiter":"\u0000",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"caseSensitive":true,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"delimiter":",",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"trimWhitespace":true,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"comment":"#",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"textQualifier":"\"",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"useTextQualifier":false,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"skipEmptyRecords":false,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"useComments":false,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"escapeMode":0
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					},
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"username":"ftptest",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"connectPattern":""
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 				},
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 				"name":"ftpreader"
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 			},
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 			"writer":{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 				"parameter":{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"password":"*****",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"column":[
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						"`data2_Column1`"
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"connection":[
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 							"jdbcUrl":"jdbc:mysql://192.168.105.5:3306/xxl_job",
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 							"table":[
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 								"test_datasys02"
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 							]
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 						}
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					],
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 					"username":"gdsunfly"
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 				},
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 				"name":"mysqlwriter"
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 			}
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 		}
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 	],
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 	"setting":{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 		"errorLimit":{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 			"record":0,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 			"percentage":0.02
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 		},
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 		"speed":{
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 			"byte":-1,
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 			"channel":3
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 		}
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 	}
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] }
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] 
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] [36m2021-08-16 16:08:51.710[0;39m [32m[        main][0;39m [34mINFO [0;39m [35mPerfTrace           [0;39m - PerfTrace traceId=job_-1, isEnable=false, priority=0
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] [36m2021-08-16 16:08:51.710[0;39m [32m[        main][0;39m [34mINFO [0;39m [35mJobContainer        [0;39m - Addax jobContainer starts job.
2021-08-16 16:08:51 [AnalysisStatistics.analysisStatisticsLog-53] [36m2021-08-16 16:08:51.712[0;39m [32m[        main][0;39m [34mINFO [0;39m [35mJobContainer        [0;39m - Set jobId = 0
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] [36m2021-08-16 16:08:52.075[0;39m [32m[       job-0][0;39m [34mINFO [0;39m [35mJobContainer        [0;39m - PerfTrace not enable!
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] ==================== DEPRECATED WARNING ========================
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] addax.py is deprecated, It's going to be removed in future release.
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] As a replacement, you can use addax.sh to run job
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] ==================== DEPRECATED WARNING ========================
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] Exception in thread "job-0" java.lang.NoClassDefFoundError: org/apache/hadoop/io/compress/CompressionCodec
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.plugin.reader.ftpreader.FtpReader$Job.init(FtpReader.java:69)
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.core.job.JobContainer.initJobReader(JobContainer.java:680)
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:325)
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:132)
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.core.Engine.start(Engine.java:79)
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.core.Engine.entry(Engine.java:137)
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.core.Engine.main(Engine.java:175)
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.io.compress.CompressionCodec
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
2021-08-16 16:08:52 [AnalysisStatistics.analysisStatisticsLog-53] 	... 7 more
2021-08-16 16:08:52 [JobThread.run-165] <br>----------- datax-web job execute end(finish) -----------<br>----------- ReturnT:ReturnT [code=500, msg=command exit value(1) is failed, content=null]
2021-08-16 16:08:52 [TriggerCallbackThread.callbackLog-186] <br>----------- datax-web job callback finish.
```

**Comment by wgzhao** [comment]
`4.0.2` 版本应该把hadoop相关的压缩算法和普通压缩算法隔离开了。

您可以使用下面的临时解决办法：

1. 如果您的 `Addax` 目录含有 `shared` 文件夹，则执行下面的命令

```shell
cd plugin/reader/ftpreader/libs
ln -sf ../../../../shared/hadoop-common-3.1.0.jar .
```
2. 如果没有 `shared` 文件夹， 则执行下面的命令：
`cp plugin/reader/hbase20xreader/libs/hadoop-common-3.1.0.jar plugin/reader/ftpreader/libs`

然后再测试
