### ISSUE TITLE
greenplum writer

### ISSUE THREAD

**Issue by cxin-william** [wgzhao/Addax#322]
我在写入greenplum时报的错误，希望能帮忙看下，┭┮﹏┭┮

```
ERROR WriterRunner         - Writer Runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.lang.ClassCastException: org.apache.commons.dbcp2.PoolingDataSource$PoolGuardConnectionWrapper cannot be cast to org.postgresql.core.BaseConnection
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:117)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
 - java.lang.ClassCastException: org.apache.commons.dbcp2.PoolingDataSource$PoolGuardConnectionWrapper cannot be cast to org.postgresql.core.BaseConnection
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:117)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWriterTask.startWrite(CopyWriterTask.java:174)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.GreenplumWriter$Task.startWrite(GreenplumWriter.java:103)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: org.apache.commons.dbcp2.PoolingDataSource$PoolGuardConnectionWrapper cannot be cast to org.postgresql.core.BaseConnection
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:117)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 common frames omitted
```

**Comment by wgzhao** [comment]
Addax 哪个版本？能否给出完整的输出日志信息，这对快速定位问题有帮助

**Comment by cxin-william** [comment]
4.0.2版本
2021-08-30 19:30:47.000 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2021-08-30 19:30:47.022 [        main] INFO  Engine               - 
{
        "content":[
                {
                        "reader":{
                                "parameter":{
                                        "password":"*****",
                                        "connection":[
                                                {
                                                        "querySql":[
                                                                "select uuid,filler,fildate,lastmodifyoper,lstupdtime,promotionid,promotionname,promotionamount,favamountchannel,favamountmerchant,favamountothers,productid,productquantity,productprice,productfavouramount,oca,tenantid,orderuuid,promotiontype,promotionmemo,pcsAmountBuyer,pcsAmountMerchant,pcsAmountChannel,promotionactivityid,promotionscope,productmemo,productfavamountmerchant,productfavamountchannel,productfavamountothers,source, 'pay_hnhg' etl_db_source from pay_hnhg.cppayorderpromotion"
                                                        ],
                                                        "jdbcUrl":[
                                                                "jdbc:mysql://rr-bp13o679358ng5f82zo.mysql.rds.aliyuncs.com:3306/mysql?allowLoadLocalInfile=false&autoDeserialize=false&allowLocalInfile=false&allowUrlInLocalInfile=false"
                                                        ]
                                                }
                                        ],
                                        "username":"dic"
                                },
                                "name":"mysqlreader"
                        },
                        "writer":{
                                "parameter":{
                                        "password":"*****",
                                        "queueSize":5,
                                        "numProc":2,
                                        "column":[
                                                "\"uuid\"",
                                                "\"filler\"",
                                                "\"fildate\"",
                                                "\"lastmodifyoper\"",
                                                "\"lstupdtime\"",
                                                "\"promotionid\"",
                                                "\"promotionname\"",
                                                "\"promotionamount\"",
                                                "\"favamountchannel\"",
                                                "\"favamountmerchant\"",
                                                "\"favamountothers\"",
                                                "\"productid\"",
                                                "\"productquantity\"",
                                                "\"productprice\"",
                                                "\"productfavouramount\"",
                                                "\"oca\"",
                                                "\"tenantid\"",
                                                "\"orderuuid\"",
                                                "\"promotiontype\"",
                                                "\"promotionmemo\"",
                                                "\"pcsAmountBuyer\"",
                                                "\"pcsAmountMerchant\"",
                                                "\"pcsAmountChannel\"",
                                                "\"promotionactivityid\"",
                                                "\"promotionscope\"",
                                                "\"productmemo\"",
                                                "\"productfavamountmerchant\"",
                                                "\"productfavamountchannel\"",
                                                "\"productfavamountothers\"",
                                                "\"source\"",
                                                "\"etl_db_source\""
                                        ],
                                        "connection":[
                                                {
                                                        "jdbcUrl":"jdbc:postgresql://172.17.9.200:5432/GPDB",
                                                        "table":[
                                                                "ods_pay.cppayorderpromotion"
                                                        ]
                                                }
                                        ],
                                        "numWriter":1,
                                        "username":"dic_etl"
                                },
                                "name":"greenplumwriter"
                        }
                }
        ],
        "setting":{
                "speed":{
                        "bytes":-1,
                        "channel":1
                }
        }
}

2021-08-30 19:30:47.038 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2021-08-30 19:30:47.039 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2021-08-30 19:30:47.040 [        main] INFO  JobContainer         - Set jobId = 0
2021-08-30 19:30:47.434 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:mysql://rr-bp13o679358ng5f82zo.mysql.rds.aliyuncs.com:3306/mysql?allowLoadLocalInfile=false&autoDeserialize=false&allowLocalInfile=false&allowUrlInLocalInfile=false&yearIsDateType=false&zeroDateTimeBehavior=CONVERT_TO_NULL&tinyInt1isBit=false&rewriteBatchedStatements=true&useSSL=false.
2021-08-30 19:30:47.760 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[ods_pay.cppayorderpromotion] all columns:[uuid,filler,fildate,lastmodifyoper,lstupdtime,promotionid,promotionname,promotionamount,favamountchannel,favamountmerchant,favamountothers,productid,productquantity,productprice,productfavouramount,oca,tenantid,orderuuid,promotiontype,promotionmemo,pcsAmountBuyer,pcsAmountMerchant,pcsAmountChannel,promotionactivityid,promotionscope,productmemo,productfavamountmerchant,productfavamountchannel,productfavamountothers,source,etl_db_source,etl_create_time,etl_update_time,etl_is_delete].
2021-08-30 19:30:47.938 [       job-0] INFO  OriginalConfPretreatmentUtil - Write data [INSERT INTO %s ("uuid","filler","fildate","lastmodifyoper","lstupdtime","promotionid","promotionname","promotionamount","favamountchannel","favamountmerchant","favamountothers","productid","productquantity","productprice","productfavouramount","oca","tenantid","orderuuid","promotiontype","promotionmemo","pcsAmountBuyer","pcsAmountMerchant","pcsAmountChannel","promotionactivityid","promotionscope","productmemo","productfavamountmerchant","productfavamountchannel","productfavamountothers","source","etl_db_source") VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)], which jdbcUrl [jdbc:postgresql://172.17.9.200:5432/GPDB]
2021-08-30 19:30:47.939 [       job-0] INFO  JobContainer         - Addax Reader.Job [mysqlreader] do prepare work .
2021-08-30 19:30:47.939 [       job-0] INFO  JobContainer         - Addax Writer.Job [greenplumwriter] do prepare work .
2021-08-30 19:30:47.939 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channels.
2021-08-30 19:30:47.941 [       job-0] INFO  JobContainer         - Addax Reader.Job [mysqlreader] splits to [1] tasks.
2021-08-30 19:30:47.941 [       job-0] INFO  JobContainer         - Addax Writer.Job [greenplumwriter] splits to [1] tasks.
2021-08-30 19:30:47.958 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2021-08-30 19:30:47.971 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2021-08-30 19:30:47.976 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2021-08-30 19:30:47.976 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2021-08-30 19:30:47.988 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select uuid,filler,fildate,lastmodifyoper,lstupdtime,promotionid,promotionname,promotionamount,favamountchannel,favamountmerchant,favamountothers,productid,productquantity,productprice,productfavouramount,oca,tenantid,orderuuid,promotiontype,promotionmemo,pcsAmountBuyer,pcsAmountMerchant,pcsAmountChannel,promotionactivityid,promotionscope,productmemo,productfavamountmerchant,productfavamountchannel,productfavamountothers,source, 'pay_hnhg' etl_db_source from pay_hnhg.cppayorderpromotion
] jdbcUrl:[jdbc:mysql://rr-bp13o679358ng5f82zo.mysql.rds.aliyuncs.com:3306/mysql?allowLoadLocalInfile=false&autoDeserialize=false&allowLocalInfile=false&allowUrlInLocalInfile=false&yearIsDateType=false&zeroDateTimeBehavior=CONVERT_TO_NULL&tinyInt1isBit=false&rewriteBatchedStatements=true&useSSL=false].
2021-08-30 19:30:48.547 [0-0-0-writer] INFO  CopyWorker           - copy sql: COPY ods_pay.cppayorderpromotion("uuid","filler","fildate","lastmodifyoper","lstupdtime","promotionid","promotionname","promotionamount","favamountchannel","favamountmerchant","favamountothers","productid","productquantity","productprice","productfavouramount","oca","tenantid","orderuuid","promotiontype","promotionmemo","pcsAmountBuyer","pcsAmountMerchant","pcsAmountChannel","promotionactivityid","promotionscope","productmemo","productfavamountmerchant","productfavamountchannel","productfavamountothers","source","etl_db_source") FROM STDIN WITH DELIMITER '' NULL '' CSV QUOTE '' ESCAPE E'\\';
2021-08-30 19:30:48.551 [0-0-0-writer] WARN  CopyWorker           - Cannot set gp_max_csv_line_length to 4194304
2021-08-30 19:30:48.621 [0-0-0-writer] ERROR WriterRunner         - Writer Runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.lang.ClassCastException: org.apache.commons.dbcp2.PoolingDataSource$PoolGuardConnectionWrapper cannot be cast to org.postgresql.core.BaseConnection
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:117)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
 - java.lang.ClassCastException: org.apache.commons.dbcp2.PoolingDataSource$PoolGuardConnectionWrapper cannot be cast to org.postgresql.core.BaseConnection
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:117)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWriterTask.startWrite(CopyWriterTask.java:174)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.GreenplumWriter$Task.startWrite(GreenplumWriter.java:103)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: org.apache.commons.dbcp2.PoolingDataSource$PoolGuardConnectionWrapper cannot be cast to org.postgresql.core.BaseConnection
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:117)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 common frames omitted
2021-08-30 19:30:50.975 [       job-0] ERROR JobContainer         - 运行scheduler出错.
2021-08-30 19:30:50.976 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 544 records, 126045 bytes | Speed 123.09KB/s, 544 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.297s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2021-08-30 19:30:50.976 [       job-0] ERROR Engine               - Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.lang.ClassCastException: org.apache.commons.dbcp2.PoolingDataSource$PoolGuardConnectionWrapper cannot be cast to org.postgresql.core.BaseConnection
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:117)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
 - java.lang.ClassCastException: org.apache.commons.dbcp2.PoolingDataSource$PoolGuardConnectionWrapper cannot be cast to org.postgresql.core.BaseConnection
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:117)
        at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWorker.call(CopyWorker.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by wgzhao** [comment]
已修复，在本地测试通过， 测试版本为 `postgres (Greenplum Database) 4.3.7.1 build` ，容易运行模式，容器来源为 <https://hub.docker.com/r/datagrip/greenplum>

下载附件并解压后，替代对应的jar包即可。

[greenplumwriter-4.0.4-SNAPSHOT.jar.zip](https://github.com/wgzhao/Addax/files/7081618/greenplumwriter-4.0.4-SNAPSHOT.jar.zip)

**Comment by cxin-william** [comment]
非常感谢，亲测有效，速率好像在800rec/s左右，还挺慢的，然后测了下4.0.3版本报错
==================== DEPRECATED WARNING ========================
addax.py is deprecated, It's going to be removed in future release.
As a replacement, you can use addax.sh to run job
==================== DEPRECATED WARNING ========================

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/soft/addax-4.0.3/lib/logback-classic-1.2.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/soft/addax-4.0.3/lib/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

  ___      _     _            
 / _ \    | |   | |           
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  < 
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.3)

2021-08-31 17:54:00.235 [main] INFO  VMInfo - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2021-08-31 17:54:00.256 [main] INFO  Engine - 
{
        "content":[
                {
                        "reader":{
                                "parameter":{
                                        "password":"*****",
                                        "connection":[
                                                {
                                                        "querySql":[
                                                                "select uuid,filler,fildate,lastmodifyoper,lstupdtime,promotionid,promotionname,promotionamount,favamountchannel,favamountmerchant,favamountothers,productid,productquantity,productprice,productfavouramount,oca,tenantid,orderuuid,promotiontype,promotionmemo,pcsAmountBuyer,pcsAmountMerchant,pcsAmountChannel,promotionactivityid,promotionscope,productmemo,productfavamountmerchant,productfavamountchannel,productfavamountothers,source, 'pay_hnhg' etl_db_source from pay_hnhg.cppayorderpromotion"
                                                        ],
                                                        "jdbcUrl":[
                                                                "jdbc:mysql://rr-bp13o679358ng5f82zo.mysql.rds.aliyuncs.com:3306/mysql?allowLoadLocalInfile=false&autoDeserialize=false&allowLocalInfile=false&allowUrlInLocalInfile=false"
                                                        ]
                                                }
                                        ],
                                        "username":"dic"
                                },
                                "name":"mysqlreader"
                        },
                        "writer":{
                                "parameter":{
                                        "password":"*****",
                                        "queueSize":5,
                                        "numProc":2,
                                        "column":[
                                                "\"uuid\"",
                                                "\"filler\"",
                                                "\"fildate\"",
                                                "\"lastmodifyoper\"",
                                                "\"lstupdtime\"",
                                                "\"promotionid\"",
                                                "\"promotionname\"",
                                                "\"promotionamount\"",
                                                "\"favamountchannel\"",
                                                "\"favamountmerchant\"",
                                                "\"favamountothers\"",
                                                "\"productid\"",
                                                "\"productquantity\"",
                                                "\"productprice\"",
                                                "\"productfavouramount\"",
                                                "\"oca\"",
                                                "\"tenantid\"",
                                                "\"orderuuid\"",
                                                "\"promotiontype\"",
                                                "\"promotionmemo\"",
                                                "\"pcsAmountBuyer\"",
                                                "\"pcsAmountMerchant\"",
                                                "\"pcsAmountChannel\"",
                                                "\"promotionactivityid\"",
                                                "\"promotionscope\"",
                                                "\"productmemo\"",
                                                "\"productfavamountmerchant\"",
                                                "\"productfavamountchannel\"",
                                                "\"productfavamountothers\"",
                                                "\"source\"",
                                                "\"etl_db_source\""
                                        ],
                                        "connection":[
                                                {
                                                        "jdbcUrl":"jdbc:postgresql://172.17.9.200:5432/GPDB",
                                                        "table":[
                                                                "ods_pay.cppayorderpromotion"
                                                        ]
                                                }
                                        ],
                                        "numWriter":1,
                                        "username":"dic_etl"
                                },
                                "name":"greenplumwriter"
                        }
                }
        ],
        "setting":{
                "speed":{
                        "bytes":-1,
                        "channel":1
                }
        }
}

2021-08-31 17:54:00.272 [main] INFO  PerfTrace - PerfTrace traceId=job_-1, isEnable=false, priority=0
2021-08-31 17:54:00.272 [main] INFO  JobContainer - Addax jobContainer starts job.
2021-08-31 17:54:00.274 [main] INFO  JobContainer - Set jobId = 0
2021-08-31 17:54:00.288 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2021-08-31 17:54:00.289 [job-0] ERROR Engine - Code:[Framework-02], Description:[Addax 引擎运行过程出错，具体原因请参看Addax 运行结束时的错误诊断信息  .].  - Code:[Framework-02], Description:[Addax 引擎运行过程出错，具体原因请参看Addax 运行结束时的错误诊断信息  .].  - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.wgzhao.addax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:181)
        at com.wgzhao.addax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:111)
        at com.wgzhao.addax.core.job.JobContainer.initJobReader(JobContainer.java:668)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:325)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:132)
        at com.wgzhao.addax.core.Engine.start(Engine.java:79)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:137)
        at com.wgzhao.addax.core.Engine.main(Engine.java:175)
 - java.lang.ClassNotFoundException: com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader$Job
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.wgzhao.addax.core.util.container.LoadUtil.loadPluginClass(LoadUtil.java:181)
        at com.wgzhao.addax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:111)
        at com.wgzhao.addax.core.job.JobContainer.initJobReader(JobContainer.java:668)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:325)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:132)
        at com.wgzhao.addax.core.Engine.start(Engine.java:79)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:137)
        at com.wgzhao.addax.core.Engine.main(Engine.java:175)

非常感谢回复，希望越来越好，感恩❤

**Comment by wgzhao** [comment]
1. 在我本地测试也是这个效率，后续再看看是哪里的问题
2. 从报错来看 `com.alibaba.datax.plugin.reader.mysqlreader.MysqlReader` 这个类不应该出现在我的这个项目里，您是和 [datax](https://github.com/alibaba/datax) 项目混用了吗？

**Comment by cxin-william** [comment]
1.非常感谢大佬耐心的解答，十分期待优化，现在这效率属实有点用不动🤭
2.4.0.3就是原封不动的下载的没改，不过先不纠结那个了，4.0.2版本可用，把效率能提升上去就完美了！！！

**Comment by wgzhao** [comment]
尝试下面的这个版本看看，在我本地测试的话，写入性能提升了4倍，不过这还不是一个完善的版本。仅当测试使用。

[greenplumwriter-4.0.4-SNAPSHOT.jar.zip](https://github.com/wgzhao/Addax/files/7084119/greenplumwriter-4.0.4-SNAPSHOT.jar.zip)

**Comment by cxin-william** [comment]
厉害了，大佬！膜拜👏👏👏
