### ISSUE TITLE
关于job里面放多个sql的报错

### ISSUE THREAD

**Issue by cxin-william** [wgzhao/Addax#342]
大佬你好，我在一个job中放了多个sql的时候，发现报错了，可能与greenplumwriter是copy的方式有关
```
{
"content":[
{
"reader":{
	"parameter":{
		"password":"******",
		"connection":[
			{
				"querySql":[
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_199qqg' etl_db_source from pay_199qqg.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_bn01' etl_db_source from pay_bn01.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_cgj' etl_db_source from pay_cgj.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_cs01' etl_db_source from pay_cs01.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_dxss' etl_db_source from pay_dxss.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_fftest' etl_db_source from pay_fftest.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_fst' etl_db_source from pay_fst.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_gyht' etl_db_source from pay_gyht.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_gzjf' etl_db_source from pay_gzjf.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_haoxiangqin' etl_db_source from pay_haoxiangqin.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_hd' etl_db_source from pay_hd.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_hddpostest' etl_db_source from pay_hddpostest.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_hdfuture' etl_db_source from pay_hdfuture.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_hnhg' etl_db_source from pay_hnhg.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_hnysd' etl_db_source from pay_hnysd.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_hqyg' etl_db_source from pay_hqyg.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_hzxy' etl_db_source from pay_hzxy.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_jmqk' etl_db_source from pay_jmqk.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_linyifuhui' etl_db_source from pay_linyifuhui.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_lsw' etl_db_source from pay_lsw.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_maidelong' etl_db_source from pay_maidelong.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_nbxjx' etl_db_source from pay_nbxjx.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_nbxjxsc' etl_db_source from pay_nbxjxsc.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_njdg' etl_db_source from pay_njdg.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_nmqw' etl_db_source from pay_nmqw.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_ptwx' etl_db_source from pay_ptwx.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_rh' etl_db_source from pay_rh.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_sdam' etl_db_source from pay_sdam.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_sdbzm' etl_db_source from pay_sdbzm.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_sgsl' etl_db_source from pay_sgsl.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_syjj' etl_db_source from pay_syjj.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_szyk' etl_db_source from pay_szyk.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_szyzd' etl_db_source from pay_szyzd.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_tianyuan' etl_db_source from pay_tianyuan.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_tick' etl_db_source from pay_tick.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_tjwqwnd' etl_db_source from pay_tjwqwnd.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_twyj' etl_db_source from pay_twyj.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_tzhl' etl_db_source from pay_tzhl.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_wzsh' etl_db_source from pay_wzsh.cppaydrpt where lstupdtime>='2021-09-01'",
"select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,'pay_rds1' etl_db_instance, 'pay_wzsm' etl_db_source from pay_wzsm.cppaydrpt where lstupdtime>='2021-09-01'"
								],
								"jdbcUrl":[
									"jdbc:mysql://rr-bp13o679358ng5f82zo.mysql.rds.aliyuncs.com:3306/mysql"
								]
							}
						],
						"username":"dic"
					},
					"name":"mysqlreader"
				},
				"writer":{
					"parameter":{
						"postSql":[
							"delete from ods_pay.cppaydrpt a where exists (select uuid,etl_db_instance,etl_db_source from @table b where a.uuid =b.uuid and a.etl_db_instance =b.etl_db_instance and a.etl_db_source =b.etl_db_source)",
							"insert into ods_pay.cppaydrpt select * from @table"
						],
						"password":"******",
						"queueSize":10000,
						"column":[
							"\"uuid\"",
							"\"filler\"",
							"\"fildate\"",
							"\"lastmodifyoper\"",
							"\"lstupdtime\"",
							"\"oca\"",
							"\"seqUuid\"",
							"\"tenantid\"",
							"\"paytime\"",
							"\"paychannel\"",
							"\"paycount\"",
							"\"amount\"",
							"\"payamount\"",
							"\"favouramount\"",
							"\"refundcount\"",
							"\"refundamount\"",
							"\"cancelcount\"",
							"\"cancelamount\"",
							"\"etl_db_instance\"",
							"\"etl_db_source\""
						],
						"connection":[
							{
								"jdbcUrl":"jdbc:postgresql://172.17.9.200:5432/GPDB",
								"table":[
									"ods_pay.tmp_cppaydrpt"
								]
							}
						],
						"username":"dic_etl",
						"preSql":[
							"truncate table @table"
						]
					},
					"name":"greenplumwriter"
				}
			}
		],
		"setting":{
			"speed":{
				"bytes":-1,
				"channel":10
			}
		}
	}
`


`[36m2021-09-08 10:10:33.029[0;39m [32m[0-1-25-writer][0;39m [1;31mERROR[0;39m [35mRetryUtil           [0;39m - Exception when calling callable, 异常Msg:Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: remaining connection slots are reserved for non-replication superuser connections)
        com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: remaining connection slots are reserved for non-replication superuser connections)
                at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
                at com.wgzhao.addax.rdbms.util.RdbmsException.asConnException(RdbmsException.java:61)
                at com.wgzhao.addax.rdbms.util.DBUtil.connect(DBUtil.java:295)
                at com.wgzhao.addax.rdbms.util.DBUtil.lambda$getConnection$2(DBUtil.java:230)
                at com.wgzhao.addax.common.util.RetryUtil$Retry.call(RetryUtil.java:202)
                at com.wgzhao.addax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:147)
                at com.wgzhao.addax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:59)
                at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:230)
                at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:223)
                at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWriterTask.createConnection(CopyWriterTask.java:73)
                at com.wgzhao.addax.plugin.writer.greenplumwriter.CopyWriterTask.startWrite(CopyWriterTask.java:143)
                at com.wgzhao.addax.plugin.writer.greenplumwriter.GreenplumWriter$Task.startWrite(GreenplumWriter.java:103)
                at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
                at java.lang.Thread.run(Thread.java:748)
```

**Comment by wgzhao** [comment]
多个SQL，特别是每个SQL都有输出的场景， 这种方式在我的理解是不支持的，从上述配置的SQL来看，你是大量类似的SQL 查询，只是因为查询源不同，所以需要一个字段识别，这种场景在我实际工作中是一直在运行的，不过方式是将多个SQL用 `union all ` 方式拼接成一个SQL。类似如下

```sql
select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,
amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,
'pay_rds1' etl_db_instance, 'pay_199qqg' etl_db_source 
from pay_199qqg.cppaydrpt where lstupdtime>='2021-09-01'
union all
select uuid,filler,fildate,lastmodifyoper,lstupdtime,oca,seqUuid,tenantid,paytime,paychannel,paycount,
amount,payamount,favouramount,refundcount,refundamount,cancelcount,cancelamount,
'pay_rds1' etl_db_instance, 'pay_bn01' etl_db_source f
rom pay_bn01.cppaydrpt where lstupdtime>='2021-09-01'
union all
...
```

**Comment by cxin-william** [comment]
首先非常感谢大佬的耐心回答！~~
多个SQL也是支持的，我试过把量放小点是成功的，量多了之后，addax生成了很多数据库连接，如果可以对那么多sql进行一个线程的控制，估计可以达到效果。由于那台机器性能不太行，不敢用你上面说的union all的方式，怕出问题😆。
