### ISSUE TITLE
使用ftpreader同时开启compress时报IO异常

### ISSUE THREAD

**Issue by heady713** [wgzhao/Addax#381]
job.json如下
`{
  "job": {
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": -1
      }
    },
    "content": [
      {
        "reader": {
            "name": "ftpreader",
            "parameter": {
                "protocol": "ftp",
                "host": "192.168.1.1",
                "port": 21,
                "username": "ftp",
                "password": "ftpp",
                "path": [
                  "/"
                ],
                "skipHeader": true,
                "column": [
                    "*"
                ],
            "encoding": "UTF-8",
            "compress": "zip",
            "fieldDelimiter": ","
          }
        },
        "writer": {
          "name": "txtfilewriter",
          "parameter": {
            "path": "/writer_test",
            "fileName": "hello",
            "writeMode": "truncate",
            "dateFormat": "yyyy-MM-dd"
          }
        }
      }
    ]
  }
}`

错误信息如下：

`
2021-10-02 12:51:55.505 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 9824 records, 1108966 bytes | Speed 90.25KB/s, 818 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.007s |  All Task WaitReaderTime 0.402s | Percentage 0.00%
2021-10-02 12:51:55.506 [       job-0] ERROR JobContainer         - 运行scheduler出错.
2021-10-02 12:51:55.507 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 9824 records, 1108966 bytes | Speed 1.06MB/s, 9824 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.007s |  All Task WaitReaderTime 0.402s | Percentage 0.00%
2021-10-02 12:51:55.510 [       job-0] ERROR Engine               - Code:[StorageReader-09], Description:[您配置的文件在读取时出现IO异常.]. - Code:[StorageReader-09], Description:[您配置的文件在读取时出现IO异常.]. - Read file '/test1.csv.zip' failure  - java.io.IOException: Push back buffer is full
        at java.io.PushbackInputStream.unread(PushbackInputStream.java:232)
        at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:345)
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:122)
        at com.wgzhao.addax.common.compress.ZipCycleInputStream.read(ZipCycleInputStream.java:58)
        at java.io.InputStream.read(InputStream.java:170)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.read1(BufferedReader.java:212)
        at java.io.BufferedReader.read(BufferedReader.java:286)
        at com.csvreader.CsvReader.checkDataLength(Unknown Source)
        at com.csvreader.CsvReader.readRecord(Unknown Source)
        at com.wgzhao.addax.storage.reader.StorageReaderUtil.splitBufferedReader(StorageReaderUtil.java:83)
        at com.wgzhao.addax.storage.reader.StorageReaderUtil.doReadFromStream(StorageReaderUtil.java:202)
        at com.wgzhao.addax.storage.reader.StorageReaderUtil.readFromStream(StorageReaderUtil.java:136)
        at com.wgzhao.addax.plugin.reader.ftpreader.FtpReader$Task.startRead(FtpReader.java:280)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
`

ftpreader不使用compress时无报错，使用textreader加gzip压缩无报错。

**Comment by heady713** [comment]
使用环境：

**Comment by heady713** [comment]
操作系统：MacOS 10.15.7
FTP环境：docker  bogem/ftp

尝试过几个小文件未出现问题，但是文件大了之后（似乎是超过2200行）就会出错。输出的文件内容中先是出现乱序，乱序后超过一定的大小才会报上述IO错误。如下图：
![image](https://user-images.githubusercontent.com/3283912/136484605-da200ec2-2111-441a-b5e3-e2c4e6769cd3.png)

另外，在linux服务器上使用addax-4.0.3，也是同样的错误。

**Comment by wgzhao** [comment]
好的，我测试大文件看看

**Comment by heady713** [comment]
[test1.csv.zip](https://github.com/wgzhao/Addax/files/7308897/test1.csv.zip)



> 好的，我测试大文件看看，为了更准备模拟的情况，你可以把截图中的zip文件直接传上来，我看看文件内容是不是有特殊字符之类的情况

出错的文件：
[test1.csv.zip](https://github.com/wgzhao/Addax/files/7308897/test1.csv.zip)

成功的文件：
[test5.csv.gz](https://github.com/wgzhao/Addax/files/7308907/test5.csv.gz)

**Comment by wgzhao** [comment]
刚才我本地测试一个10000行的csv文件，暂未发现问题

```shell
2021-10-08 14:02:40.540 [       job-0] INFO  JobContainer         -
任务启动时刻                    : 2021-10-08 14:02:37
任务结束时刻                    : 2021-10-08 14:02:40
任务总计耗时                    :                  3s
任务平均流量                    :          232.54KB/s
记录写入速度                    :           3333rec/s
读出记录总数                    :               10000
读写失败总数                    :                   0
````

现在测试你发过来的文件

**Comment by heady713** [comment]
> 重现了你说的情况，解压读取没有问题，猜测是自己实现的zip文件读取类有问题，我排查下。

好的，另外我使用gzip压缩也是同样情况，之前看过代码没看出什么端倪。

**Comment by wgzhao** [comment]
zip文件的压缩比较奇葩，你尝试用命令行的zip命令试试

```shell
zip -r test.csv.zip test.csv
```

**Comment by heady713** [comment]
> zip文件的压缩比较奇葩，你尝试用命令行的zip命令试试
> 
> ```shell
> zip -r test.csv.zip test.csv
> ```

已尝试，应该是压缩工具的问题。
