### ISSUE TITLE
[Bug]: 使用hdfsReader读取parquet文件时报错

### ISSUE THREAD

**Issue by a19920714liou** [wgzhao/Addax#392]
### What happened?

读取hdfs文件时报错。
{
    "job": {
      "setting": {
        "speed": {
          "channel": 2
        }
      },
      "content": [
        {
            "writer": {
                "name": "streamwriter",
                "parameter": {
                  "print": true
                }
              },
          "reader": {
            "name": "hdfsreader",
            "parameter": {
                "defaultFS": "hdfs://nameservice1",
                "fileType":"parquet",
                "path": "/user/hive/warehouse/zx_ta14327/ZX_TA14327-1.parquet",
                "column":[
                    {
                        "index":0,
                        "type":"STRING"
                    },
                    {
                        "index":1,
                        "type":"STRING"
                    },
                    {
                        "index":2,
                        "type":"STRING"
                    },
                    {
                        "index":3,
                        "type":"STRING"
                    },
                    {
                        "index":4,
                        "type":"STRING"
                    },
                    {
                        "index":5,
                        "type":"STRING"
                    },
                    {
                        "index":6,
                        "type":"STRING"
                    },
                    {
                        "index":7,
                        "type":"STRING"
                    },
                    {
                        "index":7,
                        "type":"STRING"
                    }
                ],
                "compress":"NONE",
                "fieldDelimiter": ",",
                "haveKerberos":"true",
                "kerberosKeytabFilePath":"/etc/security/keytabs/hdfs.keytab",
                "kerberosPrincipal":"hdfs/bigwork05@HADOOP.COM"
            }
        }
        }
      ]
    }
  }

### Version

4.0.4 (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell
2021-10-14 15:13:45.162 [0-0-0-reader] ERROR ReaderRunner         - Reader runner Received Exceptions:
java.lang.NoSuchMethodError: org.apache.parquet.format.Util.readFileMetaData(Ljava/io/InputStream;Lorg/apache/parquet/format/BlockCipher$Decryptor;[B)Lorg/apache/parquet/format/FileMetaData;
        at org.apache.parquet.format.converter.ParquetMetadataConverter$3.visit(ParquetMetadataConverter.java:1333)
        at org.apache.parquet.format.converter.ParquetMetadataConverter$3.visit(ParquetMetadataConverter.java:1330)
        at org.apache.parquet.format.converter.ParquetMetadataConverter$NoFilter.accept(ParquetMetadataConverter.java:1155)
        at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:1330)
        at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:582)
        at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:776)
        at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:657)
        at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:152)
        at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
        at com.wgzhao.addax.plugin.reader.hdfsreader.DFSUtil.parquetFileStartRead(DFSUtil.java:475)
        at com.wgzhao.addax.plugin.reader.hdfsreader.HdfsReader$Task.startRead(HdfsReader.java:303)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by wgzhao** [comment]
本地测试没有重现该问题，麻烦列出 `plugin/reader/hdfsreader/libs` 的软件包

**Comment by a19920714liou** [comment]
哦，这个可以了。。之前parquet-avro版本是1.12.0就不行，改成1.12.2就可以了
