### ISSUE TITLE
[Bug]: getValidColumnIndex Exception occurred when use oraclewriter plugin 

### ISSUE THREAD

**Issue by rogerlzp** [wgzhao/Addax#404]
### What happened?

in addax-4.0.5, it throws the error:

```shell
 脏数据: {"exception":"无效的列索引: getValidColumnIndex",
"record":[{"byteSize":6,"rawData":"999703","type":"STRING"},{"byteSize":10,"rawData":"B001999703","type":"STRING"},{"byteSize":2,"rawData":"01","type":"STRING"},{"byteSize":4,"rawData":"JY00","type":"STRING"},{"byteSize":6,"rawData":"002493","type":"STRING"},{"byteSize":6,"rawData":"298900","type":"STRING"},{"byteSize":6,"rawData":"223500","type":"STRING"},{"byteSize":10,"rawData":"0899041889","type":"STRING"},{"byteSize":10,"rawData":"0000000005","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":16,"rawData":"0101000000011680","type":"STRING"},
{"byteSize":16,"rawData":"2110161000027652","type":"STRING"},{"byteSize":6,"rawData":"100.00","type":"DOUBLE"},{"byteSize":6,"rawData":"100.00","type":"DOUBLE"},{"byteSize":7,"rawData":"17.2400","type":"DOUBLE"},{"byteSize":12,"rawData":"17.240000000","type":"DOUBLE"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":2,"rawData":"00","type":"STRING"},
{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":2,"rawData":"00","type":"STRING"},{"byteSize":1,"rawData":"A","type":"STRING"},{"byteSize":3,"rawData":"RMB","type":"STRING"},
{"byteSize":8,"rawData":"-1724.00","type":"DOUBLE"},{"byteSize":4,"rawData":"0.00","type":"DOUBLE"},{"byteSize":5,"rawData":"-0.08","type":"DOUBLE"},{"byteSize":5,"rawData":"-0.03","type":"DOUBLE"},{"byteSize":5,"rawData":"-0.03","type":"DOUBLE"},{"byteSize":4,"rawData":"0.00","type":"DOUBLE"},{"byteSize":4,"rawData":"0.00","type":"DOUBLE"},{"byteSize":4,"rawData":"0.00","type":"DOUBLE"},
{"byteSize":4,"rawData":"0.00","type":"DOUBLE"},{"byteSize":4,"rawData":"0.00","type":"DOUBLE"},{"byteSize":8,"rawData":"-1724.14","type":"DOUBLE"},{"byteSize":8,"rawData":"20211016","type":"STRING"},{"byteSize":8,"rawData":"20211016","type":"STRING"},{"byteSize":8,"rawData":"20211017","type":"STRING"},{"byteSize":8,"rawData":"20211016","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":2,"rawData":"01","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"}],"type":"writer"}%n
```

but it worked in addax-4.0.2;
There should be something wrong with oraclewriter in addax-4.0.5.

### Version

4.0.4 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
请给出详细的输出结果

**Comment by czxin788** [comment]
我也报这个错误
Oct 21, 2021 9:05:11 PM com.microsoft.sqlserver.jdbc.TDSChannel enableSSL
WARNING: TLSv1 was negotiated. Please update server and client to use TLSv1.2 at minimum.
2021-10-21 21:05:12.007 [0-0-0-writer] INFO  CommonRdbmsWriter$Task - write oracle using update(RESULTID) mode
2021-10-21 21:05:22.356 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 2560 records, 209492 bytes | Speed 17.05KB/s, 213 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.661s |  All Task WaitReaderTime 0.245s | Percentage 0.00%
2021-10-21 21:05:23.560 [0-0-0-writer] WARN  CommonRdbmsWriter$Task - 回滚此次写入, 采用每次写入一行方式提交. 因为: Invalid column index: getValidColumnIndex
2021-10-21 21:05:23.596 [0-0-0-writer] ERROR StdoutPluginCollector - 
java.sql.SQLException: Invalid column index: getValidColumnIndex
	at oracle.jdbc.driver.OracleResultSetMetaData.getValidColumnIndex(OracleResultSetMetaData.java:102)
	at oracle.jdbc.driver.OracleResultSetMetaData.getColumnType(OracleResultSetMetaData.java:398)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:454)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doOneInsert(CommonRdbmsWriter.java:428)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:316)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
	at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
	at java.lang.Thread.run(Thread.java:748)
2021-10-21 21:05:23.604 [0-0-0-writer] ERROR StdoutPluginCollector - 脏数据: {"exception":"Invalid column index: getValidColumnIndex","record":[{"byteSize":4,"rawData":"3330","type":"DOUBLE"},{"byteSize":3,"rawData":"487","type":"DOUBLE"},{"byteSize":1,"rawData":2,"type":"LONG"},{"byteSize":2,"rawData":67,"type":"LONG"},{"byteSize":7,"rawData":"0301008","type":"STRING"},{"byteSize":1,"rawData":"0","type":"STRING"},{"byteSize":6,"rawData":"3.5000","type":"DOUBLE"},{"byteSize":3,"rawData":"3.5","type":"STRING"},{"byteSize":0,"type":"STRING"},{"byteSize":0,"type":"STRING"},{"byteSize":0,"type":"STRING"},{"byteSize":0,"type":"STRING"},{"byteSize":0,"type":"STRING"},{"byteSize":0,"type":"STRING"},{"byteSize":0,"rawData":"","type":"STRING"},{"byteSize":1,"rawData":"M","type":"STRING"},{"byteSize":1,"rawData":"0","type":"STRING"},{"byteSize":6,"rawData":"umol/L","type":"STRING"},{"byteSize":8,"rawData":"1.7--6.8","type":"

**Comment by wgzhao** [comment]
我明天再仔细测试，看能否重现上述问题

**Comment by wgzhao** [comment]
静态类中变量声明存在问题，导致变量初始化后，没有保存下来。
麻烦用附件中的文件解压后，替换 `lib/addax-rdbms-4.0.5.jar` 后，再测试看看是否还存在这个问题
本地复现了该问题，并已经修复。

感谢反馈！
[addax-rdbms-4.0.5.jar.zip](https://github.com/wgzhao/Addax/files/7393688/addax-rdbms-4.0.5.jar.zip)
