### ISSUE TITLE
jsonfilereader支持数组吗

### ISSUE THREAD

**Issue by zhbdesign** [wgzhao/Addax#452]
{"reqID":"1","errorType":"logicerror","errorDetail":[{"errorCode":"2","errorMsg":"失败"}]}

支持后边的数组吗

**Comment by wgzhao** [comment]
可以使用 `$. errorDetail. errorCode` 来取得其值。

详细情况，可以参考[文档中的例子](https://wgzhao.github.io/Addax/develop/reader/jsonfilereader/)

**Comment by zhbdesign** [comment]
> 可以使用 `$. errorDetail. errorCode` 来取得其值。
> 
> 详细情况，可以参考[文档中的例子](https://wgzhao.github.io/Addax/develop/reader/jsonfilereader/)

出现了错误
日志如下：
$ python bin/addax.py job/bh_error_record.json
▒▒▒▒▒ҳ: 936

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.6)

2021-11-24 16:49:08.730 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2021-11-24 16:49:08.748 [        main] INFO  Engine               -
{
        "content":[
                {
                        "reader":{
                                "parameter":{
                                        "path":[
                                                "data/bh/▒▒▒▒▒▒▒▒▒▒▒▒_20211123_0001.json"
                                        ],
                                        "column":[
                                                {
                                                        "type":"long",
                                                        "value":"$.reqID"
                                                },
                                                {
                                                        "type":"string",
                                                        "value":"$.errorType"
                                                },
                                                {
                                                        "type":"string",
                                                        "value":"$.errorDetail"
                                                }
                                        ]
                                },
                                "name":"jsonfilereader"
                        },
                        "writer":{
                                "parameter":{
                                        "password":"*****",
                                        "session":[
                                                ""
                                        ],
                                        "column":[
                                                "*"
                                        ],
                                        "connection":[
                                                {
                                                        "driver":"com.mysql.jdbc.Driver",
                                                        "jdbcUrl":"jdbc:mysql://10.100.2.53:3306/xs_dcl?useSSL=false",
                                                        "table":[
                                                                "bh_error_record"
                                                        ]
                                                }
                                        ],
                                        "writeMode":"insert",
                                        "username":"root",
                                        "preSql":[
                                                ""
                                        ]
                                },
                                "name":"mysqlwriter"
                        }
                }
        ],
        "setting":{
                "speed":{
                        "bytes":-1,
                        "channel":1
                }
        }
}

2021-11-24 16:49:08.766 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2021-11-24 16:49:08.766 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2021-11-24 16:49:08.767 [        main] INFO  JobContainer         - Set jobId = 0
2021-11-24 16:49:08.805 [       job-0] WARN  OriginalConfPretreatmentUtil - use specified driver class: com.mysql.jdbc.Driver
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2021-11-24 16:49:09.126 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[bh_error_record] all columns:[reqid,errortype,errordetail].
2021-11-24 16:49:09.127 [       job-0] WARN  OriginalConfPretreatmentUtil - ▒▒▒▒▒▒▒▒▒ļ▒▒е▒▒▒▒▒▒▒▒▒Ϣ▒▒▒ڷ▒▒▒. ▒▒Ϊ▒▒▒▒▒õ▒д▒▒▒▒▒ݿ▒▒▒▒▒Ϊ*▒▒▒▒▒▒▒ı▒▒ֶθ▒▒▒▒▒▒▒▒▒▒б䶯ʱ▒▒▒▒▒▒Ӱ▒▒▒▒▒▒▒▒ȷ▒▒▒▒▒▒▒▒▒▒▒г▒▒▒▒▒▒▒▒▒▒▒▒▒ò▒▒▒▒▒▒޸▒.
2021-11-24 16:49:09.128 [       job-0] INFO  OriginalConfPretreatmentUtil - Write data [insert INTO %s ( reqid,errortype,errordetail) VALUES ( ?,?,? )], which jdbcUrl [jdbc:mysql://10.100.2.53:3306/xs_dcl?useSSL=false&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&tinyInt1isBit=false]
2021-11-24 16:49:09.129 [       job-0] INFO  JobContainer         - Addax Reader.Job [jsonfilereader] do prepare work .
2021-11-24 16:49:09.130 [       job-0] INFO  JsonReader$Job       - add file [data/bh/▒▒▒▒▒▒▒▒▒▒▒▒_20211123_0001.json] as a candidate to be read.
2021-11-24 16:49:09.130 [       job-0] INFO  JsonReader$Job       - ▒▒▒▒▒▒▒▒ȡ▒▒▒ļ▒▒▒Ϊ: [1]
2021-11-24 16:49:09.131 [       job-0] INFO  JobContainer         - Addax Writer.Job [mysqlwriter] do prepare work .
2021-11-24 16:49:09.131 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channels.
2021-11-24 16:49:09.131 [       job-0] INFO  JobContainer         - Addax Reader.Job [jsonfilereader] splits to [1] tasks.
2021-11-24 16:49:09.132 [       job-0] INFO  JobContainer         - Addax Writer.Job [mysqlwriter] splits to [1] tasks.
2021-11-24 16:49:09.146 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2021-11-24 16:49:09.153 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2021-11-24 16:49:09.156 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2021-11-24 16:49:09.156 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2021-11-24 16:49:09.165 [0-0-0-reader] INFO  JsonReader$Task      - reading file : [data/bh/▒▒▒▒▒▒▒▒▒▒▒▒_20211123_0001.json]
2021-11-24 16:49:09.175 [0-0-0-reader] ERROR ReaderRunner         - Reader runner Received Exceptions:
java.lang.NoClassDefFoundError: com/jayway/jsonpath/JsonPath
        at com.wgzhao.addax.plugin.reader.jsonfilereader.JsonReader$Task.parseFromJson(JsonReader.java:380)
        at com.wgzhao.addax.plugin.reader.jsonfilereader.JsonReader$Task.startRead(JsonReader.java:532)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.jayway.jsonpath.JsonPath
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 common frames omitted
2021-11-24 16:49:09.212 [0-0-0-writer] INFO  DBUtil               - execute sql:[]
2021-11-24 16:49:09.216 [0-0-0-writer] ERROR WriterRunner         - Writer Runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-14], Description:[▒▒▒▒ session ʧ▒▒.].  - session▒▒▒▒▒▒▒▒. ▒▒Ϊ▒▒▒▒▒▒▒▒▒▒▒▒ִ▒▒ session ▒▒▒▒ʧ▒▒. ▒▒▒▒▒▒▒▒Ϣ▒▒:[jdbcUrl:[jdbc:mysql://10.100.2.53:3306/xs_dcl?useSSL=false&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&tinyInt1isBit=false], table:[bh_error_record]]. ▒▒▒▒▒▒▒▒▒▒▒ò▒▒▒▒▒▒޸▒. - java.sql.SQLException: Can not issue empty query.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479)
        at com.mysql.cj.jdbc.StatementImpl.checkNullOrEmptyQuery(StatementImpl.java:541)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:804)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:795)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
        at com.wgzhao.addax.rdbms.util.DBUtil.doDealWithSessionConfig(DBUtil.java:529)
        at com.wgzhao.addax.rdbms.util.DBUtil.dealWithSessionConfig(DBUtil.java:504)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.prepare(CommonRdbmsWriter.java:248)
        at com.wgzhao.addax.plugin.writer.mysqlwriter.MysqlWriter$Task.prepare(MysqlWriter.java:138)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:75)
        at java.lang.Thread.run(Unknown Source)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:58)
        at com.wgzhao.addax.rdbms.util.DBUtil.doDealWithSessionConfig(DBUtil.java:532)
        at com.wgzhao.addax.rdbms.util.DBUtil.dealWithSessionConfig(DBUtil.java:504)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.prepare(CommonRdbmsWriter.java:248)
        at com.wgzhao.addax.plugin.writer.mysqlwriter.MysqlWriter$Task.prepare(MysqlWriter.java:138)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:75)
        at java.lang.Thread.run(Unknown Source)

**Comment by wgzhao** [comment]
看报错是缺少依赖的jar文件，晚上我看看

**Comment by zhbdesign** [comment]
> 看报错是缺少依赖的jar文件，晚上我看看

看插件，那个jar已经在里边

**Comment by zhbdesign** [comment]
> 可以使用 `$. errorDetail. errorCode` 来取得其值。
> 
> 详细情况，可以参考[文档中的例子](https://wgzhao.github.io/Addax/develop/reader/jsonfilereader/)

我本地调试可以了，但是只能读取一行吗
{"reqID":"1","errorType":"logicerror","errorDetail":[{"errorCode":"2","errorMsg":"失败"}]}
{"reqID":"2","errorType":"logicerror","errorDetail":[{"errorCode":"2","errorMsg":"失败"}]}
这种只能读第一行，其他都读不到，有解决方法吗

**Comment by wgzhao** [comment]
当前读取的策略是把一个文件当作一个单一的json内容，你这个等于是一行是一个了。
估计要加一个配置标志参数，用来做区分。后续可以考虑加上。

**Comment by wgzhao** [comment]
可以读取多行，不过从你贴出的日志来看，你的json配置文件似乎有误

```json
 "column":[
          {
                  "type":"long",
                  "value":"$.reqID"
          },
          {
                  "type":"string",
                  "value":"$.errorType"
          },
          {
                  "type":"string",
                  "value":"$.errorDetail"
          }
  ]
```

这里不应该用 `value`, 而是应该用 `index`，我本地测试没有报错，执行过程如下：

```shell
**bin/addax.sh job/json2stream.json

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.7-SNAPSHOT)

2021-11-24 21:31:48.854 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2021-11-24 21:31:48.863 [        main] INFO  Engine               -
{
	"content":{
		"reader":{
			"parameter":{
				"path":[
					"/tmp/test.json"
				],
				"column":[
					{
						"index":"$.reqID",
						"type":"long"
					},
					{
						"index":"$.errorType",
						"type":"string"
					},
					{
						"index":"$.errorDetail[0].errorCode",
						"type":"long"
					},
					{
						"index":"$.errorDetail[0].errorMsg",
						"type":"string"
					}
				],
				"encoding":"UTF-8"
			},
			"name":"jsonfilereader"
		},
		"writer":{
			"parameter":{
				"print":true,
				"encoding":""
			},
			"name":"streamwriter"
		}
	},
	"setting":{
		"speed":{
			"byte":-1,
			"channel":1
		}
	}
}

2021-11-24 21:31:48.881 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2021-11-24 21:31:48.882 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2021-11-24 21:31:48.883 [        main] INFO  JobContainer         - Set jobId = 0
2021-11-24 21:31:48.895 [       job-0] INFO  JobContainer         - Addax Reader.Job [jsonfilereader] do prepare work .
2021-11-24 21:31:48.896 [       job-0] INFO  JsonReader$Job       - add file [/tmp/test.json] as a candidate to be read.
2021-11-24 21:31:48.896 [       job-0] INFO  JsonReader$Job       - 您即将读取的文件数为: [1]
2021-11-24 21:31:48.896 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] do prepare work .
2021-11-24 21:31:48.897 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2021-11-24 21:31:48.897 [       job-0] INFO  JobContainer         - Addax Reader.Job [jsonfilereader] splits to [1] tasks.
2021-11-24 21:31:48.898 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] splits to [1] tasks.
2021-11-24 21:31:48.918 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2021-11-24 21:31:48.928 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2021-11-24 21:31:48.931 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2021-11-24 21:31:48.931 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2021-11-24 21:31:48.941 [0-0-0-reader] INFO  JsonReader$Task      - reading file : [/tmp/test.json]
1	logicerror	2	失败
2	logicerror	2	失败
3	logicerror	2	失败
4	logicerror	2	失败
5	logicerror	2	失败
6	logicerror	2	失败
7	logicerror	2	失败
2021-11-24 21:31:51.938 [       job-0] INFO  AbstractScheduler    - Scheduler accomplished all tasks.
2021-11-24 21:31:51.939 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] do post work.
2021-11-24 21:31:51.939 [       job-0] INFO  JobContainer         - Addax Reader.Job [jsonfilereader] do post work.
2021-11-24 21:31:51.941 [       job-0] INFO  JobContainer         - PerfTrace not enable!
2021-11-24 21:31:51.942 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 7 records, 98 bytes | Speed 32B/s, 2 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.043s | Percentage 100.00%
2021-11-24 21:31:51.942 [       job-0] INFO  JobContainer         -
任务启动时刻                    : 2021-11-24 21:31:48
任务结束时刻                    : 2021-11-24 21:31:51
任务总计耗时                    :                  3s
任务平均流量                    :               32B/s
记录写入速度                    :              2rec/s
读出记录总数                    :                   7
读写失败总数                    :                   0
```
```

**Comment by zhbdesign** [comment]
用最新的自己打包可以了，maven用的是哪个仓库，现在有的依赖报错

**Comment by wgzhao** [comment]
具体哪个依赖有问题？
我用的 [腾讯的maven仓库](https://mirrors.cloud.tencent.com/help/maven.html)

**Comment by zhbdesign** [comment]
> 具体哪个依赖有问题？ 我用的 [腾讯的maven仓库](https://mirrors.cloud.tencent.com/help/maven.html)

clcickhouse的jdbd找不到，用的aliyun的，另外，jsonfilereader可以加个配置，skipRows，跳过前多少行

**Comment by wgzhao** [comment]
> > 具体哪个依赖有问题？ 我用的 [腾讯的maven仓库](https://mirrors.cloud.tencent.com/help/maven.html)
> 
> clcickhouse的jdbc找不到，用的aliyun的，另外，jsonfilereader可以加个配置，skipRows，跳过前多少行

刚去aliyun的maven仓库搜索了下，是可以找到 `clickhouse-jdbc` 驱动的，但我之前被它坑过几次，之后就全部使用腾讯的仓库了。

**Comment by zhbdesign** [comment]
> > > 具体哪个依赖有问题？ 我用的 [腾讯的maven仓库](https://mirrors.cloud.tencent.com/help/maven.html)
> > 
> > 
> > clcickhouse的jdbc找不到，用的aliyun的，另外，jsonfilereader可以加个配置，skipRows，跳过前多少行
> 
> 刚去aliyun的maven仓库搜索了下，是可以找到 `clickhouse-jdbc` 驱动的，但我之前被它坑过几次，之后就全部使用腾讯的仓库了。

看了下excelreader是有skiprows的，jsonfilereader最好也优化下，我也改用腾讯把，

**Comment by wgzhao** [comment]
Excel 文件 和类 CSV 格式文件都可以存在标头，但是 json 文件不存在标头的问题，所以，大概在什么样的场景下，会需要跳过一个json文件的头几行呢？
