### ISSUE TITLE
[Bug]: rdbms支持vertica问题 

### ISSUE THREAD

**Issue by nmgliangwei** [wgzhao/Addax#460]
### What happened?

oraclereader:oracle
writer:rdmswriter

rdmswriter的plugin.json 加了如下配置:
"drivers": ["com.vertica.jdbc.Driver"]
vertica的vertica-jdbc-9.0.1-7.jar 放到了rdmswriter的 lib 和 addax 的 lib 下面.

1.运行任务报错:
2021-11-30 15:56:26.565 [       job-0] ERROR RetryUtil            - Exception when calling callable, 异常Msg:Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot load JDBC driver class 'com.wgzhao.addax.plugin.rdbms.util.DataBaseType'
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot load JDBC driver class 'com.wgzhao.addax.plugin.rdbms.util.DataBaseType'
        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.rdbms.util.RdbmsException.asConnException(RdbmsException.java:61)
        at com.wgzhao.addax.rdbms.util.DBUtil.connect(DBUtil.java:295)
        at com.wgzhao.addax.rdbms.util.DBUtil.lambda$getConnection$2(DBUtil.java:230)
        at com.wgzhao.addax.common.util.RetryUtil$Retry.call(RetryUtil.java:202)
        at com.wgzhao.addax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:147)
        at com.wgzhao.addax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:59)
        at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:230)
        at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:223)
        at com.wgzhao.addax.rdbms.util.JdbcConnectionFactory.getConnection(JdbcConnectionFactory.java:52)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:145)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:184)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:66)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:68)
        at com.wgzhao.addax.plugin.reader.rdbmswriter.RdbmsWriter$Job.init(RdbmsWriter.java:63)
        at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:710)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:326)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:132)
        at com.wgzhao.addax.core.Engine.start(Engine.java:79)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:137)
        at com.wgzhao.addax.core.Engine.main(Engine.java:175)
2021-11-30 15:56:27.567 [       job-0] ERROR RetryUtil            - Exception when calling callable, 即将尝试执行第1次重试.本次重试计划等待[1000]ms,实际等待[1000]ms, 异常Msg:[Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot load JDBC driver class 'com.wgzhao.addax.plugin.rdbms.util.DataBaseType']
^[[A2021-11-30 15:56:29.570 [       job-0] ERROR RetryUtil            - Exception when calling callable, 即将尝试执行第2次重试.本次重试计划等待[2000]ms,实际等待[2000]ms, 异常Msg:[Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot load JDBC driver class 'com.wgzhao.addax.plugin.rdbms.util.DataBaseType']
2021-11-30 15:56:29.582 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2021-11-30 15:56:29.583 [       job-0] ERROR Engine               - Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  - Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot load JDBC driver class 'com.wgzhao.addax.plugin.rdbms.util.DataBaseType'

2.如果在 任务的 json 文件中指定"driver":"com.vertica.jdbc.Driver"
报错如下:
java.sql.SQLException: Cannot create JDBC driver of class 'com.vertica.jdbc.Driver' for connect URL '["jdbc:vertica://xxxxx"]'
        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.rdbms.util.RdbmsException.asConnException(RdbmsException.java:61)
        at com.wgzhao.addax.rdbms.util.DBUtil.connect(DBUtil.java:295)
        at com.wgzhao.addax.rdbms.util.DBUtil.lambda$getConnection$2(DBUtil.java:230)
        at com.wgzhao.addax.common.util.RetryUtil$Retry.call(RetryUtil.java:202)
        at com.wgzhao.addax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:147)
        at com.wgzhao.addax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:59)
        at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:230)
        at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:223)
        at com.wgzhao.addax.rdbms.util.JdbcConnectionFactory.getConnection(JdbcConnectionFactory.java:52)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:145)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:184)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:66)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:68)
        at com.wgzhao.addax.plugin.reader.rdbmswriter.RdbmsWriter$Job.init(RdbmsWriter.java:63)
        at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:710)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:326)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:132)
        at com.wgzhao.addax.core.Engine.start(Engine.java:79)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:137)
        at com.wgzhao.addax.core.Engine.main(Engine.java:175)

### Version

4.0.3

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by nmgliangwei** [comment]
@wgzhao 大佬帮看下,使用 datax 的时候,在 plugin.json 中,添加"drivers": ["com.vertica.jdbc.Driver"]即可使用.

**Comment by wgzhao** [comment]
你用的是4.0.3版本吗？

**Comment by nmgliangwei** [comment]
@wgzhao 是的

**Comment by wgzhao** [comment]
请参考该版本的使用手册：https://addax.readthedocs.io/zh/4.0.3/writer/rdbmswriter.html
4.0.3 版本的使用方式和 `datax` 差异不大

**Comment by nmgliangwei** [comment]
@wgzhao 就是按照手册来的,但是报错.

**Comment by wgzhao** [comment]
我本次测试下

**Comment by wgzhao** [comment]
@nmgliangwei 很抱歉，是文档有误，更正流程如下：

1. 将 `vertica-jdbc-9.0.1-7.jar` 拷贝到 `plugin/writer/rdbmswriter/libs` 目录
2.  `plugin/writer/rdbmswriter/plugin.json` 配置文件中的请设置为 `"drivers": []`, 即不填写任何驱动信息，这点很重要。
3.  在 任务的 `json`  文件中，添加 `driver` 配置项。类似如下：

```json
{
  "job": {
    "setting": {
      "speed": {
        "channel": 1,
        "bytes": -1
      }
    },
    "content": [
      {
        "reader": {
          "name": "streamreader",
          "parameter": {
            "column": [
              {
                "value": "Addax",
                "type": "string"
              },
              {
                "value": 19880808,
                "type": "long"
              },
              {
                "value": "1988-08-08 08:08:08",
                "type": "date"
              },
              {
                "value": true,
                "type": "bool"
              },
              {
                "value": "test",
                "type": "bytes"
              }
            ],
            "sliceRecordCount": 1000
          }
        },
        "writer": {
          "name": "rdbmswriter",
          "parameter": {
            "connection": [
              {
                "jdbcUrl": "jdbc:vertica://127.0.0.1:1231",
                "driver": "com.vertica.jdbc.Driver",
                "table": [
                  "table"
                ]
              }
            ],
            "username": "username",
            "password": "password",
            "column": [
              "*"
            ]
          }
        }
      }
    ]
  }
}
```
4. 测试

**Comment by nmgliangwei** [comment]
@wgzhao 依然报错

com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot create JDBC driver of class 'com.vertica.jdbc.Driver' for connect URL '["jdbc:vertica://xxxxx"]'
        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.rdbms.util.RdbmsException.asConnException(RdbmsException.java:61)
        at com.wgzhao.addax.rdbms.util.DBUtil.connect(DBUtil.java:295)
        at com.wgzhao.addax.rdbms.util.DBUtil.lambda$getConnection$2(DBUtil.java:230)
        at com.wgzhao.addax.common.util.RetryUtil$Retry.call(RetryUtil.java:202)
        at com.wgzhao.addax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:147)
        at com.wgzhao.addax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:59)
        at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:230)
        at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:223)
        at com.wgzhao.addax.rdbms.util.JdbcConnectionFactory.getConnection(JdbcConnectionFactory.java:52)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:145)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:184)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:66)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:68)
        at com.wgzhao.addax.plugin.reader.rdbmswriter.RdbmsWriter$Job.init(RdbmsWriter.java:63)
        at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:710)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:326)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:132)
        at com.wgzhao.addax.core.Engine.start(Engine.java:79)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:137)
        at com.wgzhao.addax.core.Engine.main(Engine.java:175)

**Comment by nmgliangwei** [comment]
@wgzhao 不好意思,可以了.是因为 这个地方"jdbcUrl": ["jdbc:vertica://127.0.0.1:1231"],使用了 list,用"jdbc:vertica://127.0.0.1:1231"可以了.

**Comment by wgzhao** [comment]
嗯
这个地方和reader 不一样
很容易进坑

所以我一般希望大家附上完整的日志
这样能看到完整的配置文件
更容易定位问题

**Comment by nmgliangwei** [comment]
rdmsreader 正确的流程是什么样的

**Comment by wgzhao** [comment]
> rdmsreader 正确的流程是什么样的

和 `rdbmswriter` 流程一样

**Comment by nmgliangwei** [comment]
好的,感谢. @wgzhao
