### ISSUE TITLE
[Bug]: rdbmswriter插件无法正确识别db2的jdbc驱动

### ISSUE THREAD

**Issue by XhivaW** [wgzhao/Addax#484]
### What happened?

如题

Addax版本4.0.7

CentOS 7 + JDK 1.8

使用的json如下：
```json
{
    "job": {
        "setting": {
            "speed": {
                "channel": 4
            }
        },
        "content": {
            "reader": {
                "name": "hdfsreader",
                "parameter": {
                    "path": "/user/hive/warehouse/xxxxx.db/test_table/",
                    "defaultFS": "hdfs://nameservice1:8020",
                    "hadoopConfig": {
                        "dfs.nameservices": "nameservice1",
                        "dfs.ha.namenodes.nameservice1": "AA,BB",
                        "dfs.namenode.rpc-address.nameservice1.namenode2214": "AAAAAAAAA:8020",
                        "dfs.namenode.rpc-address.nameservice1.namenode2212": "BBBBBBBBBB:8020",
                        "dfs.client.failover.proxy.provider.nameservice1": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"
                    },
                    "column": [
                        "*"
                    ],
                    "fileType": "orc",
                    "encoding": "UTF-8",
                    "compress": "NONE",
                    "fieldDelimiter": "\u0001"
                }
            },
            "writer": {
                "name": "rdbmswriter",
                "parameter": {
                    "username": "UUUUUUU",
                    "password": "PPPPPPPP",
                    "column": [
                        "*"
                    ],
                    "driver": "com.ibm.db2.jcc.DB2Driver",
                    "connection": [
                        {
                            "jdbcUrl": "jdbc:db2://XXXXXX:YYYYYY/ZZZZZZ",
                            "table": [
                                "TEST_TABLE"
                            ]
                        }
                    ],
                    "preSql": [
                        "DELETE FROM TEST_TABLE;"
                    ]
                }
            }
        }
    }
}
```
同时确认`/run/addax-4.0.7/plugin/writer/rdbmswriter/libs/`已存在从`/run/addax-4.0.7/plugin/reader/rdbmsreader/libs/`中复制来的`db2jcc-db2jcc4.jar`驱动包 且插件声明文件`/run/addax-4.0.7/plugin/writer/rdbmswriter/plugin.json`如下已正常声明：
```json
{
  "name": "rdbmswriter",
  "class": "com.wgzhao.addax.plugin.reader.rdbmswriter.RdbmsWriter",
  "description": "general RDBMS writer plugin",
  "developer": "alibaba",
  "drivers": ["com.ibm.db2.jcc.DB2Driver"]
}
```

但执行时依然报错：
```bash
Caused by: com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-00], Description:[您的配置错误.].  - 数据库驱动加载错误, 请确认libs目录有驱动jar包且plugin.json中drivers配置驱动类正确! - java.lang.ClassNotFoundException: com.ibm.db2.jcc.DB2Driver
```

### Version

4.0.6 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
请将  `/run/addax-4.0.7/plugin/writer/rdbmswriter/plugin.json` 文件中的  `drivers` 置空，然后再测试看看。
另外，丛这个报错信息来，怎么觉得和你提供的版本不对？
可以提供完整的日志信息吗？

**Comment by XhivaW** [comment]
确实是4.0.7版本 完整报错如下：

```bash
2021-12-30 08:18:36.539 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2021-12-30 08:18:36.539 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2021-12-30 08:18:36.540 [        main] INFO  JobContainer         - Set jobId = 0
2021-12-30 08:18:36.547 [       job-0] INFO  HdfsReader$Job       - init() begin...
2021-12-30 08:18:36.664 [       job-0] INFO  DFSUtil              - hadoopConfig details:{"finalParameters":["hadoop.ssl.require.client.cert","hadoop.ssl.client.conf","hadoop.ssl.server.conf","hadoop.ssl.keystores.factory.class"]}
2021-12-30 08:18:36.664 [       job-0] INFO  HdfsReader$Job       - init() ok and end...
2021-12-30 08:18:36.672 [       job-0] INFO  JobContainer         - PerfTrace not enable!
java.lang.ExceptionInInitializerError
        at com.wgzhao.addax.plugin.reader.rdbmswriter.RdbmsWriter$Job.init(RdbmsWriter.java:65)
        at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:646)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:310)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:130)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)
Caused by: com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-00], Description:[您的配置错误.].  - 数据库驱动加载错误, 请确认libs目录有驱动jar包且plugin.json中drivers配置驱动类正确! - java.lang.ClassNotFoundException: com.ibm.db2.jcc.DB2Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.wgzhao.addax.rdbms.util.DBUtil.loadDriverClass(DBUtil.java:579)
        at com.wgzhao.addax.plugin.reader.rdbmswriter.RdbmsWriter.<clinit>(RdbmsWriter.java:135)
        at com.wgzhao.addax.plugin.reader.rdbmswriter.RdbmsWriter$Job.init(RdbmsWriter.java:65)
        at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:646)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:310)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:130)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:58)
        at com.wgzhao.addax.rdbms.util.DBUtil.loadDriverClass(DBUtil.java:583)
        at com.wgzhao.addax.plugin.reader.rdbmswriter.RdbmsWriter.<clinit>(RdbmsWriter.java:135)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.ibm.db2.jcc.DB2Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.wgzhao.addax.rdbms.util.DBUtil.loadDriverClass(DBUtil.java:579)
        ... 8 more
```

**Comment by XhivaW** [comment]
> 请将 `/run/addax-4.0.7/plugin/writer/rdbmswriter/plugin.json` 文件中的 `drivers` 置空，然后再测试看看。 另外，丛这个报错信息来，怎么觉得和你提供的版本不对？ 可以提供完整的日志信息吗？

另外 清空 `/run/addax-4.0.7/plugin/writer/rdbmswriter/plugin.json` 文件中的 `drivers` 确实可以执行了 不大理解为啥 原来的 `/run/addax-4.0.7/plugin/writer/rdbmswriter/libs`中似乎没有db2的驱动包

**Comment by wgzhao** [comment]
第三方的jar包现在都没有内置了

**Comment by XhivaW** [comment]
> 

好的 所以只要把db2驱动包放入rdbmswriter的libs路径 不用声明plugin.json的drivers就可以使用对吗？ 总之现在解决这个问题了 谢谢
