### ISSUE TITLE
[Bug]: 使用rdbmswriter中触发asTimestamp函数异常

### ISSUE THREAD

**Issue by XhivaW** [wgzhao/Addax#488]
### What happened?

原因是之前发的[hdfsreader读取hive中date数据类型的异常](https://github.com/wgzhao/Addax/issues/487)

在触发上述异常的情况下，使用rdbmswriter写入db2数据库timestamp数据类型字段，会触发报错：
hive表：
```sql
create table test.addax_test_date (
    v date
) stored as orc;
```

DB2表：
```sql
create table test.addax_test_date (
    v timestamp(0)
);
```

```bash
2021-12-31 13:43:02.374 [0-0-0-writer] ERROR WriterRunner         - Writer Runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Long
        at com.wgzhao.addax.common.element.LongColumn.asTimestamp(LongColumn.java:123)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:536)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:455)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:398)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
        at com.wgzhao.addax.plugin.reader.rdbmswriter.RdbmsWriter$Task.startWrite(RdbmsWriter.java:117)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
 - java.lang.ClassCastException: java.math.BigInteger cannot be cast to java.lang.Long
```

根本原因是上面提到的issue 不过这里也发现`Addax/common/src/main/java/com/wgzhao/addax/common/element/LongColumn.java`中：
```java
    @Override
    public Timestamp asTimestamp()
    {
        if (null == this.getRawData()) {
            return null;
        }
        return new Timestamp((Long) this.getRawData());
    }
```
这个函数直接进行强制类型转换 作为参考 同文件下asLong函数就会先声明转换
```java
    @Override
    public Long asLong()
    {
        BigInteger rawData = (BigInteger) this.getRawData();
        if (null == rawData) {
            return null;
        }

        OverFlowUtil.validateLongNotOverFlow(rawData);

        return rawData.longValue();
    }
```
将asTimestamp函数进行类似改造后 就不会报该类型转换错误了
```java
    @Override
    public Timestamp asTimestamp()
    {
        if (null == this.getRawData()) {
            return null;
        }

        if(this.getRawData() instanceof BigInteger) {
            BigInteger b = (BigInteger) this.getRawData();
            long l = b.longValue();
            return new Timestamp(l);
        }else{
            return new Timestamp((Long) this.getRawData());
        }
    }
```
个人对Java不大熟悉 不大确定这个算hdfsreader的异常引发的意外效果 还是函数本身逻辑缺失

### Version

4.0.7

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by XhivaW** [comment]
另外作者元旦快乐！

**Comment by wgzhao** [comment]
感谢反馈，我晚一点处理
同祝快乐！
