### ISSUE TITLE
[Bug]: clickhousereader 不能用 

### ISSUE THREAD

**Issue by tixff** [wgzhao/Addax#491]
### Contact Details（联系人）

lixinlinti@gmail.com

### What happened?

A bug happened!
**执行异常：**
`2022-01-05 17:27:10.224 [0-0-0-reader] ERROR ReaderRunner         - Reader runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select * from light_trigger limit 10 具体错误信息为：java.sql.SQLFeatureNotSupportedException: Transactions are not supported
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
	at com.wgzhao.addax.plugin.reader.clickhousereader.ClickHouseReader$Task.startRead(ClickHouseReader.java:133)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)`
**clickhouse客户端执行sql 正常：**
`iot-node0 :) select * from light_trigger limit 10

SELECT *
FROM light_trigger
LIMIT 10

Query id: 7078c292-81b7-47b2-bbe5-1b69e29c6bf5

┌─productKey──────┬─deviceName───────────────────────────┬─topic────────────────────────────────────────────────────────────────────────┬─messageId────────────────────────────┬─────timestamp─┬─topicId─────────┬─topicType─┬─qos─┬─id───────┬─method──────────────────┬─version─┬──────────time─┬─area─┬─cluster─┬─number─┬─uuid────────────────────────────────┬─nwk_id─┬─device_name──────────────────────────┬─trig_time──┬─house_dt─┐
│ xA707NOn1Lh1D4r │ 5b0f8e70-317f-4ff3-8f83-0150499379a6 │ xA707NOn1Lh1D4r/5b0f8e70-317f-4ff3-8f83-0150499379a6/user/event/trigger/post │ cdcf1fff-dee9-423a-a6ea-46cdefb1c457 │ 1640659756859 │ 0NXnXGxOmpFGEYz │         0 │   1 │ 13-2-3   │ user.event.trigger.post │ 1.0     │ 1640659756987 │   13 │       2 │      3 │ 00-00-00-00-00-00-00-00-00-00-00-00 │ C4-21  │ 5b0f8e70-317f-4ff3-8f83-0150499379a6 │ 1640659756 │ 20211228 │
│ xA707NOn1Lh1D4r │ a5be5b7a-8e9a-4b6b-a74f-f9b40c6eae4d │ xA707NOn1Lh1D4r/a5be5b7a-8e9a-4b6b-a74f-f9b40c6eae4d/user/event/trigger/post │ a15de4f5-5a28-475d-a198-3fb9d6575521 │ 1640659756860 │ 0NXnXGxOmpFGEYz │         0 │   1 │ 2-3-3    │ user.event.trigger.post │ 1.0     │ 1640659755616 │    2 │       3 │      3 │ 00-00-00-00-00-00-00-00-00-00-00-00 │ 8C-29  │ a5be5b7a-8e9a-4b6b-a74f-f9b40c6eae4d │ 1640659755 │ 20211228 │
│ xA707NOn1Lh1D4r │ 1ab4a6f5-119c-47c3-9cab-36882811264b │ xA707NOn1Lh1D4r/1ab4a6f5-119c-47c3-9cab-36882811264b/user/event/trigger/post │ 25de1dd1-7610-4834-969d-9331c1bd3461 │ 1640659756867 │ 0NXnXGxOmpFGEYz │         0 │   1 │ 2-10-103 │ user.event.trigger.post │ 1.0     │ 1640659756668 │    2 │      10 │    103 │ 00-00-00-00-00-00-00-00-00-00-00-00 │ 8C-29  │ 1ab4a6f5-119c-47c3-9cab-36882811264b │ 1640659756 │ 20211228 │
│ xA707NOn1Lh1D4r │ 2166e4b2-fd73-457a-b24e-6849afc0b01c │ xA707NOn1Lh1D4r/2166e4b2-fd73-457a-b24e-6849afc0b01c/user/event/trigger/post │ 1ed9dfd5-93b5-4a80-a9b5-36244ac1b776 │ 1640659756879 │ 0NXnXGxOmpFGEYz │         0 │   1 │ 1-2-1    │ user.event.trigger.post │ 1.0     │ 1640659756653 │    1 │       2 │      1 │ 00-00-00-00-00-00-00-00-00-00-00-00 │ 3D-E8  │ 2166e4b2-fd73-457a-b24e-6849afc0b01c │ 1640659756 │ 20211228 │
│ xA707NOn1Lh1D4r │ c93d1838-0ba3-4f57-8cbe-be332e5c773e │ xA707NOn1Lh1D4r/c93d1838-0ba3-4f57-8cbe-be332e5c773e/user/event/trigger/post │ f882af19-d86e-4d9d-ae12-4a1572277487 │ 1640659756888 │ 0NXnXGxOmpFGEYz │         0 │   1 │ 2-9-1    │ user.event.trigger.post │ 1.0     │ 1640659756724 │    2 │       9 │      1 │ 00-00-00-00-00-00-00-00-00-00-00-00 │ DD-E9  │ c93d1838-0ba3-4f57-8cbe-be332e5c773e │ 1640659756 │ 20211228 │
│ xA707NOn1Lh1D4r │ 1dc741de-5122-4750-9b3e-9802c1975d1e │ xA707NOn1Lh1D4r/1dc741de-5122-4750-9b3e-9802c1975d1e/user/event/trigger/post │ 82bfb355-6184-4d97-b650-21659317c05d │ 1640659756896 │ 0NXnXGxOmpFGEYz │         0 │   1 │ 1-5-3    │ user.event.trigger.post │ 1.0     │ 1640659756687 │    1 │       5 │      3 │ 00-00-00-00-00-00-00-00-00-00-00-00 │ 8C-29  │ 1dc741de-5122-4750-9b3e-9802c1975d1e │ 1640659756 │ 20211228 │
│ xA707NOn1Lh1D4r │ 8d480377-63f0-4aab-ac3e-445f71d8e2ef │ xA707NOn1Lh1D4r/8d480377-63f0-4aab-ac3e-445f71d8e2ef/user/event/trigger/post │ 161346f4-1004-4b32-bef7-a787a3648068 │ 1640659756898 │ 0NXnXGxOmpFGEYz │         0 │   1 │ 1-4-15   │ user.event.trigger.post │ 1.0     │ 1640659756313 │    1 │       4 │     15 │ 00-00-00-00-00-00-00-00-00-00-00-00 │ 0C-05  │ 8d480377-63f0-4aab-ac3e-445f71d8e2ef │ 1640659756 │ 20211228 │
│ xA707NOn1Lh1D4r │ a52484d3-f074-4d19-aebd-3e92edade64e │ xA707NOn1Lh1D4r/a52484d3-f074-4d19-aebd-3e92edade64e/user/event/trigger/post │ 75570672-fa62-49a6-b46a-2eca9e230cb1 │ 1640659756901 │ 0NXnXGxOmpFGEYz │         0 │   1 │ 5-1-4    │ user.event.trigger.post │ 1.0     │ 1640659756762 │    5 │       1 │      4 │ 00-00-00-00-00-00-00-00-00-00-00-00 │ DD-E9  │ a52484d3-f074-4d19-aebd-3e92edade64e │ 1640659756 │ 20211228 │
│ xA707NOn1Lh1D4r │ 5b0f8e70-317f-4ff3-8f83-0150499379a6 │ xA707NOn1Lh1D4r/5b0f8e70-317f-4ff3-8f83-0150499379a6/user/event/trigger/post │ 0e8dfe55-248b-4938-88fc-12c3ac2b955d │ 1640659756903 │ 0NXnXGxOmpFGEYz │         0 │   1 │ 14-8-3   │ user.event.trigger.post │ 1.0     │ 1640659757034 │   14 │       8 │      3 │ 00-00-00-00-00-00-00-00-00-00-00-00 │ C4-21  │ 5b0f8e70-317f-4ff3-8f83-0150499379a6 │ 1640659757 │ 20211228 │
│ xA707NOn1Lh1D4r │ ba977958-17bf-4d2f-b0c7-e26d641266e4 │ xA707NOn1Lh1D4r/ba977958-17bf-4d2f-b0c7-e26d641266e4/user/event/trigger/post │ 45ac4aca-9172-4935-bb18-fa29b296a5ab │ 1640659756905 │ 0NXnXGxOmpFGEYz │         0 │   1 │ 1-3-105  │ user.event.trigger.post │ 1.0     │ 1640659756714 │    1 │       3 │    105 │ 00-00-00-00-00-00-00-00-00-00-00-00 │ 3D-E8  │ ba977958-17bf-4d2f-b0c7-e26d641266e4 │ 1640659756 │ 20211228 │
└─────────────────┴──────────────────────────────────────┴──────────────────────────────────────────────────────────────────────────────┴──────────────────────────────────────┴───────────────┴─────────────────┴───────────┴─────┴──────────┴─────────────────────────┴─────────┴───────────────┴──────┴─────────┴────────┴─────────────────────────────────────┴────────┴──────────────────────────────────────┴────────────┴──────────┘

10 rows in set. Elapsed: 0.006 sec. `

### Version

4.0.8 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell
[root@iot-node2 /home/bigdata/app/addax-4.0.8-SNAPSHOT/job]#../bin/addax.sh clickhouse2stream.json 

  ___      _     _            
 / _ \    | |   | |           
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  < 
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.8-SNAPSHOT)

2022-01-05 17:27:09.561 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-01-05 17:27:09.571 [        main] INFO  Engine               - 
{
	"content":{
		"reader":{
			"parameter":{
				"password":"*****",
				"column":[
					"*"
				],
				"connection":[
					{
						"querySql":[
							"select * from light_trigger limit 10"
						],
						"jdbcUrl":[
							"jdbc:clickhouse://iot-node0:8123/dwd"
						]
					}
				],
				"username":"default"
			},
			"name":"clickhousereader"
		},
		"writer":{
			"parameter":{
				"print":true
			},
			"name":"streamwriter"
		}
	},
	"setting":{
		"errorLimit":{
			"record":0,
			"percentage":0.02
		},
		"speed":{
			"channel":3
		}
	}
}

2022-01-05 17:27:09.592 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-01-05 17:27:09.593 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2022-01-05 17:27:09.594 [        main] INFO  JobContainer         - Set jobId = 0
2022-01-05 17:27:09.699 [       job-0] INFO  ClickHouseDriver     - Driver registered
2022-01-05 17:27:10.081 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:clickhouse://iot-node0:8123/dwd.
2022-01-05 17:27:10.083 [       job-0] WARN  OriginalConfPretreatmentUtil - 您的配置有误. 由于您读取数据库表采用了querySql的方式, 所以您不需要再配置 column. 如果您不想看到这条提醒，请移除您源头表中配置中的 column.
2022-01-05 17:27:10.093 [       job-0] INFO  JobContainer         - Addax Reader.Job [clickhousereader] do prepare work .
2022-01-05 17:27:10.093 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] do prepare work .
2022-01-05 17:27:10.094 [       job-0] INFO  JobContainer         - Job set Channel-Number to 3 channel(s).
2022-01-05 17:27:10.098 [       job-0] INFO  JobContainer         - Addax Reader.Job [clickhousereader] splits to [1] tasks.
2022-01-05 17:27:10.099 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] splits to [1] tasks.
2022-01-05 17:27:10.133 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2022-01-05 17:27:10.150 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2022-01-05 17:27:10.157 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2022-01-05 17:27:10.157 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2022-01-05 17:27:10.184 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select * from light_trigger limit 10
] jdbcUrl:[jdbc:clickhouse://iot-node0:8123/dwd].
2022-01-05 17:27:10.224 [0-0-0-reader] ERROR ReaderRunner         - Reader runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select * from light_trigger limit 10 具体错误信息为：java.sql.SQLFeatureNotSupportedException: Transactions are not supported
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
	at com.wgzhao.addax.plugin.reader.clickhousereader.ClickHouseReader$Task.startRead(ClickHouseReader.java:133)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select * from light_trigger limit 10 具体错误信息为：java.sql.SQLFeatureNotSupportedException: Transactions are not supported
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
	at com.wgzhao.addax.plugin.reader.clickhousereader.ClickHouseReader$Task.startRead(ClickHouseReader.java:133)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)
2022-01-05 17:27:13.165 [       job-0] ERROR JobContainer         - 运行scheduler出错.
2022-01-05 17:27:13.168 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select * from light_trigger limit 10 具体错误信息为：java.sql.SQLFeatureNotSupportedException: Transactions are not supported
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
	at com.wgzhao.addax.plugin.reader.clickhousereader.ClickHouseReader$Task.startRead(ClickHouseReader.java:133)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wgzhao** [comment]
原因是 `clickhouse` 不支持 `autocommit` 特性

**Comment by tixff** [comment]
**clickhouse写入bug：**
`com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.sql.SQLException: Cannot rollback when auto-commit is enabled
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at ru.yandex.clickhouse.ClickHouseConnectionImpl.rollback(ClickHouseConnectionImpl.java:230)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:482)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:482)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:407)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task.startWrite(ClickHouseWriter.java:137)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.Thread.run(Thread.java:748)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53]  - java.sql.SQLException: Cannot rollback when auto-commit is enabled
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at ru.yandex.clickhouse.ClickHouseConnectionImpl.rollback(ClickHouseConnectionImpl.java:230)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:482)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:482)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:407)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task.startWrite(ClickHouseWriter.java:137)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.Thread.run(Thread.java:748)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:327)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task.startWrite(ClickHouseWriter.java:137)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.Thread.run(Thread.java:748)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] Caused by: java.sql.SQLException: Cannot rollback when auto-commit is enabled
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at ru.yandex.clickhouse.ClickHouseConnectionImpl.rollback(ClickHouseConnectionImpl.java:230)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:482)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:482)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:407)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
2022-01-06 10:43:07 [AnalysisStatistics.analysisStatisticsLog-53] 	... 4 common frames omitted`

**Comment by wgzhao** [comment]
应该是同样的问题，我等下修复。
