### ISSUE TITLE
[Bug]: rdbms读取 oracle 错误,但是未捕获

### ISSUE THREAD

**Issue by nmgliangwei** [wgzhao/Addax#508]
### What happened?

oracle 时间类型在 where 条件中 to_date 会报错.但是 addax 未捕获,导致读取数据为 0 程序正常退出.
select * FROM
 db.table where (TO_CHAR(to_date(CREATE_TIME,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd') ='2022-01-14'
CREATE_TIME在 oracle 是时间类型.正常执行这个 sql 会报 ORA-01861: 文字与格式字符串不匹配.
但是 addax 正常执行,未报错,数据条数为 0,程序正常退出.

### Version

4.0.3

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
后续版本已经解决了这个问题，我本次测试结果如下：

```shell
$bin/addax.sh job/oracle2stream.json

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.8-SNAPSHOT)

2022-01-15 21:09:08.794 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-01-15 21:09:08.803 [        main] INFO  Engine               -
{
	"content":{
		"reader":{
			"parameter":{
				"password":"*****",
				"column":[
					"d"
				],
				"where":"to_char(to_date(d,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd') = '2021-12-12'",
				"connection":[
					{
						"jdbcUrl":[
							"jdbc:oracle:thin:@127.0.0.1:1521/XE"
						],
						"table":[
							"t"
						]
					}
				],
				"username":"user"
			},
			"name":"oraclereader"
		},
		"writer":{
			"parameter":{
				"print":true
			},
			"name":"streamwriter"
		}
	},
	"setting":{
		"speed":{
			"bytes":-1,
			"channel":1
		}
	}
}

2022-01-15 21:09:08.821 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-01-15 21:09:08.822 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2022-01-15 21:09:08.823 [        main] INFO  JobContainer         - Set jobId = 0
2022-01-15 21:09:09.668 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:oracle:thin:@127.0.0.1:1521/XE.
2022-01-15 21:09:09.875 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[t] has columns:[D,N].
2022-01-15 21:09:09.878 [       job-0] INFO  JobContainer         - Addax Reader.Job [oraclereader] do prepare work .
2022-01-15 21:09:09.879 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] do prepare work .
2022-01-15 21:09:09.879 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2022-01-15 21:09:09.881 [       job-0] INFO  JobContainer         - Addax Reader.Job [oraclereader] splits to [1] tasks.
2022-01-15 21:09:09.881 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] splits to [1] tasks.
2022-01-15 21:09:09.897 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2022-01-15 21:09:09.905 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2022-01-15 21:09:09.907 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2022-01-15 21:09:09.907 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2022-01-15 21:09:09.916 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select d from t where (to_char(to_date(d,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd') = '2021-12-12')
] jdbcUrl:[jdbc:oracle:thin:@127.0.0.1:1521/XE].
2022-01-15 21:09:09.992 [0-0-0-reader] ERROR ReaderRunner         - Reader runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select d from t where (to_char(to_date(d,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd') = '2021-12-12') 具体错误信息为：java.sql.SQLDataException: ORA-01861: 文字与格式字符串不匹配

	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
	at com.wgzhao.addax.plugin.reader.oraclereader.OracleReader$Task.startRead(OracleReader.java:137)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select d from t where (to_char(to_date(d,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd') = '2021-12-12') 具体错误信息为：java.sql.SQLDataException: ORA-01861: 文字与格式字符串不匹配

	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
	at com.wgzhao.addax.plugin.reader.oraclereader.OracleReader$Task.startRead(OracleReader.java:137)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)
2022-01-15 21:09:12.915 [       job-0] ERROR JobContainer         - 运行scheduler出错.
2022-01-15 21:09:12.916 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select d from t where (to_char(to_date(d,'yyyy-mm-dd hh24:mi:ss'),'yyyy-mm-dd') = '2021-12-12') 具体错误信息为：java.sql.SQLDataException: ORA-01861: 文字与格式字符串不匹配

	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
	at com.wgzhao.addax.plugin.reader.oraclereader.OracleReader$Task.startRead(OracleReader.java:137)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)
$ echo $?
2
```

**Comment by nmgliangwei** [comment]
ok,我想办法把我这边的版本升级到 4.0.8 试试

**Comment by nmgliangwei** [comment]
@wgzhao 我在 release 下载的 4.0.8 测试,不报错. /汗

**Comment by nmgliangwei** [comment]
是v4.0.8-SNAPSHOT 和 v4.0.8 有区别?

**Comment by wgzhao** [comment]
4.0.8-SNAPSHOT 是正在开发的版本
4.0.8 是发行版本。建议按照发行版本测试，如果有问题有问题，我会在下个发行版本中修复。

**Comment by nmgliangwei** [comment]
我测试目前这个issue的问题，在v4.0.8中还是存在的。一样不会报出错误，正常执行。

**Comment by wgzhao** [comment]
好的，我测试下 4.0.8 release 版本

**Comment by nmgliangwei** [comment]
@wgzhao 老板这个有进展吗

**Comment by wgzhao** [comment]
这个在当前 master 分支已经解决，本地没有复现该问题。
