### ISSUE TITLE
[Bug]: hdfs to vertica Invalid parameter index: 27

### ISSUE THREAD

**Issue by nmgliangwei** [wgzhao/Addax#549]
### What happened?

从 hdfs 读取写入vertica,报Invalid parameter index: 27
index 只有 0-25
数据没问题,使用 datax 可以同步进去,并且数据量一致.
json如下:

```json
{
    "job":{
        "content":[
            {
                "reader":{
                    "name":"hdfsreader",
                    "parameter":{
                        "column":[
                            {
                                "index":"0",
                                "type":"string"
                            },
                            {
                                "index":"1",
                                "type":"string"
                            },
                            {
                                "index":"2",
                                "type":"string"
                            },
                            {
                                "index":"3",
                                "type":"string"
                            },
                            {
                                "index":"4",
                                "type":"string"
                            },
                            {
                                "index":"5",
                                "type":"string"
                            },
                            {
                                "index":"6",
                                "type":"string"
                            },
                            {
                                "index":"7",
                                "type":"string"
                            },
                            {
                                "index":"8",
                                "type":"string"
                            },
                            {
                                "index":"9",
                                "type":"string"
                            },
                            {
                                "index":"10",
                                "type":"string"
                            },
                            {
                                "index":"11",
                                "type":"string"
                            },
                            {
                                "index":"12",
                                "type":"string"
                            },
                            {
                                "index":"13",
                                "type":"string"
                            },
                            {
                                "index":"14",
                                "type":"string"
                            },
                            {
                                "index":"15",
                                "type":"string"
                            },
                            {
                                "index":"16",
                                "type":"string"
                            },
                            {
                                "index":"17",
                                "type":"string"
                            },
                            {
                                "index":"18",
                                "type":"string"
                            },
                            {
                                "index":"19",
                                "type":"string"
                            },
                            {
                                "index":"20",
                                "type":"string"
                            },
                            {
                                "index":"21",
                                "type":"string"
                            },
                            {
                                "index":"22",
                                "type":"string"
                            },
                            {
                                "index":"23",
                                "type":"string"
                            },
                            {
                                "index":"24",
                                "type":"string"
                            },
                            {
                                "index":"25",
                                "type":"string"
                            }
                        ],
                        "defaultFS":"hdfs://xxx:8020",
                        "fileType":"text",
                        "fieldDelimiter":"\u0001",
                        "path":"/user/hive/warehouse/src.db/XXX/dt=${v_date}/*"
                    }
                },
                "writer":{
                    "name":"rdbmswriter",
                    "parameter":{
                        "column":[
                            "BATCH_ID",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx",
                            "xxx"
                        ],
                        "connection":[
                            {
                                "jdbcUrl":"jdbc:vertica://xxx",
                                "table":[
                                    "DWA.XXXXXXX"
                                ],
                                "driver":"com.vertica.jdbc.Driver"
                            }
                        ],
                        "password":"",
                        "username":"",
                        "preSql":[
                            "truncate table DWA.XXXXXXX"
                        ]
                    }
                }
            }
        ],
        "setting":{
            "speed":{
                "channel":"4"
            }
        }
    }
}
```
### Version

4.0.3

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell
2022-04-01 17:13:33.598 [0-0-0-writer] WARN  CommonRdbmsWriter$Task - 回滚此次写入, 采用每次写入一行方式提交. 因为: [Vertica][JDBC](10940) Invalid parameter index: 27.
2022-04-01 17:13:33.609 [0-0-0-writer] ERROR StdoutPluginCollector - 
java.sql.SQLException: [Vertica][JDBC](10940) Invalid parameter index: 27.
        at com.vertica.exceptions.ExceptionConverter.toSQLException(Unknown Source)
        at com.vertica.jdbc.common.SPreparedStatement.checkValidParameterIndex(Unknown Source)
        at com.vertica.jdbc.common.SPreparedStatement.setString(Unknown Source)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.setString(DelegatingPreparedStatement.java:616)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.setString(DelegatingPreparedStatement.java:616)
        at com.wgzhao.addax.plugin.reader.rdbmswriter.SubCommonRdbmsWriter$Task.fillPreparedStatementColumnType(SubCommonRdbmsWriter.java:73)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:491)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doOneInsert(CommonRdbmsWriter.java:461)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:440)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:337)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:365)
        at com.wgzhao.addax.plugin.reader.rdbmswriter.RdbmsWriter$Task.startWrite(RdbmsWriter.java:115)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
2022-04-01 17:13:33.616 [0-0-0-writer] ERROR StdoutPluginCollector - 脏数据: {"exception":"[Vertica][JDBC](10940) Invalid parameter index: 27."
```

**Comment by wgzhao** [comment]
确定是 4.0.3 版本？可否使用最新版进行测试？

**Comment by nmgliangwei** [comment]
是 4.0.3 版本,我今天用 4.0.8 版本测试一下看看.

**Comment by nmgliangwei** [comment]
4.0.8版本测试没问题.
