### ISSUE TITLE
[Bug]: impala ldap认证错误

### ISSUE THREAD

**Issue by nmgliangwei** [wgzhao/Addax#550]
### What happened?

impala 采用 ldap 认证后,addax 该如何配置,尝试了几种配置都不行..
json 如下:

```json
{
        "content":[
                {
                        "reader":{
                                "parameter":{
                                        "password":"xxx",
                                        "fetchSize":5000,
                                        "column":[
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx"
                                        ],
                                        "connection":[
                                                {
                                                        "driver":"com.cloudera.impala.jdbc41.Driver",
                                                        "jdbcUrl":[
                                                                "jdbc:impala://impala:21050;AuthMech=3;UID=xxx;PWD=xxx"
                                                        ],
                                                        "table":[
                                                                "xxx"
                                                        ]
                                                }
                                        ],
                                        "where":"dt='{xxx}'",
                                        "username":""
                                },
                                "name":"rdbmsreader"
                        },
                        "writer":{
                                "parameter":{
                                        "password":"xxx",
                                        "column":[
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx",
                                                "xxx"
                                        ],
                                        "connection":[
                                                {
                                                        "driver":"com.vertica.jdbc.Driver",
                                                        "jdbcUrl":"jdbc:vertica://xxx",
                                                        "table":[
                                                                "xxx"
                                                        ]
                                                }
                                        ],
                                        "username":"xxx",
                                        "preSql":[
                                                "truncate table xxx"
                                        ]
                                },
                                "name":"rdbmswriter"
                        }
                }
        ],
        "setting":{
                "speed":{
                        "channel":"4"
                }
        }
}
```

### Version

4.0.3

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell
2022-04-01 18:38:03.811 [0-0-0-reader] ERROR RetryUtil            - Exception when calling callable, 异常Msg:Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot create JDBC driver of class 'com.vertica.jdbc.Driver' for connect URL 'jdbc:impala://impala:21050/src;AuthMech=3;UID=xxx;PWD=xxx'
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.sql.SQLException: Cannot create JDBC driver of class 'com.vertica.jdbc.Driver' for connect URL 'jdbc:impala://impala:21050/src;AuthMech=3;UID=xxx;PWD=xxx'
        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.rdbms.util.RdbmsException.asConnException(RdbmsException.java:61)
        at com.wgzhao.addax.rdbms.util.DBUtil.connect(DBUtil.java:295)
        at com.wgzhao.addax.rdbms.util.DBUtil.lambda$getConnection$2(DBUtil.java:230)
        at com.wgzhao.addax.common.util.RetryUtil$Retry.call(RetryUtil.java:202)
        at com.wgzhao.addax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:147)
        at com.wgzhao.addax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:59)
        at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:230)
        at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:223)
        at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:213)
        at com.wgzhao.addax.plugin.reader.rdbmsreader.RdbmsReader$Task.startRead(RdbmsReader.java:105)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by wgzhao** [comment]
看 json 配置是连接 impala, 但是看日志报错却是  `com.vertica.jdbc.Driver`，请确保驱动是正确的

**Comment by nmgliangwei** [comment]
是的,我也在纳闷这个事,驱动是对的,是不是和使用 2 个 rdms 有关系,一个rdbmsreader 一个rdbmswriter?

**Comment by wgzhao** [comment]
你看下 rdbmsreader 插件的 libs 目录下有几个驱动，尝试只保留 impala 的驱动，其他都删除试下
