### ISSUE TITLE
[Bug]: excelreader报错

### ISSUE THREAD

**Issue by zhbdesign** [wgzhao/Addax#552]
### What happened?

```
$ python bin/addax.py job/excel_record.json
▒▒▒▒▒ҳ: 936

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.8)

2022-04-08 14:39:02.349 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-04-08 14:39:02.364 [        main] INFO  Engine               -
{
        "content":{
                "reader":{
                        "parameter":{
                                "path":[
                                        "data/demo.xlsx"
                                ],
                                "skipRows":0,
                                "header":true
                        },
                        "name":"excelreader"
                },
                "writer":{
                        "parameter":{
                                "password":"*****",
                                "column":[
                                        "*"
                                ],
                                "connection":[
                                        {
                                                "driver":"com.mysql.jdbc.Driver",
                                                "jdbcUrl":"jdbc:mysql://10.100.2.53:3306/xs_dcl?useSSL=false",
                                                "table":[
                                                        "tax_sb_zzs_xgm_1"
                                                ]
                                        }
                                ],
                                "writeMode":"insert",
                                "username":"root",
                                "preSql":[
                                        ""
                                ]
                        },
                        "name":"mysqlwriter"
                }
        },
        "setting":{
                "speed":{
                        "bytes":-1,
                        "channel":1
                }
        }
}

2022-04-08 14:39:02.380 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-04-08 14:39:02.380 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2022-04-08 14:39:02.380 [        main] INFO  JobContainer         - Set jobId = 0
2022-04-08 14:39:02.395 [       job-0] INFO  FileHelper           - add file [data/demo.xlsx] as a candidate to be read.
2022-04-08 14:39:02.395 [       job-0] INFO  ExcelReader$Job      - The number of files to read is: [1]
2022-04-08 14:39:02.395 [       job-0] WARN  OriginalConfPretreatmentUtil - use specified driver class: com.mysql.jdbc.Driver
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2022-04-08 14:39:02.692 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[tax_sb_zzs_xgm_1] all columns:[id,bat_id,uuid,pzxh,sbuuid,ewblxh,lmc,yzzzsbhsxse,swjgdkdzzszyfpbhsxse,skqjkjdptfpbhsxse_1,xssygdysgdzcbhsxse,skqjkjdptfpbhsxse,msxse,skqjkjdptfpxse,ckmsxse,skqjkjdptfpxse_1,bqynse,bqynsejze,ynsehj,bqyjse_1,bqybtse,lrr_dm,lrrq,xgr_dm,xgrq,sjgsdq,sjtb_sj,xwqymsxse,wdqzdxse,qtmsxse,bqmse,xwqymse,wdqzdmse,hdxse,hdynse,xsczbdcbhsxse,swjgdkdzzszyfpbhsxse1,skqjkjdptfpbhsxse2,sjblbz,bdcxse,create_time,modified_time,type].
2022-04-08 14:39:02.692 [       job-0] WARN  OriginalConfPretreatmentUtil - ▒▒▒▒▒▒▒▒▒ļ▒▒е▒▒▒▒▒▒▒▒▒Ϣ▒▒▒ڷ▒▒▒. ▒▒Ϊ▒▒▒▒▒õ▒д▒▒▒▒▒ݿ▒▒▒▒▒Ϊ*▒▒▒▒▒▒▒ı▒▒ֶθ▒▒▒▒▒▒▒▒▒▒б䶯ʱ▒▒▒▒▒▒Ӱ▒▒▒▒▒▒▒▒ȷ▒▒▒▒▒▒▒▒▒▒▒г▒▒▒▒▒▒▒▒▒▒▒▒▒ò▒▒▒▒▒▒޸▒.
2022-04-08 14:39:02.692 [       job-0] INFO  OriginalConfPretreatmentUtil - Write data [insert INTO %s ( id,bat_id,uuid,pzxh,sbuuid,ewblxh,lmc,yzzzsbhsxse,swjgdkdzzszyfpbhsxse,skqjkjdptfpbhsxse_1,xssygdysgdzcbhsxse,skqjkjdptfpbhsxse,msxse,skqjkjdptfpxse,ckmsxse,skqjkjdptfpxse_1,bqynse,bqynsejze,ynsehj,bqyjse_1,bqybtse,lrr_dm,lrrq,xgr_dm,xgrq,sjgsdq,sjtb_sj,xwqymsxse,wdqzdxse,qtmsxse,bqmse,xwqymse,wdqzdmse,hdxse,hdynse,xsczbdcbhsxse,swjgdkdzzszyfpbhsxse1,skqjkjdptfpbhsxse2,sjblbz,bdcxse,create_time,modified_time,type) VALUES ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? )], which jdbcUrl [jdbc:mysql://10.100.2.53:3306/xs_dcl?useSSL=false&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&tinyInt1isBit=false]
2022-04-08 14:39:02.692 [       job-0] INFO  JobContainer         - Addax Reader.Job [excelreader] do prepare work .
2022-04-08 14:39:02.692 [       job-0] INFO  JobContainer         - Addax Writer.Job [mysqlwriter] do prepare work .
2022-04-08 14:39:02.692 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2022-04-08 14:39:02.692 [       job-0] INFO  JobContainer         - Addax Reader.Job [excelreader] splits to [1] tasks.
2022-04-08 14:39:02.692 [       job-0] INFO  JobContainer         - Addax Writer.Job [mysqlwriter] splits to [1] tasks.
2022-04-08 14:39:02.708 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2022-04-08 14:39:02.724 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2022-04-08 14:39:02.724 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2022-04-08 14:39:02.724 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2022-04-08 14:39:02.739 [0-0-0-reader] INFO  ExcelReader$Task     - The first row is skipped as a table header
2022-04-08 14:39:02.739 [0-0-0-reader] INFO  ExcelReader$Task     - begin read file data/demo.xlsx
2022-04-08 14:39:02.755 [0-0-0-reader] ERROR ReaderRunner         - Reader runner Received Exceptions:
java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 common frames omitted
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-13], Description:[Addax ▒▒▒▒▒▒▒ʱ▒▒▒▒, ▒▒▒▒ԭ▒▒▒▒ο▒Addax ▒▒▒н▒▒▒ʱ▒Ĵ▒▒▒▒▒▒▒▒Ϣ .].  - java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
 - java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:211)
        at com.wgzhao.addax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
2022-04-08 14:39:05.739 [       job-0] ERROR JobContainer         - ▒▒▒▒scheduler▒▒▒▒.
2022-04-08 14:39:05.739 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-13], Description:[Addax ▒▒▒▒▒▒▒ʱ▒▒▒▒, ▒▒▒▒ԭ▒▒▒▒ο▒Addax ▒▒▒н▒▒▒ʱ▒Ĵ▒▒▒▒▒▒▒▒Ϣ .].  - java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
 - java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:63)
        at com.wgzhao.addax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:121)
        at com.wgzhao.addax.core.job.JobContainer.schedule(JobContainer.java:493)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:137)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)
```

### Version

4.0.8 (Default)

### OS Type

Windows

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell
$ python bin/addax.py job/excel_record.json
▒▒▒▒▒ҳ: 936

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.8)

2022-04-08 14:39:02.349 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-04-08 14:39:02.364 [        main] INFO  Engine               -
{
        "content":{
                "reader":{
                        "parameter":{
                                "path":[
                                        "data/demo.xlsx"
                                ],
                                "skipRows":0,
                                "header":true
                        },
                        "name":"excelreader"
                },
                "writer":{
                        "parameter":{
                                "password":"*****",
                                "column":[
                                        "*"
                                ],
                                "connection":[
                                        {
                                                "driver":"com.mysql.jdbc.Driver",
                                                "jdbcUrl":"jdbc:mysql://10.100.2.53:3306/xs_dcl?useSSL=false",
                                                "table":[
                                                        "tax_sb_zzs_xgm_1"
                                                ]
                                        }
                                ],
                                "writeMode":"insert",
                                "username":"root",
                                "preSql":[
                                        ""
                                ]
                        },
                        "name":"mysqlwriter"
                }
        },
        "setting":{
                "speed":{
                        "bytes":-1,
                        "channel":1
                }
        }
}

2022-04-08 14:39:02.380 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-04-08 14:39:02.380 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2022-04-08 14:39:02.380 [        main] INFO  JobContainer         - Set jobId = 0
2022-04-08 14:39:02.395 [       job-0] INFO  FileHelper           - add file [data/demo.xlsx] as a candidate to be read.
2022-04-08 14:39:02.395 [       job-0] INFO  ExcelReader$Job      - The number of files to read is: [1]
2022-04-08 14:39:02.395 [       job-0] WARN  OriginalConfPretreatmentUtil - use specified driver class: com.mysql.jdbc.Driver
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2022-04-08 14:39:02.692 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[tax_sb_zzs_xgm_1] all columns:[id,bat_id,uuid,pzxh,sbuuid,ewblxh,lmc,yzzzsbhsxse,swjgdkdzzszyfpbhsxse,skqjkjdptfpbhsxse_1,xssygdysgdzcbhsxse,skqjkjdptfpbhsxse,msxse,skqjkjdptfpxse,ckmsxse,skqjkjdptfpxse_1,bqynse,bqynsejze,ynsehj,bqyjse_1,bqybtse,lrr_dm,lrrq,xgr_dm,xgrq,sjgsdq,sjtb_sj,xwqymsxse,wdqzdxse,qtmsxse,bqmse,xwqymse,wdqzdmse,hdxse,hdynse,xsczbdcbhsxse,swjgdkdzzszyfpbhsxse1,skqjkjdptfpbhsxse2,sjblbz,bdcxse,create_time,modified_time,type].
2022-04-08 14:39:02.692 [       job-0] WARN  OriginalConfPretreatmentUtil - ▒▒▒▒▒▒▒▒▒ļ▒▒е▒▒▒▒▒▒▒▒▒Ϣ▒▒▒ڷ▒▒▒. ▒▒Ϊ▒▒▒▒▒õ▒д▒▒▒▒▒ݿ▒▒▒▒▒Ϊ*▒▒▒▒▒▒▒ı▒▒ֶθ▒▒▒▒▒▒▒▒▒▒б䶯ʱ▒▒▒▒▒▒Ӱ▒▒▒▒▒▒▒▒ȷ▒▒▒▒▒▒▒▒▒▒▒г▒▒▒▒▒▒▒▒▒▒▒▒▒ò▒▒▒▒▒▒޸▒.
2022-04-08 14:39:02.692 [       job-0] INFO  OriginalConfPretreatmentUtil - Write data [insert INTO %s ( id,bat_id,uuid,pzxh,sbuuid,ewblxh,lmc,yzzzsbhsxse,swjgdkdzzszyfpbhsxse,skqjkjdptfpbhsxse_1,xssygdysgdzcbhsxse,skqjkjdptfpbhsxse,msxse,skqjkjdptfpxse,ckmsxse,skqjkjdptfpxse_1,bqynse,bqynsejze,ynsehj,bqyjse_1,bqybtse,lrr_dm,lrrq,xgr_dm,xgrq,sjgsdq,sjtb_sj,xwqymsxse,wdqzdxse,qtmsxse,bqmse,xwqymse,wdqzdmse,hdxse,hdynse,xsczbdcbhsxse,swjgdkdzzszyfpbhsxse1,skqjkjdptfpbhsxse2,sjblbz,bdcxse,create_time,modified_time,type) VALUES ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? )], which jdbcUrl [jdbc:mysql://10.100.2.53:3306/xs_dcl?useSSL=false&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&tinyInt1isBit=false]
2022-04-08 14:39:02.692 [       job-0] INFO  JobContainer         - Addax Reader.Job [excelreader] do prepare work .
2022-04-08 14:39:02.692 [       job-0] INFO  JobContainer         - Addax Writer.Job [mysqlwriter] do prepare work .
2022-04-08 14:39:02.692 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2022-04-08 14:39:02.692 [       job-0] INFO  JobContainer         - Addax Reader.Job [excelreader] splits to [1] tasks.
2022-04-08 14:39:02.692 [       job-0] INFO  JobContainer         - Addax Writer.Job [mysqlwriter] splits to [1] tasks.
2022-04-08 14:39:02.708 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2022-04-08 14:39:02.724 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2022-04-08 14:39:02.724 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2022-04-08 14:39:02.724 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2022-04-08 14:39:02.739 [0-0-0-reader] INFO  ExcelReader$Task     - The first row is skipped as a table header
2022-04-08 14:39:02.739 [0-0-0-reader] INFO  ExcelReader$Task     - begin read file data/demo.xlsx
2022-04-08 14:39:02.755 [0-0-0-reader] ERROR ReaderRunner         - Reader runner Received Exceptions:
java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 common frames omitted
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-13], Description:[Addax ▒▒▒▒▒▒▒ʱ▒▒▒▒, ▒▒▒▒ԭ▒▒▒▒ο▒Addax ▒▒▒н▒▒▒ʱ▒Ĵ▒▒▒▒▒▒▒▒Ϣ .].  - java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
 - java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:211)
        at com.wgzhao.addax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
2022-04-08 14:39:05.739 [       job-0] ERROR JobContainer         - ▒▒▒▒scheduler▒▒▒▒.
2022-04-08 14:39:05.739 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-13], Description:[Addax ▒▒▒▒▒▒▒ʱ▒▒▒▒, ▒▒▒▒ԭ▒▒▒▒ο▒Addax ▒▒▒н▒▒▒ʱ▒Ĵ▒▒▒▒▒▒▒▒Ϣ .].  - java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
 - java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Workbook
        at com.wgzhao.addax.plugin.reader.excelreader.ExcelReader$Task.startRead(ExcelReader.java:148)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Workbook
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:63)
        at com.wgzhao.addax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:121)
        at com.wgzhao.addax.core.job.JobContainer.schedule(JobContainer.java:493)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:137)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)
```

**Comment by wgzhao** [comment]
我本地测试 4.0.8 版本暂时没有发现缺失 class 的问题。缺失的 `org.apache.poi.ss.usermodel.Workbook` 类是在 `shared/poi-ooxml-5.1.0.jar` 和 `shared/poi-5.1.0.jar` 文件中。

1. 确认看下你的是否缺失这两个文件
2. 如果缺失，方便的话，能否提供你读取的excel，我看是否有特别的地方。

**Comment by zhbdesign** [comment]
换了4.0.5，4.0.6，也是同样的问题，都是在release里下载的打包好的，都是用的online里的demo.xlsx，都是同样的错误

**Comment by wgzhao** [comment]
[poi.zip](https://github.com/wgzhao/Addax/files/8456405/poi.zip)
你把附件中的压缩文件解压后，把三个jar文件替换 `shared` 目录下的同名文件试下，我从release重新下载测试下

**Comment by zhbdesign** [comment]
我测试一下，你那边测试完反馈下，谢谢

**Comment by wgzhao** [comment]
刚从 releases 页面下载了 4.0.8 版本，并使用文档中提供的 demo.xml 文件进行测试，没有异常。

结果如下：

```
bin/addax.sh excel2stream.json

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.8)

2022-04-09 14:57:33.837 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-04-09 14:57:33.852 [        main] INFO  Engine               -
{
	"content":{
		"reader":{
			"parameter":{
				"path":[
					"/tmp/demo.xlsx"
				],
				"skipRows":0,
				"header":true
			},
			"name":"excelreader"
		},
		"writer":{
			"parameter":{
				"print":true
			},
			"name":"streamwriter"
		}
	},
	"setting":{
		"speed":{
			"bytes":-1,
			"channel":2
		}
	}
}

2022-04-09 14:57:33.884 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-04-09 14:57:33.885 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2022-04-09 14:57:33.886 [        main] INFO  JobContainer         - Set jobId = 0
2022-04-09 14:57:33.929 [       job-0] INFO  FileHelper           - add file [/tmp/demo.xlsx] as a candidate to be read.
2022-04-09 14:57:33.929 [       job-0] INFO  ExcelReader$Job      - The number of files to read is: [1]
2022-04-09 14:57:33.934 [       job-0] INFO  JobContainer         - Addax Reader.Job [excelreader] do prepare work .
2022-04-09 14:57:33.934 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] do prepare work .
2022-04-09 14:57:33.934 [       job-0] INFO  JobContainer         - Job set Channel-Number to 2 channel(s).
2022-04-09 14:57:33.935 [       job-0] INFO  JobContainer         - Addax Reader.Job [excelreader] splits to [1] tasks.
2022-04-09 14:57:33.935 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] splits to [1] tasks.
2022-04-09 14:57:33.979 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2022-04-09 14:57:34.002 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2022-04-09 14:57:34.029 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2022-04-09 14:57:34.029 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2022-04-09 14:57:34.046 [0-0-0-reader] INFO  ExcelReader$Task     - The first row is skipped as a table header
2022-04-09 14:57:34.047 [0-0-0-reader] INFO  ExcelReader$Task     - begin read file /tmp/demo.xlsx
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
1	11	1102.234	Addax加上中文	2021-09-10 00:00:00	5544.17	1102.234
2	12	1103.234	Addax加上中文	2021-09-11 00:00:00	5552.17	1103.234
3	13	1104.234	Addax加上中文	2021-09-12 00:00:00	5560.17	1104.234
4	14	1105.234	Addax加上中文	2021-09-13 00:00:00	5568.17	1105.234
5	15	1106.234	Addax加上中文	2021-09-14 00:00:00	5576.17	1106.234
6	16	1107.234	Addax加上中文	2021-09-15 00:00:00	5584.17	1107.234
7	17	1108.234	Addax加上中文	2021-09-16 00:00:00	5592.17	1108.234
8	18	1109.234	Addax加上中文	2021-09-17 00:00:00	5600.17	1109.234
9	19	1110.234	Addax加上中文	2021-09-18 00:00:00	5608.17	1110.234
10	20	1111.234	Addax加上中文	2021-09-19 00:00:00	5616.17	1111.234
11	21	1112.234	Addax加上中文	2021-09-20 00:00:00	5624.17	1112.234
12	22	1113.234	Addax加上中文	2021-09-21 00:00:00	5632.17	1113.234
13	23	1114.234	Addax加上中文	2021-09-22 00:00:00	5640.17	1114.234
14	24	1115.234	Addax加上中文	2021-09-23 00:00:00	5648.17	1115.234
15	25	1116.234	Addax加上中文	2021-09-24 00:00:00	5656.17	1116.234
16	26	1117.234	Addax加上中文	2021-09-25 00:00:00	5664.17	1117.234
17	27	1118.234	Addax加上中文	2021-09-26 00:00:00	5672.17	1118.234
18	28	1119.234	Addax加上中文	2021-09-27 00:00:00	5680.17	1119.234
19	29	1120.234	Addax加上中文	2021-09-28 00:00:00	5688.17	1120.234
20	30	1121.234	Addax加上中文	2021-09-29 00:00:00	5696.17	1121.234
2022-04-09 14:57:37.046 [       job-0] INFO  AbstractScheduler    - Scheduler accomplished all tasks.
2022-04-09 14:57:37.046 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] do post work.
2022-04-09 14:57:37.047 [       job-0] INFO  JobContainer         - Addax Reader.Job [excelreader] do post work.
2022-04-09 14:57:37.048 [       job-0] INFO  JobContainer         - PerfTrace not enable!
2022-04-09 14:57:37.049 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 20 records, 1120 bytes | Speed 373B/s, 6 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2022-04-09 14:57:37.049 [       job-0] INFO  JobContainer         -
任务启动时刻                    : 2022-04-09 14:57:33
任务结束时刻                    : 2022-04-09 14:57:37
任务总计耗时                    :                  3s
任务平均流量                    :              373B/s
记录写入速度                    :              6rec/s
读出记录总数                    :                  20
读写失败总数                    :                   0
```

**Comment by wgzhao** [comment]
addax.sh 只能用于 Linux 环境， Windows 下都应的 addax.bat 我还没有写

**Comment by zhbdesign** [comment]
windows用addax.py也不行，一样的错误，要不你测试下

**Comment by wgzhao** [comment]
我还得想办法找一台有windows系统的设备，可能要晚一点。
