### ISSUE TITLE
[Bug]: NoSuchMethodError: com.google.common.base.Preconditions.checkState

### ISSUE THREAD

**Issue by lschampion** [wgzhao/Addax#569]
### Contact Details（联系人）

911lisa@163.com

### What happened?

hbase with kerberos  error, and hbase version 2.1.0 using pluign hbase11xwriter.

### Version

4.0.7

### OS Type

Linux (Default)

### Java JDK Version

open JDK 1.8.0

### Relevant log output

```shell
[root@localhost addax-4.0.7-origin]# bin/addax.sh ../addax-myjobs/addax_test_pg2hbase.json 

  ___      _     _            
 / _ \    | |   | |           
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  < 
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.7)

2022-05-09 14:32:30.984 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-05-09 14:32:30.992 [        main] INFO  Engine               - 
{
	"content":{
		"reader":{
			"parameter":{
				"password":"*****",
				"fetchSize":2048,
				"autoPk":false,
				"column":[
					"kind",
					"code",
					"detail"
				],
				"connection":[
					{
						"jdbcUrl":[
							"jdbc:postgresql://180.1.1.22:25308/test_data?sslmode=disable"
						],
						"table":[
							"newimportdata.xt_zdb"
						]
					}
				],
				"where":"",
				"splitPk":"kind",
				"username":"root"
			},
			"name":"postgresqlreader"
		},
		"writer":{
			"parameter":{
				"mode":"normal",
				"haveKerberos":"true",
				"kerberosKeytabFilePath":"/opt/bigdata/KrbClient/keytab/hbaseadmin.keytab",
				"kerberosKrb5Conf":"/etc/krb5.conf",
				"rowkeyColumn":[
					{
						"name":"autogen_main_record_id",
						"index":0,
						"type":"string"
					}
				],
				"column":[
					{
						"name":"c1:kind",
						"index":0,
						"type":"string"
					},
					{
						"name":"c1:code",
						"index":1,
						"type":"string"
					},
					{
						"name":"c1:detail",
						"index":2,
						"type":"string"
					}
				],
				"encoding":"UTF-8",
				"kerberosPrincipal":"hbaseadmin@YMHADOOP.COM",
				"table":"TEST:TEST_ADDAX_PG2HBASE",
				"hbaseConfig":{
					"hbase.zookeeper.quorum":"192.168.100.100",
					"zookeeper.znode.parent":"/hbase-secure",
					"hbase.rootdir":"/apps/hbase/data",
					"hbase.cluster.distributed":"true"
				}
			},
			"name":"hbase11xwriter"
		}
	},
	"setting":{
		"speed":{
			"bytes":-1,
			"channel":1
		}
	}
}

2022-05-09 14:32:31.007 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-05-09 14:32:31.007 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2022-05-09 14:32:31.008 [        main] INFO  JobContainer         - Set jobId = 0
2022-05-09 14:32:31.474 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:postgresql://180.1.1.22:25308/test_data?sslmode=disable.
2022-05-09 14:32:31.873 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[newimportdata.xt_zdb] has columns:[kind,code,detail].
2022-05-09 14:32:32.232 [       job-0] INFO  JobContainer         - Addax Reader.Job [postgresqlreader] do prepare work .
2022-05-09 14:32:32.233 [       job-0] INFO  JobContainer         - Addax Writer.Job [hbase11xwriter] do prepare work .
2022-05-09 14:32:32.233 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2022-05-09 14:32:32.235 [       job-0] INFO  JobContainer         - Addax Reader.Job [postgresqlreader] splits to [1] tasks.
2022-05-09 14:32:32.235 [       job-0] INFO  JobContainer         - Addax Writer.Job [hbase11xwriter] splits to [1] tasks.
2022-05-09 14:32:32.307 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2022-05-09 14:32:32.319 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2022-05-09 14:32:32.323 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2022-05-09 14:32:32.323 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2022-05-09 14:32:32.338 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select autogen_main_record_id,kind,code,detail from newimportdata.xt_zdb 
] jdbcUrl:[jdbc:postgresql://180.1.1.22:25308/test_data?sslmode=disable].
2022-05-09 14:32:32.374 [0-0-0-writer] ERROR WriterRunner         - Writer Runner Received Exceptions:
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;J)V
	at com.google.common.cache.CacheBuilder.refreshAfterWrite(CacheBuilder.java:841)
	at org.apache.hadoop.hbase.security.UserProvider.setConf(UserProvider.java:72)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:77)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
	at org.apache.hadoop.hbase.security.UserProvider.instantiate(UserProvider.java:124)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:214)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getHbaseConnection(Hbase11xHelper.java:82)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getBufferedMutator(Hbase11xHelper.java:122)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.HbaseAbstractTask.<init>(HbaseAbstractTask.java:65)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.NormalTask.<init>(NormalTask.java:47)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xWriter$Task.init(Hbase11xWriter.java:89)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:69)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-13], Description:[Addax 插件运行时出错, 具体原因请参看Addax 运行结束时的错误诊断信息 .].  - java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;J)V
	at com.google.common.cache.CacheBuilder.refreshAfterWrite(CacheBuilder.java:841)
	at org.apache.hadoop.hbase.security.UserProvider.setConf(UserProvider.java:72)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:77)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
	at org.apache.hadoop.hbase.security.UserProvider.instantiate(UserProvider.java:124)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:214)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getHbaseConnection(Hbase11xHelper.java:82)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getBufferedMutator(Hbase11xHelper.java:122)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.HbaseAbstractTask.<init>(HbaseAbstractTask.java:65)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.NormalTask.<init>(NormalTask.java:47)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xWriter$Task.init(Hbase11xWriter.java:89)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:69)
	at java.lang.Thread.run(Thread.java:748)
 - java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;J)V
	at com.google.common.cache.CacheBuilder.refreshAfterWrite(CacheBuilder.java:841)
	at org.apache.hadoop.hbase.security.UserProvider.setConf(UserProvider.java:72)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:77)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
	at org.apache.hadoop.hbase.security.UserProvider.instantiate(UserProvider.java:124)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:214)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getHbaseConnection(Hbase11xHelper.java:82)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getBufferedMutator(Hbase11xHelper.java:122)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.HbaseAbstractTask.<init>(HbaseAbstractTask.java:65)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.NormalTask.<init>(NormalTask.java:47)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xWriter$Task.init(Hbase11xWriter.java:89)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:69)
	at java.lang.Thread.run(Thread.java:748)

	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
	at com.wgzhao.addax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:211)
	at com.wgzhao.addax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;J)V
	at com.google.common.cache.CacheBuilder.refreshAfterWrite(CacheBuilder.java:841)
	at org.apache.hadoop.hbase.security.UserProvider.setConf(UserProvider.java:72)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:77)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
	at org.apache.hadoop.hbase.security.UserProvider.instantiate(UserProvider.java:124)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:214)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getHbaseConnection(Hbase11xHelper.java:82)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getBufferedMutator(Hbase11xHelper.java:122)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.HbaseAbstractTask.<init>(HbaseAbstractTask.java:65)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.NormalTask.<init>(NormalTask.java:47)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xWriter$Task.init(Hbase11xWriter.java:89)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:69)
	... 1 more
2022-05-09 14:32:35.327 [       job-0] ERROR JobContainer         - 运行scheduler出错.
2022-05-09 14:32:35.329 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-13], Description:[Addax 插件运行时出错, 具体原因请参看Addax 运行结束时的错误诊断信息 .].  - java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;J)V
	at com.google.common.cache.CacheBuilder.refreshAfterWrite(CacheBuilder.java:841)
	at org.apache.hadoop.hbase.security.UserProvider.setConf(UserProvider.java:72)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:77)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
	at org.apache.hadoop.hbase.security.UserProvider.instantiate(UserProvider.java:124)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:214)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getHbaseConnection(Hbase11xHelper.java:82)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getBufferedMutator(Hbase11xHelper.java:122)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.HbaseAbstractTask.<init>(HbaseAbstractTask.java:65)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.NormalTask.<init>(NormalTask.java:47)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xWriter$Task.init(Hbase11xWriter.java:89)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:69)
	at java.lang.Thread.run(Thread.java:748)
 - java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;J)V
	at com.google.common.cache.CacheBuilder.refreshAfterWrite(CacheBuilder.java:841)
	at org.apache.hadoop.hbase.security.UserProvider.setConf(UserProvider.java:72)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:77)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
	at org.apache.hadoop.hbase.security.UserProvider.instantiate(UserProvider.java:124)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:214)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getHbaseConnection(Hbase11xHelper.java:82)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getBufferedMutator(Hbase11xHelper.java:122)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.HbaseAbstractTask.<init>(HbaseAbstractTask.java:65)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.NormalTask.<init>(NormalTask.java:47)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xWriter$Task.init(Hbase11xWriter.java:89)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:69)
	at java.lang.Thread.run(Thread.java:748)

	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
	at com.wgzhao.addax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:63)
	at com.wgzhao.addax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:121)
	at com.wgzhao.addax.core.job.JobContainer.schedule(JobContainer.java:492)
	at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:136)
	at com.wgzhao.addax.core.Engine.start(Engine.java:75)
	at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
	at com.wgzhao.addax.core.Engine.main(Engine.java:163)
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;J)V
	at com.google.common.cache.CacheBuilder.refreshAfterWrite(CacheBuilder.java:841)
	at org.apache.hadoop.hbase.security.UserProvider.setConf(UserProvider.java:72)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:77)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:137)
	at org.apache.hadoop.hbase.security.UserProvider.instantiate(UserProvider.java:124)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:214)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getHbaseConnection(Hbase11xHelper.java:82)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xHelper.getBufferedMutator(Hbase11xHelper.java:122)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.HbaseAbstractTask.<init>(HbaseAbstractTask.java:65)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.NormalTask.<init>(NormalTask.java:47)
	at com.wgzhao.addax.plugin.writer.hbase11xwriter.Hbase11xWriter$Task.init(Hbase11xWriter.java:89)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:69)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wgzhao** [comment]
这应该是 guava 版本不兼容的问题

**Comment by wgzhao** [comment]
请尝试升级到 4.0.8 版本测试
