### ISSUE TITLE
[Bug]: 使用starrocks官方提供的DataX Writer插件报错

### ISSUE THREAD

**Issue by imzhf** [wgzhao/Addax#575]
### What happened?

1、下载starrocks官方提供的writer插件
https://github.com/StarRocks/DataX/releases
2、解压到addax的writer目录下
3、运行任务报错：
com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-02], Description:[Addax 引擎运行过程出错，具体原因请参看Addax 运行结束时的错误诊断信息  .].  - 找到plugin[starrockswriter]的Job配置. - java.lang.ClassCastException: com.starrocks.connector.datax.plugin.writer.starrockswriter.StarRocksWriter$Job cannot be cast to com.wgzhao.addax.common.plugin.AbstractJobPlugin
	at com.wgzhao.addax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:105)
	at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:637)
	at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:311)
	at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:131)
	at com.wgzhao.addax.core.Engine.start(Engine.java:75)
	at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
	at com.wgzhao.addax.core.Engine.main(Engine.java:163)

	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:58)
	at com.wgzhao.addax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:110)
	at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:637)
	at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:311)
	at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:131)
	at com.wgzhao.addax.core.Engine.start(Engine.java:75)
	at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
	at com.wgzhao.addax.core.Engine.main(Engine.java:163)
Caused by: java.lang.ClassCastException: com.starrocks.connector.datax.plugin.writer.starrockswriter.StarRocksWriter$Job cannot be cast to com.wgzhao.addax.common.plugin.AbstractJobPlugin
	at com.wgzhao.addax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil.java:105)
	... 6 more

### Version

4.0.8 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
官方的插件应该是基于 DataX 来开发的，目前 Addax 并不和 DataX 兼容
可以把官方提供的插件进行改造

**Comment by imdevboy** [comment]
能简单说下怎么做兼容性改造吗？

**Comment by wgzhao** [comment]
改动比较多，我先尝试下

**Comment by wgzhao** [comment]
另外，这个 starrocks 和 [Doris](http://doris.incubator.apache.org/) 到底是什么关系？之前也有人提到需要 Starrocks的writer 插件，但是我从官方的文档来看，他应该是完全兼容 Doriswriter的。

**Comment by imdevboy** [comment]
看下这篇文章，有详细的介绍：
https://mq.mbd.baidu.com/r/GVTGq3ATq8?f=cp&u=05c36de10b81b657

**Comment by imdevboy** [comment]
这一年来，starrocks发展很快，性能比Apache doris有明显的进步，有不少公司已使用该产品

**Comment by imdevboy** [comment]
> 另外，这个 starrocks 和 [Doris](http://doris.incubator.apache.org/) 到底是什么关系？之前也有人提到需要 Starrocks的writer 插件，但是我从官方的文档来看，他应该是完全兼容 Doriswriter的。

两者同源，但去年已分道扬镳

**Comment by wgzhao** [comment]
[starrockswriter-4.0.9.zip](https://github.com/wgzhao/Addax/files/8798200/starrockswriter-4.0.9.zip)
这是刚编译出来的插件，不过我还没有来得及测试，因为我暂时还没有部署环境
如果你愿意的话，可以测试测试看看。

**Comment by imdevboy** [comment]
好的，我有环境，我明天测下

**Comment by imdevboy** [comment]
> [starrockswriter-4.0.9.zip](https://github.com/wgzhao/Addax/files/8798200/starrockswriter-4.0.9.zip) 这是刚编译出来的插件，不过我还没有来得及测试，因为我暂时还没有部署环境 如果你愿意的话，可以测试测试看看。

我有8张表，同步成功了6张表，有2张表失败，失败原因相同，是因为执行配置文件中"preSql"中的truncate table语句失败：
2022-05-31 13:54:50.356 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: truncate table dwd.dwd_agent 具体错误信息为：java.sql.SQLException: Can not issue data manipulation statements with executeQuery().
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.plugin.writer.starrockswriter.util.StarRocksWriterUtil.executeSqls(StarRocksWriterUtil.java:75)
	at com.wgzhao.addax.plugin.writer.starrockswriter.StarRocksWriter$Job.prepare(StarRocksWriter.java:60)
	at com.wgzhao.addax.core.job.JobContainer.prepareJobWriter(JobContainer.java:665)
	at com.wgzhao.addax.core.job.JobContainer.prepare(JobContainer.java:317)
	at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:133)
	at com.wgzhao.addax.core.Engine.start(Engine.java:75)
	at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
	at com.wgzhao.addax.core.Engine.main(Engine.java:163)
![addax](https://user-images.githubusercontent.com/3370207/171103529-d9fa7969-9038-4014-91fb-79e2f985395a.png)

**Comment by imdevboy** [comment]
starrocks的配置脚本中是允许

**Comment by wgzhao** [comment]
好的，晚上我尝试修复下

**Comment by wgzhao** [comment]
麻烦下载 [starrockswriter-4.0.9-SNAPSHOT.jar.zip](https://github.com/wgzhao/Addax/files/8805113/starrockswriter-4.0.9-SNAPSHOT.jar.zip) ，并解压后覆盖当前 `plugin/writer/starrockswriter` 目录下对应的 jar 文件。
然后进行测试，谢谢！

**Comment by imdevboy** [comment]
好的，我明天更新后，再测一遍

**Comment by imzhf** [comment]
> 麻烦下载 [starrockswriter-4.0.9-SNAPSHOT.jar.zip](https://github.com/wgzhao/Addax/files/8805113/starrockswriter-4.0.9-SNAPSHOT.jar.zip) ，并解压后覆盖当前 `plugin/writer/starrockswriter` 目录下对应的 jar 文件。 然后进行测试，谢谢！

可以正常执行了：

**Comment by wgzhao** [comment]
感谢！
