### ISSUE TITLE
[Bug]: 数据量较多时，kafka写入报错

### ISSUE THREAD

**Issue by imzhf** [wgzhao/Addax#579]
### What happened?

数据量较多时，kafka写入报错：
2022-06-01 17:34:34.790 [kafka-producer-network-thread | addax-kafka-writer] ERROR ProducerBatch        - Error executing user-provided callback on message for topic-partition 'db_marketing-0'
com.wgzhao.addax.common.exception.AddaxException: PUT_KAFKA_ERROR - org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for db_marketing-0: 30003 ms has passed since last append
 - org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for db_marketing-0: 30003 ms has passed since last append

	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
	at com.wgzhao.addax.plugin.writer.kafkawriter.KafkaWriter$Task.lambda$startWrite$1(KafkaWriter.java:190)
	at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion(KafkaProducer.java:1235)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:204)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:187)
	at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:635)
	at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:290)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:238)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for db_marketing-0: 30003 ms has passed since last append
2022-06-01 17:34:34.790 [kafka-producer-network-thread | addax-kafka-writer] ERROR ProducerBatch        - Error executing user-provided callback on message for topic-partition 'db_marketing-0'
com.wgzhao.addax.common.exception.AddaxException: PUT_KAFKA_ERROR - org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for db_marketing-0: 30002 ms has passed since last append
 - org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for db_marketing-0: 30002 ms has passed since last append

	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
	at com.wgzhao.addax.plugin.writer.kafkawriter.KafkaWriter$Task.lambda$startWrite$1(KafkaWriter.java:190)
	at org.apache.kafka.clients.producer.KafkaProducer$InterceptorCallback.onCompletion(KafkaProducer.java:1235)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.completeFutureAndFireCallbacks(ProducerBatch.java:204)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.done(ProducerBatch.java:187)
	at org.apache.kafka.clients.producer.internals.Sender.failBatch(Sender.java:635)
	at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:290)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:238)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for db_marketing-0: 30002 ms has passed since last append
2022-06-01 17:34:34.838 [       job-0] INFO  AbstractScheduler    - Scheduler accomplished all tasks.
2022-06-01 17:34:34.839 [       job-0] INFO  JobContainer         - Addax Writer.Job [kafkawriter] do post work.
2022-06-01 17:34:34.839 [       job-0] INFO  JobContainer         - Addax Reader.Job [sqlserverreader] do post work.
2022-06-01 17:34:34.840 [       job-0] INFO  JobContainer         - PerfTrace not enable!
2022-06-01 17:34:34.840 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 41688 records, 18703515 bytes | Speed 380.52KB/s, 868 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 33.283s |  All Task WaitReaderTime 9.866s | Percentage 100.00%
2022-06-01 17:34:34.841 [       job-0] INFO  JobContainer         - 
任务启动时刻                    : 2022-06-01 17:33:45
任务结束时刻                    : 2022-06-01 17:34:34
任务总计耗时                    :                 48s
任务平均流量                    :          380.52KB/s
记录写入速度                    :            868rec/s
读出记录总数                    :               41688
读写失败总数                    :                   0

从kafka主题来看，数据并没有全部写入，只写入了一小部分

### Version

4.0.8 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by imzhf** [comment]
![image](https://user-images.githubusercontent.com/3370207/171375343-abf88408-0437-4211-830e-851c2d473604.png)

**Comment by imzhf** [comment]
数据量少时，例如几千条，就能正常执行

**Comment by wgzhao** [comment]
看下kafak服务端是否有对应的报错信息
方便的话，能否提供kafka的相关日志

**Comment by imzhf** [comment]
写入报错时kafka服务端没有异常日志。仔细看客户端日志，就是超过30秒就开始报错，是不是设置的有什么超时时间？

**Comment by imzhf** [comment]
![image](https://user-images.githubusercontent.com/3370207/171543495-d3be9f8c-b7e4-46a5-94b2-c8ecf0e7ed7c.png)

**Comment by imzhf** [comment]
客户端的完整日志：

**Comment by imzhf** [comment]
客户端完整日志：
[CtCust.log](https://github.com/wgzhao/Addax/files/8820343/CtCust.log)

**Comment by wgzhao** [comment]
官方的 [Producer Configuration](https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html) 这里有一个参数说明如下：

[request.timeout.ms](https://docs.confluent.io/platform/current/installation/configuration/producer-configs.html#producerconfigs_request.timeout.ms)
The configuration controls the maximum amount of time the client will wait for the response of a request. If the response is not received before the timeout elapses the client will resend the request if necessary or fail the request if retries are exhausted. This should be larger than replica.lag.time.max.ms (a broker configuration) to reduce the possibility of message duplication due to unnecessary producer retries.

Type:	int
Default:	30000 (30 seconds)
Valid Values:	[0,...]
Importance:	medium


你可以参数调整这个参数，`kafkawriter` 插件支持 `properties` 参数，你可以在这个参数里，设置任意多的连接属性

**Comment by wgzhao** [comment]
我测试了十万条记录的插入，目前没有发现超时的现象，任务文件如下：

```json
{
  "job": {
    "setting": {
        "speed": {
            "channel": 1
        }
    },
    "content": [
      {
        "reader": {
            "name": "streamreader",
            "parameter": {
              "column": [
                    {"random": "10,1000", "type": "long"},
                    {"value": "1.1.1.1", "type": "string"},
                    {"value": 19890604.0, "type": "double"},
                    {"value": 19890604, "type": "long"},
                    {"value": 19890604, "type": "long"},
                    {"value": "hello world", "type": "string"},
                    {"value": "long text", "type": "string"},
                    {"value": "41.12,-71.34", "type": "string"},
                    {"value": "2017-05-25 11:22:33", "type": "string"}
                    ],
            "sliceRecordCount": 100000
            }
        },
        "writer": {
          "name": "kafkawriter",
          "parameter": {
            "brokerList": "remote-host:9092",
            "topic": "test-1",
            "partitions": 0,
            "batchSize": 1000,
            "column": ["col1", "col2","col3","col4","col5", "col6", "col7", "col8", "col9"]
          }
        }
      }
    ]
  }
}
```

执行结果如下：

```shell
bin/addax.sh job/stream2kafka.json

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.9)

2022-06-19 14:14:23.292 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-06-19 14:14:23.304 [        main] INFO  Engine               -
{
	"content":{
		"reader":{
			"parameter":{
				"column":[
					{
						"random":"10,1000",
						"type":"long"
					},
					{
						"type":"string",
						"value":"1.1.1.1"
					},
					{
						"type":"double",
						"value":19890604.0
					},
					{
						"type":"long",
						"value":19890604
					},
					{
						"type":"long",
						"value":19890604
					},
					{
						"type":"string",
						"value":"hello world"
					},
					{
						"type":"string",
						"value":"long text"
					},
					{
						"type":"string",
						"value":"41.12,-71.34"
					},
					{
						"type":"string",
						"value":"2017-05-25 11:22:33"
					}
				],
				"sliceRecordCount":100000
			},
			"name":"streamreader"
		},
		"writer":{
			"parameter":{
				"partitions":0,
				"column":[
					"col1",
					"col2",
					"col3",
					"col4",
					"col5",
					"col6",
					"col7",
					"col8",
					"col9"
				],
				"topic":"test-1",
				"batchSize":1000,
				"brokerList":"remote-host:9092"
			},
			"name":"kafkawriter"
		}
	},
	"setting":{
		"speed":{
			"channel":1
		}
	}
}

2022-06-19 14:14:23.333 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-06-19 14:14:23.334 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2022-06-19 14:14:23.334 [        main] INFO  JobContainer         - Set jobId = 0
2022-06-19 14:14:23.351 [       job-0] INFO  JobContainer         - Addax Reader.Job [streamreader] do prepare work .
2022-06-19 14:14:23.352 [       job-0] INFO  JobContainer         - Addax Writer.Job [kafkawriter] do prepare work .
2022-06-19 14:14:23.352 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2022-06-19 14:14:23.352 [       job-0] INFO  JobContainer         - Addax Reader.Job [streamreader] splits to [1] tasks.
2022-06-19 14:14:23.353 [       job-0] INFO  JobContainer         - Addax Writer.Job [kafkawriter] splits to [1] tasks.
2022-06-19 14:14:23.376 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2022-06-19 14:14:23.388 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2022-06-19 14:14:23.391 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2022-06-19 14:14:23.391 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2022-06-19 14:14:23.577 [0-0-0-writer] INFO  ProducerConfig       - ProducerConfig values:
....
2022-06-19 14:14:23.817 [0-0-0-writer] INFO  AppInfoParser        - Kafka version : 2.0.0
2022-06-19 14:14:23.817 [0-0-0-writer] INFO  AppInfoParser        - Kafka commitId : 3402a8361b734732
2022-06-19 14:14:24.510 [kafka-producer-network-thread | addax-kafka-writer] WARN  NetworkClient        - [Producer clientId=addax-kafka-writer] Error while fetching metadata with correlation id 1 : {test-1=LEADER_NOT_AVAILABLE}
2022-06-19 14:14:24.510 [kafka-producer-network-thread | addax-kafka-writer] INFO  Metadata             - Cluster ID: HVIikHF6SQKguZSnAc4C-Q
2022-06-19 14:14:24.627 [kafka-producer-network-thread | addax-kafka-writer] WARN  NetworkClient        - [Producer clientId=addax-kafka-writer] Error while fetching metadata with correlation id 3 : {test-1=LEADER_NOT_AVAILABLE}
2022-06-19 14:14:35.413 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 66464 records, 6114688 bytes | Speed 497.61KB/s, 5538 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 1.331s |  All Task WaitReaderTime 8.022s | Percentage 0.00%
2022-06-19 14:14:38.418 [       job-0] INFO  AbstractScheduler    - Scheduler accomplished all tasks.
2022-06-19 14:14:38.418 [       job-0] INFO  JobContainer         - Addax Writer.Job [kafkawriter] do post work.
2022-06-19 14:14:38.419 [       job-0] INFO  JobContainer         - Addax Reader.Job [streamreader] do post work.
2022-06-19 14:14:38.421 [       job-0] INFO  JobContainer         - PerfTrace not enable!
2022-06-19 14:14:38.421 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 100000 records, 9200000 bytes | Speed 598.96KB/s, 6666 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 1.335s |  All Task WaitReaderTime 11.870s | Percentage 100.00%
2022-06-19 14:14:38.422 [       job-0] INFO  JobContainer         -
任务启动时刻                    : 2022-06-19 14:14:23
任务结束时刻                    : 2022-06-19 14:14:38
任务总计耗时                    :                 15s
任务平均流量                    :          598.96KB/s
记录写入速度                    :           6666rec/s
读出记录总数                    :              100000
读写失败总数                    :                   0
```

我用的是 `4.0.9` 版本，不过 `kafkawriter` 插件没有变动，所以他和 `4.0.8`  版本一直。
另外，我用的 kafka 版本为 是 `2.13_3.2.0`
