### ISSUE TITLE
[Bug]: 本地调试代码java.lang.NoClassDefFoundError，mysqlreader loadClass success, but cannot invoke clazz.newInstance()

### ISSUE THREAD

**Issue by zhfk** [wgzhao/Addax#581]
### Contact Details（联系人）

1105159489@qq.com

### What happened?

IDEA本地调试代码时，mysqlreader插件加载成功, 但是 clazz.newInstance() 时抛出异常 java.lang.NoClassDefFoundError
运行时指定的参数如下：
```
-Daddax.home=/XXX/Addax/target/addax/addax-4.0.9-SNAPSHOT
com.wgzhao.addax.core.Engine
-job /XXX/Addax/job/mysql2stream.json
```
mysql2stream.json内容如下：
```
{
  "job": {
    "setting": {
      "speed": {
        "channel": 2
      },
      "errorLimit": {
        "record": 0,
        "percentage": 0.02
      }
    },
    "content": [
      {
        "reader": {
          "name": "mysqlreader",
          "parameter": {
            "username": "XXX",
            "password": "XXXXXX",
            "column": [
              "id",
              "name"
            ],
            "splitPk": "id",
            "connection": [
              {
                "table": [
                  "test_table"
                ],
                "jdbcUrl": [
                  "jdbc:mysql://127.0.0.1:3306/test_db"
                ]
              }
            ]
          }
        },
        "writer": {
          "name": "streamwriter",
          "parameter": {
            "print":true
          }
        }
      }
    ]
  }
}
```
**console输出的错误信息：**
```
java.lang.NoClassDefFoundError: com/wgzhao/addax/rdbms/reader/CommonRdbmsReader$Job
	at com.wgzhao.addax.plugin.reader.mysqlreader.MysqlReader$Job.init(MysqlReader.java:66)
	at com.wgzhao.addax.core.job.JobContainer.initJobReader(JobContainer.java:623)
	at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:310)
	at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:131)
	at com.wgzhao.addax.core.Engine.start(Engine.java:75)
	at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
	at com.wgzhao.addax.core.Engine.main(Engine.java:163)
Caused by: java.lang.ClassNotFoundException: com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
```
**经过调试发现问题所在于：com.wgzhao.addax.core.util.container.LoadUtil.java loadJobPlugin 方法**
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/18511567/172552437-229c976e-d733-4a32-9e73-e3639b6c80cf.png">

### Version

4.0.8 (Default)

### OS Type

MacOS

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell
15:02:45.760 [job-0] DEBUG com.wgzhao.addax.core.job.JobContainer - 
	 [total cpu info] => 
		averageCpu                     | maxDeltaCpu                    | minDeltaCpu                    
		-1.00%                         | -1.00%                         | -1.00%
                        

	 [total gc info] => 
		 NAME                 | totalGCCount       | maxDeltaGCCount    | minDeltaGCCount    | totalGCTime        | maxDeltaGCTime     | minDeltaGCTime     
		 PS MarkSweep         | 0                  | 0                  | 0                  | 0.000s             | 0.000s             | 0.000s             
		 PS Scavenge          | 0                  | 0                  | 0                  | 0.000s             | 0.000s             | 0.000s             

15:02:45.760 [job-0] INFO com.wgzhao.addax.core.job.JobContainer - PerfTrace not enable!
java.lang.NoClassDefFoundError: com/wgzhao/addax/rdbms/reader/CommonRdbmsReader$Job
	at com.wgzhao.addax.plugin.reader.mysqlreader.MysqlReader$Job.init(MysqlReader.java:66)
	at com.wgzhao.addax.core.job.JobContainer.initJobReader(JobContainer.java:623)
	at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:310)
	at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:131)
	at com.wgzhao.addax.core.Engine.start(Engine.java:75)
	at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
	at com.wgzhao.addax.core.Engine.main(Engine.java:163)
Caused by: java.lang.ClassNotFoundException: com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Job
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
Disconnected from the target VM, address: '127.0.0.1:63772', transport: 'socket'

Process finished with exit code 2
```

**Comment by wgzhao** [comment]
麻烦看下 [调试文档](https://wgzhao.github.io/Addax/4.0.8/debug/) 中的假定部分，看是否满足要求。

我个人偏好用第二种远程调试模式。

**Comment by k7gxn56** [comment]
@zhfk 老兄，解决了吗？我也碰到一模一样的问题，都是按照调试文档来的
