### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by poseidon2011** [wgzhao/Addax#599]
### What happened?

String["202003031954363701543274"]不能转为Long, Mysql5.7:  varchar(24)，clickhouse : Nullable(String)

### Version

4.0.9 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
[0-0-0-writer] ERROR WriterRunner         - Writer Runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[Common-01], Describe:[同步数据出现业务脏数据情况，数据类型转换错误 .] - String["202003031954363701543274"]不能转为Long .
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.common.element.StringColumn.asLong(StringColumn.java:112)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:491)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task$1.fillPreparedStatementColumnType(ClickHouseWriter.java:123)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:456)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task$1.doBatchInsert(ClickHouseWriter.java:143)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:316)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task.startWrite(ClickHouseWriter.java:163)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[Common-01], Describe:[同步数据出现业务脏数据情况，数据类型转换错误 .] - String["202003031954363701543274"]不能转为Long .
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.common.element.StringColumn.asLong(StringColumn.java:112)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:491)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task$1.fillPreparedStatementColumnType(ClickHouseWriter.java:123)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:456)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task$1.doBatchInsert(ClickHouseWriter.java:143)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:316)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task.startWrite(ClickHouseWriter.java:163)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by poseidon2011** [comment]
[root@localhost bin]# ./addax.sh ../job/mysq2ch.json

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.9)

2022-06-23 21:36:46.474 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-06-23 21:36:46.529 [        main] INFO  Engine               -
{
	"content":{
		"reader":{
			"parameter":{
				"password":"*****",
				"column":[
					"*"
				],
				"connection":[
					{
						"driver":"com.mysql.jdbc.Driver",
						"jdbcUrl":[
							"jdbc:mysql://192.168.152.141:3306/smp?serverTimezone=UTC"
						],
						"table":[
							"acr_record_cg"
						]
					}
				],
				"username":"root"
			},
			"name":"mysqlreader"
		},
		"writer":{
			"parameter":{
				"column":[
					"*"
				],
				"connection":[
					{
						"jdbcUrl":"jdbc:clickhouse://127.0.0.1:8123/smp",
						"table":[
							"acr_record_cg02"
						]
					}
				],
				"username":"default",
				"preSql":[
					"alter table @table delete where 1=1"
				]
			},
			"name":"clickhousewriter"
		}
	},
	"setting":{
		"speed":{
			"bytes":-1,
			"channel":1
		}
	}
}

2022-06-23 21:36:46.653 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-06-23 21:36:46.654 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2022-06-23 21:36:46.665 [        main] INFO  JobContainer         - Set jobId = 0
2022-06-23 21:36:46.930 [       job-0] WARN  OriginalConfPretreatmentUtil - use specified driver class: com.mysql.jdbc.Driver
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2022-06-23 21:36:50.355 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:mysql://192.168.152.141:3306/smp?serverTimezone=UTC&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true.
2022-06-23 21:36:50.358 [       job-0] WARN  OriginalConfPretreatmentUtil - 您的配置文件中的列配置存在一定的风险. 因为您未配置读取数据库表的列，当您的表字段个数、类型有变动时，可能影响任务正确性甚至会运行出错。请检查您的配置并作出修改.
2022-06-23 21:36:51.593 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[acr_record_cg02] all columns:[streamnumber,oricallednumber,stopdateandtime,reservedInt8,reservedInt7,reservedStr5,chargeclass,reservedStr3,callersubgroup,reroute,callcategory,reservedInt,callcost,calledpartynumber,startdateandtime,operatorname,operatorid,reservedStr6,reservedStr9,specificchargedpar,callerpnp,acrtype,forwardnumber,releasereason,reservedInt5,translatednumber,videocallflag,srfmsgid,reservedStr7,chargemode,serviceid,reservedInt1,reservedStr,acrcallid,extforwardnumber,id,reservedInt9,duration,reservedInt2,reservedStr2,reservedStr8,callingpartynumber,oricallingnumber,calleepnp,reservedInt4,reservedStr4,calleesubgroup,chargetype,userpin,releasecause,reservedInt6,transparentparamet,calltype,groupnumber,msserver,areanumber,reservedStr1,servicekey,begintime,reservedInt3].
2022-06-23 21:36:51.594 [       job-0] WARN  OriginalConfPretreatmentUtil - 您的配置文件中的列配置信息存在风险. 因为您配置的写入数据库表的列为*，当您的表字段个数、类型有变动时，可能影响任务正确性甚至会运行出错。请检查您的配置并作出修改.
2022-06-23 21:36:51.625 [       job-0] INFO  OriginalConfPretreatmentUtil - Write data [INSERT INTO %s ( streamnumber,oricallednumber,stopdateandtime,reservedInt8,reservedInt7,reservedStr5,chargeclass,reservedStr3,callersubgroup,reroute,callcategory,reservedInt,callcost,calledpartynumber,startdateandtime,operatorname,operatorid,reservedStr6,reservedStr9,specificchargedpar,callerpnp,acrtype,forwardnumber,releasereason,reservedInt5,translatednumber,videocallflag,srfmsgid,reservedStr7,chargemode,serviceid,reservedInt1,reservedStr,acrcallid,extforwardnumber,id,reservedInt9,duration,reservedInt2,reservedStr2,reservedStr8,callingpartynumber,oricallingnumber,calleepnp,reservedInt4,reservedStr4,calleesubgroup,chargetype,userpin,releasecause,reservedInt6,transparentparamet,calltype,groupnumber,msserver,areanumber,reservedStr1,servicekey,begintime,reservedInt3) VALUES ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? )], which jdbcUrl [jdbc:clickhouse://127.0.0.1:8123/smp]
2022-06-23 21:36:51.626 [       job-0] INFO  JobContainer         - Addax Reader.Job [mysqlreader] do prepare work .
2022-06-23 21:36:51.627 [       job-0] INFO  JobContainer         - Addax Writer.Job [clickhousewriter] do prepare work .
2022-06-23 21:36:51.671 [       job-0] INFO  CommonRdbmsWriter$Job - Begin to execute preSqls:[alter table acr_record_cg02 delete where 1=1]. context info:jdbc:clickhouse://127.0.0.1:8123/smp.
2022-06-23 21:36:51.711 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2022-06-23 21:36:51.720 [       job-0] INFO  JobContainer         - Addax Reader.Job [mysqlreader] splits to [1] tasks.
2022-06-23 21:36:51.722 [       job-0] INFO  JobContainer         - Addax Writer.Job [clickhousewriter] splits to [1] tasks.
2022-06-23 21:36:51.798 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2022-06-23 21:36:51.852 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2022-06-23 21:36:51.883 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2022-06-23 21:36:51.884 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2022-06-23 21:36:52.034 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select * from acr_record_cg
] jdbcUrl:[jdbc:mysql://192.168.152.141:3306/smp?serverTimezone=UTC&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true].
2022-06-23 21:36:52.811 [0-0-0-writer] INFO  CommonRdbmsWriter$Task - insert sql: insert into acr_record_cg02 select streamnumber,oricallednumber,stopdateandtime,reservedInt8,reservedInt7,reservedStr5,chargeclass,reservedStr3,callersubgroup,reroute,callcategory,reservedInt,callcost,calledpartynumber,startdateandtime,operatorname,operatorid,reservedStr6,reservedStr9,specificchargedpar,callerpnp,acrtype,forwardnumber,releasereason,reservedInt5,translatednumber,videocallflag,srfmsgid,reservedStr7,chargemode,serviceid,reservedInt1,reservedStr,acrcallid,extforwardnumber,id,reservedInt9,duration,reservedInt2,reservedStr2,reservedStr8,callingpartynumber,oricallingnumber,calleepnp,reservedInt4,reservedStr4,calleesubgroup,chargetype,userpin,releasecause,reservedInt6,transparentparamet,calltype,groupnumber,msserver,areanumber,reservedStr1,servicekey,begintime,reservedInt3 from input('streamnumber String,oricallednumber Nullable(String),stopdateandtime Nullable(String),reservedInt8 Nullable(Int32),reservedInt7 Nullable(Int32),reservedStr5 Nullable(String),chargeclass Nullable(Int32),reservedStr3 Nullable(String),callersubgroup Nullable(String),reroute Nullable(Int32),callcategory Nullable(Int32),reservedInt Nullable(Int32),callcost Nullable(Int32),calledpartynumber Nullable(String),startdateandtime Nullable(String),operatorname Nullable(String),operatorid Nullable(Int32),reservedStr6 Nullable(String),reservedStr9 Nullable(String),specificchargedpar Nullable(String),callerpnp Nullable(String),acrtype Nullable(Int32),forwardnumber Nullable(String),releasereason Nullable(String),reservedInt5 Nullable(Int32),translatednumber Nullable(String),videocallflag Nullable(Int32),srfmsgid Nullable(String),reservedStr7 Nullable(String),chargemode Nullable(Int16),serviceid Nullable(String),reservedInt1 Nullable(Int32),reservedStr Nullable(String),acrcallid Nullable(String),extforwardnumber Nullable(String),id Int32,reservedInt9 Nullable(Int32),duration Nullable(Int32),reservedInt2 Nullable(Int32),reservedStr2 Nullable(String),reservedStr8 Nullable(String),callingpartynumber Nullable(String),oricallingnumber Nullable(String),calleepnp Nullable(String),reservedInt4 Nullable(Int32),reservedStr4 Nullable(String),calleesubgroup Nullable(String),chargetype Nullable(Int32),userpin Nullable(String),releasecause Nullable(Int32),reservedInt6 Nullable(Int32),transparentparamet Nullable(String),calltype Nullable(Int32),groupnumber Nullable(String),msserver Nullable(String),areanumber Nullable(String),reservedStr1 Nullable(String),servicekey Nullable(Int32),begintime String,reservedInt3 Nullable(Int32)')
2022-06-23 21:36:53.074 [0-0-0-writer] ERROR WriterRunner         - Writer Runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[Common-01], Describe:[同步数据出现业务脏数据情况，数据类型转换错误 .] - String["202003031954363701543274"]不能转为Long .
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.common.element.StringColumn.asLong(StringColumn.java:112)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:491)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task$1.fillPreparedStatementColumnType(ClickHouseWriter.java:123)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:456)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task$1.doBatchInsert(ClickHouseWriter.java:143)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:316)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task.startWrite(ClickHouseWriter.java:163)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[Common-01], Describe:[同步数据出现业务脏数据情况，数据类型转换错误 .] - String["202003031954363701543274"]不能转为Long .
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.common.element.StringColumn.asLong(StringColumn.java:112)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:491)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task$1.fillPreparedStatementColumnType(ClickHouseWriter.java:123)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:456)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task$1.doBatchInsert(ClickHouseWriter.java:143)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:316)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task.startWrite(ClickHouseWriter.java:163)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
	at java.lang.Thread.run(Thread.java:745)
2022-06-23 21:36:54.959 [       job-0] ERROR JobContainer         - 运行scheduler出错.
2022-06-23 21:36:54.976 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 2560 records, 1058845 bytes | Speed 1.01MB/s,2560 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.012s |  All Task WaitReaderTime 0.490s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[Common-01], Describe:[同步数据出现业务脏数据情况，数据类型转换错误 .] - String["202003031954363701543274"]不能转为Long .
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.common.element.StringColumn.asLong(StringColumn.java:112)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:491)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task$1.fillPreparedStatementColumnType(ClickHouseWriter.java:123)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:456)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task$1.doBatchInsert(ClickHouseWriter.java:143)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:316)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
	at com.wgzhao.addax.plugin.writer.clickhousewriter.ClickHouseWriter$Task.startWrite(ClickHouseWriter.java:163)
	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
	at java.lang.Thread.run(Thread.java:745)
[mysq2ch.json.txt](https://github.com/wgzhao/Addax/files/8986002/mysq2ch.json.txt)

**Comment by wgzhao** [comment]
- String["202003031954363701543274"]不能转为Long .

这个字段对应的 clickhouse 类型是什么？
你可以尝试把这个值直接插入到clickhouse 表里，看是否数值是否超过了该类型的最大值

**Comment by poseidon2011** [comment]
你好，对应的是String，可以插入到clickhouse表里面；大佬顺便问一下，后续会支持增量实时数据同步吗

**Comment by wgzhao** [comment]
如果你的源表字段和目标字段都是是字符串类型，就不存在把字符串类型转为 Long 这类型这个过程的。具体要插入的这个字段名称是什么？

Addax 专注于全量以及自定义增量数据导入，暂没有实时增量同步开发的考虑

**Comment by wgzhao** [comment]
下面是我的测试过程

源是 MySQL

```sql
ysql> create table t (col varchar(24));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t values('202003031954363701543274');
Query OK, 1 row affected (0.00 sec)

mysql> select * from t;
+--------------------------+
| col                      |
+--------------------------+
| 202003031954363701543274 |
+--------------------------+
1 row in set (0.00 sec)
```

目标是 clickhouse

```
 :) create table t (col1 String) engine TinyLog;

CREATE TABLE t
(
    `col1` String
)
ENGINE = TinyLog

Query id: 6fd3fffc-baf4-4991-b8d3-03f621fd12f9

Ok.

0 rows in set. Elapsed: 0.002 sec.

 :) desc t;

DESCRIBE TABLE t

Query id: 66552707-9780-4716-81b0-364be17682ef

┌─name─┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ col1 │ String │              │                    │         │                  │                │
└──────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

1 rows in set. Elapsed: 0.001 sec.
```

下面是 执行的 json 文件

```json
{
    "job": {
        "setting": {
            "speed": {
                 "byte": -1,
                 "channel": 1
            }
        },
        "content": [
            {
                "reader": {
                    "name": "mysqlreader",
                    "parameter": {
                        "username": "xxx",
                        "password": "xxxx",
                        "column": [
                           "*"
                        ],
                        "connection": [
                            {
                                "table": [
                                    "t"
                                ],
                                "jdbcUrl": [
                "jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Chongqing"
                                ]
                            }
                        ]
                    }
                },
                "writer": {
                    "name": "clickhousewriter",
                    "parameter": {
                        "username": "xxxx",
                        "password": "xxxxx",
                        "preSql":["truncate table @table"],
                        "column": [
                            "*"
                        ],
                        "connection": [
                            {
                                "table": [
                                    "t"
                                ],
                                "jdbcUrl": "jdbc:clickhouse://ip:port/default"
                            }
                        ]
                    }
                }
            }
        ]
    }
}
```

下面是运行的结果

```shell
bin/addax.sh test.json

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.8)

2022-06-27 10:55:28.442 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-06-27 10:55:28.454 [        main] INFO  Engine               -
{
	"content":{
		"reader":{
			"parameter":{
				"password":"*****",
				"column":[
					"*"
				],
				"connection":[
					{
						"jdbcUrl":[
							"jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Chongqing"
						],
						"table":[
							"t"
						]
					}
				],
				"username":"xxx"
			},
			"name":"mysqlreader"
		},
		"writer":{
			"parameter":{
				"password":"*****",
				"column":[
					"*"
				],
				"connection":[
					{
						"jdbcUrl":"jdbc:clickhouse://ip:port/default",
						"table":[
							"t"
						]
					}
				],
				"username":"xxx",
				"preSql":[
					"truncate table @table"
				]
			},
			"name":"clickhousewriter"
		}
	},
	"setting":{
		"speed":{
			"byte":-1,
			"channel":1
		}
	}
}

2022-06-27 10:55:28.497 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-06-27 10:55:28.497 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2022-06-27 10:55:28.498 [        main] INFO  JobContainer         - Set jobId = 0
2022-06-27 10:55:29.747 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Chongqing&yearIsDateType=false&zeroDateTimeBehavior=CONVERT_TO_NULL&tinyInt1isBit=false&rewriteBatchedStatements=true&useSSL=false.
2022-06-27 10:55:29.748 [       job-0] WARN  OriginalConfPretreatmentUtil - 您的配置文件中的列配置存在一定的风险. 因为您未配置读取数据库表的列，当您的表字段个数、类型有变动时，可能影响任务正确性甚至会运行出错。请检查您的配置并作出修改.
2022-06-27 10:55:30.339 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[t] all columns:[col1].
2022-06-27 10:55:30.339 [       job-0] WARN  OriginalConfPretreatmentUtil - 您的配置文件中的列配置信息存在风险. 因为您配置的写入数据库表的列为*，当您的表字段个数、类型有变动时，可能影响任务正确性甚至会运行出错。请检查您的配置并作出修改.
2022-06-27 10:55:30.354 [       job-0] INFO  OriginalConfPretreatmentUtil - Write data [INSERT INTO %s ( col1) VALUES ( ? )], which jdbcUrl [jdbc:clickhouse://10.90.71.91/default]
2022-06-27 10:55:30.355 [       job-0] INFO  JobContainer         - Addax Reader.Job [mysqlreader] do prepare work .
2022-06-27 10:55:30.355 [       job-0] INFO  JobContainer         - Addax Writer.Job [clickhousewriter] do prepare work .
2022-06-27 10:55:30.541 [       job-0] INFO  CommonRdbmsWriter$Job - Begin to execute preSqls:[truncate table t]. context info:jdbc:clickhouse://10.90.71.91/default.
2022-06-27 10:55:30.580 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2022-06-27 10:55:30.583 [       job-0] INFO  JobContainer         - Addax Reader.Job [mysqlreader] splits to [1] tasks.
2022-06-27 10:55:30.583 [       job-0] INFO  JobContainer         - Addax Writer.Job [clickhousewriter] splits to [1] tasks.
2022-06-27 10:55:30.604 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2022-06-27 10:55:30.629 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2022-06-27 10:55:30.652 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2022-06-27 10:55:30.652 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2022-06-27 10:55:30.679 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select * from t
] jdbcUrl:[jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Chongqing&yearIsDateType=false&zeroDateTimeBehavior=CONVERT_TO_NULL&tinyInt1isBit=false&rewriteBatchedStatements=true&useSSL=false].
2022-06-27 10:55:30.876 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Finished read record by Sql: [select * from t
] jdbcUrl:[jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Chongqing&yearIsDateType=false&zeroDateTimeBehavior=CONVERT_TO_NULL&tinyInt1isBit=false&rewriteBatchedStatements=true&useSSL=false].
2022-06-27 10:55:31.035 [0-0-0-writer] INFO  CommonRdbmsWriter$Task - insert sql: insert into t select col1 from input('col1 String')
2022-06-27 10:55:33.664 [       job-0] INFO  AbstractScheduler    - Scheduler accomplished all tasks.
2022-06-27 10:55:33.665 [       job-0] INFO  JobContainer         - Addax Writer.Job [clickhousewriter] do post work.
2022-06-27 10:55:33.665 [       job-0] INFO  JobContainer         - Addax Reader.Job [mysqlreader] do post work.
2022-06-27 10:55:33.666 [       job-0] INFO  JobContainer         - PerfTrace not enable!
2022-06-27 10:55:33.668 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 1 records, 24 bytes | Speed 8B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2022-06-27 10:55:33.670 [       job-0] INFO  JobContainer         -
任务启动时刻                    : 2022-06-27 10:55:28
任务结束时刻                    : 2022-06-27 10:55:33
任务总计耗时                    :                  5s
任务平均流量                    :                8B/s
记录写入速度                    :              0rec/s
读出记录总数                    :                   1
读写失败总数                    :                   0
```

最后是 clickhouse 表结果

```sql
:) select * from t;

SELECT *
FROM t

Query id: 846fd83f-2ab6-4491-84af-86c0a75582a9

┌─col1─────────────────────┐
│ 202003031954363701543274 │
└──────────────────────────┘

1 rows in set. Elapsed: 0.002 sec.
```
