### ISSUE TITLE
[Bug]: win10使用hive2es报NPE异常

### ISSUE THREAD

**Issue by k7gxn56** [wgzhao/Addax#608]
### Contact Details（联系人）

799590989@qq.com

### What happened?

```
python .\bin\addax.py .\job\hive2es.json

==================== DEPRECATED WARNING ========================
addax.py is deprecated, It's going to be removed in future release.
As a replacement, you can use addax.sh to run job
==================== DEPRECATED WARNING ========================


  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.10-SNAPSHOT)

java.lang.NullPointerException
        at com.wgzhao.addax.core.util.ConfigParser.upgradeJobConfig(ConfigParser.java:104)
        at com.wgzhao.addax.core.util.ConfigParser.parse(ConfigParser.java:55)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:115)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)

hive2es.json

{
	"content":[
		{
			"reader":{
				"parameter":{
				"username": "hive",
				    "password": "hive",
				    "connection": [
				      {
					"jdbcUrl": [
					  "jdbc:hive2://***"
					],
					"table": [
					  "te_0f7682fd07884707b85b7bad80896017"
					]
				      }
				    ],
				    "where": "" ,
					"haveKerberos":true,
					"kerberosKeytabFilePath":"/home**/hive.keytab",
					"hadoopConfig":{
						"dfs.ha.namenodes.chinaoly":"nn1,nn2",
						"dfs.namenode.rpc-address.chinaoly.nn2":"***:8022",
						"dfs.namenode.rpc-address.chinaoly.nn1":"***:8020",
						"dfs.nameservices":"chinaoly",
						"dfs.client.failover.proxy.provider.chinaoly":"org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"
					},
					"column":[
						{
							"type":"STRING",
							"value":"gmsfhm"
						},
						{
							"type":"STRING",
							"value":"zsyd_rzyc_fz"
						},
						{
							"type":"STRING",
							"value":"zsyd_tfyc_fz"
						},
						{
							"type":"STRING",
							"value":"swyd_swyc10cys_fz"
						},
						{
							"type":"STRING",
							"value":"swyd_swycqt20cys_fz"
						},
						{
							"type":"STRING",
							"value":"my_dt"
						},
						{
							"type":"STRING",
							"value":"my_primary_key"
						},
						{
							"type":"STRING",
							"value":"dt"
						}
					],
					"defaultFS":"hdfs://***",
					"encoding":"UTF-8",
					"javaSecurityKrb5Conf":"/home/***/krb5.conf",
					"kerberosPrincipal":"hive/***"
				},
				"name":"hivereader"
			},
			"writer":{
				"parameter":{
					"accessId":"xxx",
					"settings":{
						"index":{
							"number_of_shards":1,
							"number_of_replicas":1
						}
					},
					"endpoint":"http://***",
					"accessKey":"***",
					"cleanup":true,
					"discovery":false,
					"column":[
						{
							"name":"gmsfhm",
							"type":"text"
						},
						{
							"name":"zsyd_rzyc_fz",
							"type":"text"
						},
						{
							"name":"zsyd_tfyc_fz",
							"type":"text"
						},
						{
							"name":"swyd_swyc10cys_fz",
							"type":"text"
						},
						{
							"name":"swyd_swycqt20cys_fz",
							"type":"text"
						},
						{
							"name":"my_dt",
							"type":"text"
						},
						{
							"name":"my_primary_key",
							"type":"text"
						},
						{
							"name":"dt",
							"type":"text"
						}
					],
					"index":"te**_0f7682fd07884707b85b7bad80896017",
					"dynamic":true,
					"type":"_doc",
					"batchSize":30000,
					"splitter":","
				},
				"name":"elasticsearchwriter"
			}
		}
	],
	"setting":{
		"speed":{
			"channel":1
		}
	}
}
```
### Version

4.0.3

### OS Type

Windows

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
配置文件不正确
