### ISSUE TITLE
[Bug]: 读mysql数据写入es报查询超时

### ISSUE THREAD

**Issue by imzhf** [wgzhao/Addax#612]
### What happened?

![企业微信截图_20220709165702](https://user-images.githubusercontent.com/3370207/178099174-74d6f2ad-8de4-455b-a393-985ade6c7311.png)

### Version

4.0.9 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
2022-07-09 16:24:20.812 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 895520 records, 665149729 bytes | Speed 2.19MB/s, 2917 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 234.337s |  All Task WaitReaderTime 24.089s | Percentage 0.00%
2022-07-09 16:24:32.818 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 929376 records, 690139282 bytes | Speed 1.99MB/s, 2821 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 243.664s |  All Task WaitReaderTime 24.953s | Percentage 0.00%
2022-07-09 16:24:44.824 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 960512 records, 715197758 bytes | Speed 1.99MB/s, 2594 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 252.681s |  All Task WaitReaderTime 25.766s | Percentage 0.00%
2022-07-09 16:24:56.831 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 990528 records, 739485925 bytes | Speed 1.93MB/s, 2501 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 260.793s |  All Task WaitReaderTime 26.565s | Percentage 0.00%
2022-07-09 16:24:56.836 [       job-0] INFO  VMInfo               -
         [delta cpu info] =>
                curDeltaCpu                    | averageCpu                     | maxDeltaCpu                    | minDeltaCpu
                -1.00%                         | -1.00%                         | -1.00%                         | -1.00%


         [delta memory info] =>
                 NAME                           | used_size                      | used_percent                   | max_used_size                  | max_percent
                 PS Eden Space                  | 172.82MB                       | 51.82%                         | 172.82MB                       | 51.82%
                 Code Cache                     | 11.93MB                        | 94.46%                         | 11.93MB                        | 94.46%
                 Compressed Class Space         | 2.51MB                         | 91.31%                         | 2.51MB                         | 91.31%
                 PS Survivor Space              | 107.09MB                       | 65.30%                         | 107.09MB                       | 65.30%
                 PS Old Gen                     | 182.26MB                       | 75.00%                         | 182.26MB                       | 75.00%
                 Metaspace                      | 22.76MB                        | 96.83%                         | 22.76MB                        | 96.83%

         [delta gc info] =>
                 NAME                 | curDeltaGCCount    | totalGCCount       | maxDeltaGCCount    | minDeltaGCCount    | curDeltaGCTime     | totalGCTime        | maxDeltaGCTime     | minDeltaGCTime
                 PS MarkSweep         | 4                  | 4                  | 4                  | 4                  | 0.945s             | 0.945s             | 0.945s             | 0.945s
                 PS Scavenge          | 294                | 294                | 294                | 294                | 6.921s             | 6.921s             | 6.921s             | 6.921s

2022-07-09 16:24:57.135 [0-0-0-reader] ERROR ReaderRunner         - Reader runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为:
                                    SELECT
                                   *
                                    FROM es_cust_wide
                                     具体错误信息为：java.sql.SQLSyntaxErrorException: Query exceeded time limit of 300 seconds
        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
        at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:249)
        at com.wgzhao.addax.plugin.reader.mysqlreader.MysqlReader$Task.startRead(MysqlReader.java:126)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by wgzhao** [comment]
这是查询 MySQL 超时了，请确认上述查询能在 300 秒内完成，如果不能，或者在 MySQL 端增加最大执行时间调高，或者在JDBC 连接串中增加最大执行时间的参数
