### ISSUE TITLE
[Bug]: java.sql.SQLRecoverableException: IO Error: Socket read timed out

### ISSUE THREAD

**Issue by iouAkira** [wgzhao/Addax#619]
### What happened?

不确定是不是bug，oraclereader 需要执行的查询，因为业务库方面条件没有索引，需要8~10分钟，但是addax同步任务超过5分钟就会报该异常`java.sql.SQLRecoverableException: IO Error: Socket read timed out`

### Version

4.0.8

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
2022-07-16 15:33:37.456 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select xxxx from INV.MTL_MATERIAL_TRANSACTIONS2 where (create_time>sysdate-1 and create_time<sysdate) or (update_date>sysdate-1 and update_date<sysdate)
] jdbcUrl:[jdbc:oracle:thin:@xxx.xxx.xx.xx:xxxx].
2022-07-16 15:33:49.424 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:34:01.428 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:34:13.434 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:34:25.438 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:34:37.442 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:34:49.446 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:35:01.449 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:35:13.460 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:35:25.464 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:35:37.467 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:35:49.475 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:36:01.477 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:36:13.480 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:36:25.483 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:36:37.486 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:36:49.491 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:37:01.493 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:37:13.496 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:37:25.498 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:37:37.501 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:37:49.504 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:38:01.507 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:38:13.509 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:38:25.512 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:38:37.514 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2022-07-16 15:38:37.516 [       job-0] INFO  VMInfo               - 
	 [delta cpu info] => 
		curDeltaCpu                    | averageCpu                     | maxDeltaCpu                    | minDeltaCpu                    
		-1.00%                         | -1.00%                         | -1.00%                         | -1.00%
                        

	 [delta memory info] => 
		 NAME                           | used_size                      | used_percent                   | max_used_size                  | max_percent                    
		 PS Eden Space                  | 35.10MB                        | 30.13%                         | 35.10MB                        | 30.13%                         
		 Code Cache                     | 9.09MB                         | 85.60%                         | 9.09MB                         | 85.60%                         
		 Compressed Class Space         | 4.10MB                         | 96.55%                         | 4.10MB                         | 96.55%                         
		 PS Survivor Space              | 0.00MB                         | 0.00%                          | 0.00MB                         | 0.00%                          
		 PS Old Gen                     | 7.87MB                         | 18.31%                         | 7.87MB                         | 18.31%                         
		 Metaspace                      | 35.58MB                        | 97.58%                         | 35.58MB                        | 97.58%                         

	 [delta gc info] => 
		 NAME                 | curDeltaGCCount    | totalGCCount       | maxDeltaGCCount    | minDeltaGCCount    | curDeltaGCTime     | totalGCTime        | maxDeltaGCTime     | minDeltaGCTime     
		 PS MarkSweep         | 2                  | 2                  | 2                  | 2                  | 0.109s             | 0.109s             | 0.109s             | 0.109s             
		 PS Scavenge          | 7                  | 7                  | 7                  | 7                  | 0.084s             | 0.084s             | 0.084s             | 0.084s             

2022-07-16 15:38:37.644 [0-0-0-reader] ERROR ReaderRunner         - Reader runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select xxxx from INV.MTL_MATERIAL_TRANSACTIONS2 where (create_time>sysdate-1 and create_time<sysdate) or (update_date>sysdate-1 and update_date<sysdate) 具体错误信息为：java.sql.SQLRecoverableException: IO Error: Socket read timed out
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
	at com.wgzhao.addax.plugin.reader.oraclereader.OracleReader$Task.startRead(OracleReader.java:137)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select xxxx from INV.MTL_MATERIAL_TRANSACTIONS2 where (create_time>sysdate-1 and create_time<sysdate) or (update_date>sysdate-1 and update_date<sysdate) 具体错误信息为：java.sql.SQLRecoverableException: IO Error: Socket read timed out
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
	at com.wgzhao.addax.plugin.reader.oraclereader.OracleReader$Task.startRead(OracleReader.java:137)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)
2022-07-16 15:38:40.517 [       job-0] ERROR JobContainer         - 运行scheduler出错.
2022-07-16 15:38:40.519 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select xxxx from INV.MTL_MATERIAL_TRANSACTIONS2 where (create_time>sysdate-1 and create_time<sysdate) or (update_date>sysdate-1 and update_date<sysdate) 具体错误信息为：java.sql.SQLRecoverableException: IO Error: Socket read timed out
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:248)
	at com.wgzhao.addax.plugin.reader.oraclereader.OracleReader$Task.startRead(OracleReader.java:137)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wgzhao** [comment]
如果是 4.0.8 的版本，Oracle 的 readTimeout 是默认值。你可以使用 4.0.9 或更高版本。

**Comment by iouAkira** [comment]
测试了一下，4.0.8版本替换jar问题依旧，直接使用最新的4.0.9 release版本，问题已修复。
