### ISSUE TITLE
[Bug]: ftp读取大文件

### ISSUE THREAD

**Issue by nmgliangwei** [wgzhao/Addax#623]
### What happened?

sftp 读取 27G 的gzip压缩文件,
报 Java heap space
reader的 json 文件如下
```
"reader":{
				"parameter":{
					"path":[
						"/xxx/xxx/xxx.gz"
					],
					"protocol":"sftp",
					"password":"******",
					"port":22,
					"compress":"gz",
					"host":"",
					"column":[
						{
							"index":0,
							"type":"string"
						},
						{
							"index":1,
							"type":"string"
						},
						{
							"index":2,
							"type":"string"
						},
						{
							"index":3,
							"type":"string"
						},
						{
							"index":4,
							"type":"string"
						},
						{
							"index":5,
							"type":"string"
						},
						{
							"index":6,
							"type":"string"
						},
						{
							"index":"7",
							"type":"string"
						},
						{
							"index":"8",
							"type":"string"
						},
						{
							"index":"9",
							"type":"string"
						},
						{
							"index":"10",
							"type":"string"
						},
						{
							"index":"11",
							"type":"string"
						},
						{
							"index":"12",
							"type":"string"
						},
						{
							"index":"13",
							"type":"string"
						},
						{
							"index":"14",
							"type":"string"
						},
						{
							"index":"15",
							"type":"string"
						},
						{
							"index":"16",
							"type":"string"
						},
						{
							"index":"17",
							"type":"string"
						},
						{
							"index":"18",
							"type":"string"
						},
						{
							"index":"19",
							"type":"string"
						},
						{
							"index":"20",
							"type":"string"
						},
						{
							"index":"21",
							"type":"string"
						},
						{
							"index":"22",
							"type":"string"
						},
						{
							"index":"23",
							"type":"string"
						},
						{
							"index":"24",
							"type":"string"
						},
						{
							"index":"25",
							"type":"string"
						},
						{
							"index":"26",
							"type":"string"
						},
						{
							"index":"27",
							"type":"string"
						},
						{
							"index":"28",
							"type":"string"
						},
						{
							"index":"29",
							"type":"string"
						},
						{
							"index":"30",
							"type":"string"
						},
						{
							"index":"31",
							"type":"string"
						},
						{
							"index":"32",
							"type":"string"
						},
						{
							"index":"33",
							"type":"string"
						},
						{
							"index":"34",
							"type":"string"
						},
						{
							"index":"35",
							"type":"string"
						},
						{
							"index":"36",
							"type":"string"
						},
						{
							"index":"37",
							"type":"string"
						},
						{
							"index":"38",
							"type":"string"
						},
						{
							"index":"39",
							"type":"string"
						},
						{
							"index":"40",
							"type":"string"
						},
						{
							"index":"41",
							"type":"string"
						},
						{
							"index":"42",
							"type":"string"
						},
						{
							"type":"string",
							"value":"2022-07-25 18:57:24"
						}
					],
					"skipHeader":false,
					"encoding":"UTF-8",
					"fieldDelimiter":"\t",
					"username":"xxx"
				},
				"name":"ftpreader"
```
### Version

4.0.8

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
[INFO] 2022-07-25 19:06:39.161  - [taskAppId=TASK-2111-235772-673926]:[138] -  -> [36m2022-07-25 19:06:38.387[0;39m [32m[       job-0][0;39m [34mINFO [0;39m [35mStandAloneJobContainerCommunicator[0;39m - Total 18457440 records, 3782202702 bytes | Speed 539.96KB/s, 2616 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 248.367s |  All Task WaitReaderTime 0.578s | Percentage 0.00%
[INFO] 2022-07-25 19:06:47.162  - [taskAppId=TASK-2111-235772-673926]:[138] -  -> java.lang.OutOfMemoryError: Java heap space
	Dumping heap to /opt/soft/addax-4.0.8/java_pid16415.hprof ...
	Unable to create /opt/soft/addax-4.0.8/java_pid16415.hprof: Permission denied
	[36m2022-07-25 19:06:46.600[0;39m [32m[0-0-0-reader][0;39m [1;31mERROR[0;39m [35mReaderRunner        [0;39m - Reader runner Received Exceptions:
	java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:3332)
		at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
		at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
		at java.lang.StringBuilder.append(StringBuilder.java:202)
		at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:375)
		at org.apache.commons.csv.Lexer.nextToken(Lexer.java:285)
		at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:701)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:146)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(CSVParser.java:159)
		at java.util.Iterator.forEachRemaining(Iterator.java:115)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.doReadFromStream(StorageReaderUtil.java:174)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.readFromStream(StorageReaderUtil.java:117)
		at com.wgzhao.addax.plugin.reader.ftpreader.FtpReader$Task.startRead(FtpReader.java:280)
		at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
		at java.lang.Thread.run(Thread.java:748)
	Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-13], Description:[Addax 插件运行时出错, 具体原因请参看Addax 运行结束时的错误诊断信息 .].  - java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:3332)
		at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
		at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
		at java.lang.StringBuilder.append(StringBuilder.java:202)
		at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:375)
		at org.apache.commons.csv.Lexer.nextToken(Lexer.java:285)
		at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:701)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:146)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(CSVParser.java:159)
		at java.util.Iterator.forEachRemaining(Iterator.java:115)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.doReadFromStream(StorageReaderUtil.java:174)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.readFromStream(StorageReaderUtil.java:117)
		at com.wgzhao.addax.plugin.reader.ftpreader.FtpReader$Task.startRead(FtpReader.java:280)
		at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
		at java.lang.Thread.run(Thread.java:748)
	 - java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:3332)
		at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
		at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
		at java.lang.StringBuilder.append(StringBuilder.java:202)
		at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:375)
		at org.apache.commons.csv.Lexer.nextToken(Lexer.java:285)
		at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:701)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:146)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(CSVParser.java:159)
		at java.util.Iterator.forEachRemaining(Iterator.java:115)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.doReadFromStream(StorageReaderUtil.java:174)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.readFromStream(StorageReaderUtil.java:117)
		at com.wgzhao.addax.plugin.reader.ftpreader.FtpReader$Task.startRead(FtpReader.java:280)
		at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
		at java.lang.Thread.run(Thread.java:748)
	
		at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
		at com.wgzhao.addax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:211)
		at com.wgzhao.addax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:47)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:3332)
		at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
		at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
		at java.lang.StringBuilder.append(StringBuilder.java:202)
		at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:375)
		at org.apache.commons.csv.Lexer.nextToken(Lexer.java:285)
		at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:701)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:146)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(CSVParser.java:159)
		at java.util.Iterator.forEachRemaining(Iterator.java:115)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.doReadFromStream(StorageReaderUtil.java:174)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.readFromStream(StorageReaderUtil.java:117)
		at com.wgzhao.addax.plugin.reader.ftpreader.FtpReader$Task.startRead(FtpReader.java:280)
		at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
		... 1 more
[INFO] 2022-07-25 19:06:47.617  - [taskAppId=TASK-2111-235772-673926]:[238] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/88/2111/235772/673926, processId:16399 ,exitStatusCode:255 ,processWaitForStatus:true ,processExitValue:255
[INFO] 2022-07-25 19:06:48.163  - [taskAppId=TASK-2111-235772-673926]:[138] -  -> [36m2022-07-25 19:06:47.390[0;39m [32m[       job-0][0;39m [1;31mERROR[0;39m [35mJobContainer        [0;39m - 运行scheduler出错.
	[36m2022-07-25 19:06:47.391[0;39m [32m[       job-0][0;39m [34mINFO [0;39m [35mStandAloneJobContainerCommunicator[0;39m - Total 18457440 records, 3782202702 bytes | Speed 3.52GB/s, 18457440 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 248.367s |  All Task WaitReaderTime 0.578s | Percentage 0.00%
	com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-13], Description:[Addax 插件运行时出错, 具体原因请参看Addax 运行结束时的错误诊断信息 .].  - java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:3332)
		at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
		at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
		at java.lang.StringBuilder.append(StringBuilder.java:202)
		at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:375)
		at org.apache.commons.csv.Lexer.nextToken(Lexer.java:285)
		at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:701)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:146)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(CSVParser.java:159)
		at java.util.Iterator.forEachRemaining(Iterator.java:115)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.doReadFromStream(StorageReaderUtil.java:174)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.readFromStream(StorageReaderUtil.java:117)
		at com.wgzhao.addax.plugin.reader.ftpreader.FtpReader$Task.startRead(FtpReader.java:280)
		at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
		at java.lang.Thread.run(Thread.java:748)
	 - java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:3332)
		at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
		at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
		at java.lang.StringBuilder.append(StringBuilder.java:202)
		at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:375)
		at org.apache.commons.csv.Lexer.nextToken(Lexer.java:285)
		at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:701)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:146)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(CSVParser.java:159)
		at java.util.Iterator.forEachRemaining(Iterator.java:115)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.doReadFromStream(StorageReaderUtil.java:174)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.readFromStream(StorageReaderUtil.java:117)
		at com.wgzhao.addax.plugin.reader.ftpreader.FtpReader$Task.startRead(FtpReader.java:280)
		at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
		at java.lang.Thread.run(Thread.java:748)
	
		at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
		at com.wgzhao.addax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:63)
		at com.wgzhao.addax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:121)
		at com.wgzhao.addax.core.job.JobContainer.schedule(JobContainer.java:493)
		at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:137)
		at com.wgzhao.addax.core.Engine.start(Engine.java:75)
		at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
		at com.wgzhao.addax.core.Engine.main(Engine.java:163)
	Caused by: java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:3332)
		at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
		at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
		at java.lang.StringBuilder.append(StringBuilder.java:202)
		at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:375)
		at org.apache.commons.csv.Lexer.nextToken(Lexer.java:285)
		at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:701)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:146)
		at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(CSVParser.java:159)
		at java.util.Iterator.forEachRemaining(Iterator.java:115)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.doReadFromStream(StorageReaderUtil.java:174)
		at com.wgzhao.addax.storage.reader.StorageReaderUtil.readFromStream(StorageReaderUtil.java:117)
		at com.wgzhao.addax.plugin.reader.ftpreader.FtpReader$Task.startRead(FtpReader.java:280)
		at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by nmgliangwei** [comment]
@wgzhao 大佬帮看看

**Comment by nmgliangwei** [comment]
发现在文件索引37 列 出现 "物美 单边的引号,去掉引号正常

**Comment by wgzhao** [comment]
gzip 文件读取时，实在内存中解压的，所以27G的文件要在内存中解压的话，至少需要27G内存。你可以调整 `conf/core.json` 文件中的 `jvm` 参数，或者 执行 `bin/addax.sh` 时指定 `-j` 参数来设定可用内存。

**Comment by nmgliangwei** [comment]
@wgzhao 嗯,解压出来100G,那这 100G 也在内存里?   还有文件中的单边引号问题,我使用Transformer 发现也不行.

**Comment by nmgliangwei** [comment]
"transformer": [
                    {
                        "name": "dx_groovy",
                        "parameter": {
                            "code": "Column column = record.getColumn(37);String oriValue = column.asString();if(oriValue){String newValue = oriValue.replaceAll('\"','');record.setColumn(37, new StringColumn(newValue));};return record;",
                            "extraPackage": []
                        }
                    }
                ],

**Comment by wgzhao** [comment]
目前来说，压缩文件都是在内存中进行的，这个看看后续有啥好的解决办法
单边引号这种已经不算正确格式了吧

**Comment by nmgliangwei** [comment]
@wgzhao 单引号确实不是正确的格式,目前就是看能不能在读取的时候给替换掉,否则addax会报错.

**Comment by wgzhao** [comment]
今天在我本地环境进行了测试，使用 `datareader` 插件生成了 1000万条记录，非压缩下 2.6G，压缩后差不多 1G。
我特意设定 `addax` 最多使用 `64M` 内存，进行了读取测试，目前来看没有出现 OOM 的问题。

执行输出如下：
```
bin/addax.sh job/ftpreader.json

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.8)

2022-07-31 15:26:59.692 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2022-07-31 15:26:59.700 [        main] INFO  Engine               -
{
	"content":{
		"reader":{
			"parameter":{
				"path":[
					"/var/tmp/a.csv.gz"
				],
				"protocol":"sftp",
				"password":"*****",
				"port":22,
				"compress":"gz",
				"host":"127.0.0.1",
				"column":[
					"*"
				],
				"encoding":"UTF-8",
				"fieldDelimiter":",",
				"username":"wgzhao"
			},
			"name":"ftpreader"
		},
		"writer":{
			"parameter":{
				"path":"/var/tmp/",
				"fileName":"out",
				"writeMode":"append",
				"fileFormat":"csv"
			},
			"name":"txtfilewriter"
		}
	},
	"setting":{
		"speed":{
			"bytes":-1,
			"channel":2
		}
	}
}

2022-07-31 15:26:59.716 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2022-07-31 15:26:59.716 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2022-07-31 15:26:59.718 [        main] INFO  JobContainer         - Set jobId = 0
2022-07-31 15:27:00.353 [       job-0] WARN  StorageWriterUtil    - 您的encoding配置为空, 将使用默认值[UTF-8]
2022-07-31 15:27:00.353 [       job-0] WARN  StorageWriterUtil    - 您没有配置列分隔符, 使用默认值[,]
2022-07-31 15:27:00.354 [       job-0] INFO  JobContainer         - Addax Reader.Job [ftpreader] do prepare work .
2022-07-31 15:27:00.356 [       job-0] INFO  FtpReader$Job        - 您即将读取的文件数为: [1]
2022-07-31 15:27:00.356 [       job-0] INFO  JobContainer         - Addax Writer.Job [txtfilewriter] do prepare work .
2022-07-31 15:27:00.357 [       job-0] INFO  TxtFileWriter$Job    - 由于您配置了writeMode append, 写入前不做清理工作, [/var/tmp/] 目录下写入相应文件名前缀 [out] 的文件
2022-07-31 15:27:00.357 [       job-0] INFO  JobContainer         - Job set Channel-Number to 2 channel(s).
2022-07-31 15:27:00.358 [       job-0] INFO  JobContainer         - Addax Reader.Job [ftpreader] splits to [1] tasks.
2022-07-31 15:27:00.358 [       job-0] INFO  StorageWriterUtil    - begin do split...
2022-07-31 15:27:00.359 [       job-0] INFO  JobContainer         - Addax Writer.Job [txtfilewriter] splits to [1] tasks.
2022-07-31 15:27:00.377 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2022-07-31 15:27:00.385 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2022-07-31 15:27:00.387 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2022-07-31 15:27:00.387 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2022-07-31 15:27:00.403 [0-0-0-writer] INFO  TxtFileWriter$Task   - begin do write...
2022-07-31 15:27:00.404 [0-0-0-writer] INFO  TxtFileWriter$Task   - write to file : [/var/tmp/out.csv]
2022-07-31 15:27:00.795 [0-0-0-reader] INFO  FtpReader$Task       - reading file : [/var/tmp/a.csv.gz]
2022-07-31 15:27:12.406 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 1137536 records, 217214432 bytes | Speed 17.26MB/s, 94794 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.098s |  All Task WaitReaderTime 6.636s | Percentage 0.00%
2022-07-31 15:27:24.419 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 2152128 records, 411944241 bytes | Speed 15.48MB/s, 84549 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.142s |  All Task WaitReaderTime 13.782s | Percentage 0.00%
2022-07-31 15:27:36.423 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 2987168 records, 572215006 bytes | Speed 12.74MB/s, 69586 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.176s |  All Task WaitReaderTime 21.406s | Percentage 0.00%
2022-07-31 15:27:48.448 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 3900864 records, 747568414 bytes | Speed 13.94MB/s, 76141 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 1.172s |  All Task WaitReaderTime 27.793s | Percentage 0.00%
2022-07-31 15:28:00.467 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 4930496 records, 945733958 bytes | Speed 15.75MB/s, 85802 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 1.214s |  All Task WaitReaderTime 34.773s | Percentage 0.00%
2022-07-31 15:28:12.479 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 7061504 records, 1356864301 bytes | Speed 32.67MB/s, 177584 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 1.318s |  All Task WaitReaderTime 48.620s | Percentage 0.00%
2022-07-31 15:28:24.498 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 8155616 records, 1567946291 bytes | Speed 16.78MB/s, 91176 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 1.355s |  All Task WaitReaderTime 55.540s | Percentage 0.00%
2022-07-31 15:28:36.512 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 9242240 records, 1777585695 bytes | Speed 16.66MB/s, 90552 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 1.394s |  All Task WaitReaderTime 62.453s | Percentage 0.00%
2022-07-31 15:28:37.115 [0-0-0-writer] INFO  TxtFileWriter$Task   - end do write
2022-07-31 15:28:39.513 [       job-0] INFO  AbstractScheduler    - Scheduler accomplished all tasks.
2022-07-31 15:28:39.514 [       job-0] INFO  JobContainer         - Addax Writer.Job [txtfilewriter] do post work.
2022-07-31 15:28:39.515 [       job-0] INFO  JobContainer         - Addax Reader.Job [ftpreader] do post work.
2022-07-31 15:28:39.517 [       job-0] INFO  JobContainer         - PerfTrace not enable!
2022-07-31 15:28:39.518 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 10000000 records, 1923775598 bytes | Speed 18.53MB/s, 101010 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 1.483s |  All Task WaitReaderTime 66.480s | Percentage 100.00%
2022-07-31 15:28:39.518 [       job-0] INFO  JobContainer         -
任务启动时刻                    : 2022-07-31 15:26:59
任务结束时刻                    : 2022-07-31 15:28:39
任务总计耗时                    :                 99s
任务平均流量                    :           18.53MB/s
记录写入速度                    :         101010rec/s
读出记录总数                    :            10000000
读写失败总数                    :                   0
```

**Comment by nmgliangwei** [comment]
@wgzhao 嗯,我怀疑是单边引号导致的
