### ISSUE TITLE
[Bug]: 示例错误

### ISSUE THREAD

**Issue by HBSpy** [wgzhao/Addax#624]
### Contact Details（联系人）

zymspy@163.com

### What happened?

文档 https://wgzhao.github.io/Addax/develop/quickstart/#_4

开始第一个采集任务 test.json 就不成功

看job下的其它文件，content 已经改成数组了，文档这里还没有

### Version

4.0.9 (Default)

### OS Type

Linux (Default)

### Java JDK Version

openjdk 17.0.3

### Relevant log output

```shell-script
:: Addax version ::    (v4.0.9)

java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "content" is null
	at com.wgzhao.addax.core.util.ConfigParser.upgradeJobConfig(ConfigParser.java:104)
	at com.wgzhao.addax.core.util.ConfigParser.parse(ConfigParser.java:55)
	at com.wgzhao.addax.core.Engine.entry(Engine.java:115)
	at com.wgzhao.addax.core.Engine.main(Engine.java:163)
```

**Comment by wgzhao** [comment]
感谢反馈，不是数组的问题，从 `4.0.9` 版本开始, `content` 可以是数组，也可以是字典了。
失败的原因是，缺少 `job` 这个关键字
