### ISSUE TITLE
[Bug]: 日志信息相关问题

### ISSUE THREAD

**Issue by weihebu** [wgzhao/Addax#638]
### Contact Details（联系人）

weihebuken@gmail.com

### What happened?

作者你好，像下面的错误信息，能不能顺带把报错的那条数据也打印出来呢？

### Version

4.0.9 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] com.wgzhao.addax.common.exception.AddaxException: Code:[Common-01], Describe:[同步数据出现业务脏数据情况，数据类型转换错误 .] - String["否"]不能转为Long .
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.common.element.StringColumn.asLong(StringColumn.java:112)
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatementColumnType(CommonRdbmsWriter.java:497)
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.fillPreparedStatement(CommonRdbmsWriter.java:456)
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:393)
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:316)
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] 	at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
2022-09-16 18:49:23 [AnalysisStatistics.analysisStatisticsLog-53] 	at java.lang.Thread.run(Thread.java:745)
2022-09-16 18:49:24 [AnalysisStatistics.analysisStatisticsLog-53] 2022-09-16 18:49:24.156 [job-0] ERROR JobContainer - 运行scheduler出错.
2022-09-16 18:49:24 [AnalysisStatistics.analysisStatisticsLog-53]
```

**Comment by wgzhao** [comment]
异常在单独的字段转换过程出现了，这种情况下，很难再返回去拿到整条记录的信息。不过我可以增加一个DEBUG级别的日志，这样如果出现异常后，使用 `bin/addax.sh -L debug <json file>` 才执行就可以获得完整的数据信息了

**Comment by LongNineSun** [comment]
@wgzhao 您好，现在用您版本的datax   hivereader支持querySql吧，可以把相关的配置样例提供一下吗？感激不尽

**Comment by wgzhao** [comment]
请参考  https://wgzhao.github.io/Addax/develop/reader/hivereader/
