### ISSUE TITLE
[Bug]: 4.0.10 encrypt_password.sh java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by HBSpy** [wgzhao/Addax#689]
### What happened?

[root@Fiammetta bin]# ./encrypt_password.sh test
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.wgzhao.addax.common.util.EncryptUtil.<clinit>(EncryptUtil.java:50)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 1 more

### Version

4.0.10 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
openjdk 17.0.4.1 2022-08-12
```

**Comment by wgzhao** [comment]
> openjdk 17.0.4.1 2022-08-12

please use jdk 1.8 instead of jdk 17

**Comment by HBSpy** [comment]
still

```
[root@Fiammetta addax]# java -version
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (build 25.345-b01, mixed mode)
[root@Fiammetta addax]# cd ..^C
[root@Fiammetta addax]# ./bin/
addax.py             addax.sh             dxprof.py            encrypt_password.sh  perftrace.py
[root@Fiammetta addax]# ./bin/encrypt_password.sh test
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.wgzhao.addax.common.util.EncryptUtil.<clinit>(EncryptUtil.java:50)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more
```

**Comment by HBSpy** [comment]
4.0.9 is just good

```
[root@Fiammetta bin]# ./addax.sh -v
Addax version 4.0.9
[root@Fiammetta bin]# ./encrypt_password.sh test
The encrypt string is : '${enc:ZhzxyGF8DfY8pzA5aFrd0A==}', you can paste it to json file.
```

**Comment by wgzhao** [comment]
you can download the two files below, unzip them, and then replace the corresponding files in addax home folder
[addax-common-4.0.11-SNAPSHOT.jar.zip](https://github.com/wgzhao/Addax/files/9937972/addax-common-4.0.11-SNAPSHOT.jar.zip)
[encrypt_password.sh.zip](https://github.com/wgzhao/Addax/files/9937975/encrypt_password.sh.zip)

**Comment by HBSpy** [comment]
it's OK!
