### ISSUE TITLE
[Bug]: 读trino出现事务问题，是否读取有开启事务？

### ISSUE THREAD

**Issue by ShawshankLin** [wgzhao/Addax#706]
### What happened?

![1669117611102](https://user-images.githubusercontent.com/16248686/203306355-527504e6-6076-4622-97eb-7cd09b9ccf73.png)

### Version

4.0.10 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
感谢反馈
请贴出完整的输出日志，不要截图

**Comment by ShawshankLin** [comment]
具体错误信息为：java.sql.SQLException: Query failed (#20221122_015241_00902_gvnhk): Unknown transaction ID: 069143b5-3586-42f0-a650-e096ab0d366c. Possibly expired? Commands ignored until end of transaction block
		at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:30) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
		at com.alibaba.datax.plugin.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:97) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]
		at com.alibaba.datax.plugin.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:220) ~[plugin-rdbms-util-0.0.1-SNAPSHOT.jar:na]


我这个是整合了Addax的插件和datax的插件到一起的用，trino这块之前是用的Addax的

**Comment by wgzhao** [comment]
我不确认是怎么把 Addax 和 DataX 集成到一块的，Addax 的读写插件严重依赖 lib 目录的下两个基础库，从你的报错信息来看，应该是没有将 lib 目录的库一并移植过去
