### ISSUE TITLE
[Bug]: MySQL 写入HDFS 使用 bigint 类型报错

### ISSUE THREAD

**Issue by 2351103450** [wgzhao/Addax#709]
### Contact Details（联系人）

2351103450@qq.com

### What happened?

- MySQL 写入HDFS 使用 bigint类型报错

### Version

4.0.8

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-13], Description:[Addax 插件运行时出错, 具体原因请参看Addax 运行结束时的错误诊断信息 .].  - java.lang.IllegalArgumentException: No enum constant org.apache.avro.Schema.Type.BIGINT
		at java.lang.Enum.valueOf(Enum.java:238)
		at org.apache.avro.Schema$Type.valueOf(Schema.java:124)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.generateParquetSchema(HdfsHelper.java:640)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:568)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:402)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
		at java.lang.Thread.run(Thread.java:748)
	 - java.lang.IllegalArgumentException: No enum constant org.apache.avro.Schema.Type.BIGINT
		at java.lang.Enum.valueOf(Enum.java:238)
		at org.apache.avro.Schema$Type.valueOf(Schema.java:124)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.generateParquetSchema(HdfsHelper.java:640)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:568)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:402)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
		at java.lang.Thread.run(Thread.java:748)
	
		at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
		at com.wgzhao.addax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:211)
		at com.wgzhao.addax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:47)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.avro.Schema.Type.BIGINT
		at java.lang.Enum.valueOf(Enum.java:238)
		at org.apache.avro.Schema$Type.valueOf(Schema.java:124)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.generateParquetSchema(HdfsHelper.java:640)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:568)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:402)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
		... 1 more
[INFO] 2022-11-28 11:58:46.505 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[202] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/7657942112320/7659809245632_20/7694/14811, processId:25254 ,exitStatusCode:0 ,processWaitForStatus:true ,processExitValue:0
[INFO] 2022-11-28 11:58:46.508 TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.shell.ShellTask:[66] -  -> [36m2022-11-28 11:58:46.302[0;39m [32m[       job-0][0;39m [1;31mERROR[0;39m [35mJobContainer        [0;39m - 运行scheduler出错.
	[36m2022-11-28 11:58:46.310[0;39m [32m[       job-0][0;39m [34mINFO [0;39m [35mStandAloneJobContainerCommunicator[0;39m - Total 512 records, 80074 bytes | Speed 78.20KB/s, 512 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.002s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
	com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-13], Description:[Addax 插件运行时出错, 具体原因请参看Addax 运行结束时的错误诊断信息 .].  - java.lang.IllegalArgumentException: No enum constant org.apache.avro.Schema.Type.BIGINT
		at java.lang.Enum.valueOf(Enum.java:238)
		at org.apache.avro.Schema$Type.valueOf(Schema.java:124)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.generateParquetSchema(HdfsHelper.java:640)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:568)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:402)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
		at java.lang.Thread.run(Thread.java:748)
	 - java.lang.IllegalArgumentException: No enum constant org.apache.avro.Schema.Type.BIGINT
		at java.lang.Enum.valueOf(Enum.java:238)
		at org.apache.avro.Schema$Type.valueOf(Schema.java:124)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.generateParquetSchema(HdfsHelper.java:640)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:568)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:402)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
		at java.lang.Thread.run(Thread.java:748)
	
		at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
		at com.wgzhao.addax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:63)
		at com.wgzhao.addax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:121)
		at com.wgzhao.addax.core.job.JobContainer.schedule(JobContainer.java:493)
		at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:137)
		at com.wgzhao.addax.core.Engine.start(Engine.java:75)
		at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
		at com.wgzhao.addax.core.Engine.main(Engine.java:163)
	Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.avro.Schema.Type.BIGINT
		at java.lang.Enum.valueOf(Enum.java:238)
		at org.apache.avro.Schema$Type.valueOf(Schema.java:124)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.generateParquetSchema(HdfsHelper.java:640)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.parquetFileStartWrite(HdfsHelper.java:568)
		at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Task.startWrite(HdfsWriter.java:402)
		at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by 2351103450** [comment]
使用 parquet 文件类型时会报错，使用ocr文件类型不会报错

**Comment by wgzhao** [comment]
parquet 类型写入用的是 [Avro](https://avro.apache.org) 库实现的，该库的[数据类型](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html) 仅为以下类型：

[ARRAY](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#ARRAY) 
[BOOLEAN](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#BOOLEAN) 
[BYTES](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#BYTES) 
[DOUBLE](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#DOUBLE) 
[ENUM](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#ENUM) 
[FIXED](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#FIXED) 
[FLOAT](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#FLOAT) 
[INT](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#INT) 
[LONG](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#LONG) 
[MAP](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#MAP) 
[NULL](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#NULL) 
[RECORD](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#RECORD) 
[STRING](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#STRING) 
[UNION](https://avro.apache.org/docs/1.8.1/api/java/org/apache/avro/Schema.Type.html#UNION)

并不包含 bigint，你用 long 类型应该可以满足你的要求
