### ISSUE TITLE
[Bug]: oracle writer long raw/blob update模式问题

### ISSUE THREAD

**Issue by wutao0914** [wgzhao/Addax#722]
### Contact Details（联系人）

wutao0914@163.com

### What happened?

操作系统：centos7.6
数据库版本：oracle 11.2.0.4.0
addax版本：4.0.11，oracle writer插件writermode为update
问题描述：
1、源表和目标表longraw字段同步照片(ID int,PHOTO long raw)
源表一条数据，当目标表有ID一样时同步成功，当目标表无数据时提示如下异常，即merge into insert异常。
2、源表和目标表blob字段同步照片(ID int,PHOTO blob)
目标表有无数据均提示如下异常。
异常信息：
java.sql.SQLRecoverableException: 关闭的连接

### Version

4.0.10 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
2023-01-17 09:31:43.268 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2023-01-17 09:31:43.268 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2023-01-17 09:31:43.270 [        main] INFO  JobContainer         - Set jobId = 0
2023-01-17 09:31:45.094 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:oracle:thin:@//192.168.137.100:1521/orcl.
2023-01-17 09:31:45.702 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[T_PHOTOS_S] has columns:[ID,PHOTO].
2023-01-17 09:31:46.750 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[T_PHOTOS_T] all columns:[ID,PHOTO].
2023-01-17 09:31:46.856 [       job-0] INFO  OriginalConfPretreatmentUtil - Write data [MERGE INTO %s A USING ( SELECT ? AS ID FROM DUAL ) TMP ON (TMP.ID = A.ID ) WHEN MATCHED THEN UPDATE SET PHOTO = ? WHEN NOT MATCHED THEN INSERT (ID,PHOTO) VALUES ( ?,? )], which jdbcUrl [jdbc:oracle:thin:@//192.168.137.100:1521/orcl]
2023-01-17 09:31:46.857 [       job-0] INFO  JobContainer         - Addax Reader.Job [oraclereader] do prepare work .
2023-01-17 09:31:46.858 [       job-0] INFO  JobContainer         - Addax Writer.Job [oraclewriter] do prepare work .
2023-01-17 09:31:46.859 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2023-01-17 09:31:46.869 [       job-0] INFO  JobContainer         - Addax Reader.Job [oraclereader] splits to [1] tasks.
2023-01-17 09:31:46.870 [       job-0] INFO  JobContainer         - Addax Writer.Job [oraclewriter] splits to [1] tasks.
2023-01-17 09:31:46.932 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2023-01-17 09:31:46.953 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2023-01-17 09:31:46.968 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2023-01-17 09:31:46.971 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2023-01-17 09:31:47.020 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select "ID","PHOTO" from T_PHOTOS_S
] jdbcUrl:[jdbc:oracle:thin:@//192.168.137.100:1521/orcl].
2023-01-17 09:31:47.339 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Finished read record by Sql: [select "ID","PHOTO" from T_PHOTOS_S
] jdbcUrl:[jdbc:oracle:thin:@//192.168.137.100:1521/orcl].
2023-01-17 09:31:47.369 [0-0-0-writer] INFO  CommonRdbmsWriter$Task - write Oracle using update(ID) mode
2023-01-17 09:31:47.559 [0-0-0-writer] WARN  CommonRdbmsWriter$Task - 回滚此次写入, 采用每次写入一行方式提交. 因为: IO 错误: 断开的管道
2023-01-17 09:31:47.563 [0-0-0-writer] ERROR WriterRunner         - Writer Runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.sql.SQLRecoverableException: 关闭的连接
        at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2089)
        at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2218)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
        at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
 - java.sql.SQLRecoverableException: 关闭的连接
        at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2089)
        at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2218)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
        at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:327)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
        at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLRecoverableException: 关闭的连接
        at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2089)
        at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2218)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
        ... 4 common frames omitted
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.sql.SQLRecoverableException: 关闭的连接
        at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2089)
        at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2218)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
        at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
 - java.sql.SQLRecoverableException: 关闭的连接
        at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2089)
        at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2218)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
        at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:327)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
        at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLRecoverableException: 关闭的连接
        at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2089)
        at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2218)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
        ... 4 more
2023-01-17 09:31:49.989 [       job-0] ERROR JobContainer         - 运行scheduler出错.
2023-01-17 09:31:49.997 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 1 records, 1298648 bytes | Speed 1.24MB/s, 1 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-05], Description:[往您配置的写入表中写入数据时失败.].  - java.sql.SQLRecoverableException: 关闭的连接
        at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2089)
        at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2218)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
        at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
 - java.sql.SQLRecoverableException: 关闭的连接
        at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2089)
        at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2218)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
        at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:327)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWrite(CommonRdbmsWriter.java:340)
        at com.wgzhao.addax.plugin.writer.oraclewriter.OracleWriter$Task.startWrite(OracleWriter.java:115)
        at com.wgzhao.addax.core.taskgroup.runner.WriterRunner.run(WriterRunner.java:81)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLRecoverableException: 关闭的连接
        at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2089)
        at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2218)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
        ... 4 more
```

**Comment by wgzhao** [comment]
感谢反馈
麻烦提供完整的日志，包括运行时的 json 配置，方便本地复现。

**Comment by wutao0914** [comment]
[json和日志.zip](https://github.com/wgzhao/Addax/files/10636563/json.zip)
@wgzhao json 配置和日志

**Comment by wgzhao** [comment]
根据你提供的任务配置，我在本地可以成功运行

测试环境：

- Oracle: Oracle 11g XE
- Addax: 4.0.10

测试步骤：

首先创建两张测试表，并在第一张表中插入一条数据

```sql
CREATE TABLE ias.T_PHOTOS_S(id int, photo LONG raw);
CREATE TABLE ias.T_PHOTOS_T(id int, photo LONG raw);
INSERT INTO ias.T_PHOTOS_S values(1, utl_raw.cast_to_raw('hello'));
```

运行你提供的 `test_longraw.json` 文件，运行结果如下：
```
bin/addax.sh test_longraw.json

  ___      _     _
 / _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.10)

2023-02-07 20:10:18.736 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2023-02-07 20:10:18.746 [        main] INFO  Engine               -
{
	"setting":{
		"speed":{
			"channel":1
		}
	},
	"content":{
		"reader":{
			"name":"oraclereader",
			"parameter":{
				"username":"ias",
				"password":"*****",
				"column":[
					"ID",
					"PHOTO"
				],
				"splitPk":"",
				"connection":[
					{
						"table":[
							"T_PHOTOS_S"
						],
						"jdbcUrl":[
							"jdbc:oracle:thin:@//xxxxxx:1521/XE"
						]
					}
				]
			}
		},
		"writer":{
			"name":"oraclewriter",
			"parameter":{
				"username":"ias",
				"password":"*****",
				"writeMode":"update(ID)",
				"column":[
					"ID",
					"PHOTO"
				],
				"connection":[
					{
						"jdbcUrl":"jdbc:oracle:thin:@//xxxxxx:13521/XE",
						"table":[
							"T_PHOTOS_T"
						]
					}
				]
			}
		}
	}
}

2023-02-07 20:10:18.766 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2023-02-07 20:10:18.766 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2023-02-07 20:10:18.767 [        main] INFO  JobContainer         - Set jobId = 0
2023-02-07 20:10:19.916 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:oracle:thin:@//xxxxx:13521/XE.
2023-02-07 20:10:20.722 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[T_PHOTOS_S] has columns:[ID,PHOTO].
2023-02-07 20:10:21.737 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[T_PHOTOS_T] all columns:[ID,PHOTO].
2023-02-07 20:10:23.366 [       job-0] INFO  OriginalConfPretreatmentUtil - Write data [MERGE INTO %s A USING ( SELECT ? AS ID FROM DUAL ) TMP ON (TMP.ID = A.ID ) WHEN MATCHED THEN UPDATE SET PHOTO = ? WHEN NOT MATCHED THEN INSERT (ID,PHOTO) VALUES ( ?,? )], which jdbcUrl [jdbc:oracle:thin:@//xxxxx:13521/XE]
2023-02-07 20:10:23.366 [       job-0] INFO  JobContainer         - Addax Reader.Job [oraclereader] do prepare work .
2023-02-07 20:10:23.367 [       job-0] INFO  JobContainer         - Addax Writer.Job [oraclewriter] do prepare work .
2023-02-07 20:10:23.367 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2023-02-07 20:10:23.370 [       job-0] INFO  JobContainer         - Addax Reader.Job [oraclereader] splits to [1] tasks.
2023-02-07 20:10:23.370 [       job-0] INFO  JobContainer         - Addax Writer.Job [oraclewriter] splits to [1] tasks.
2023-02-07 20:10:23.392 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2023-02-07 20:10:23.400 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2023-02-07 20:10:23.403 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2023-02-07 20:10:23.403 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2023-02-07 20:10:23.412 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select ID,PHOTO from T_PHOTOS_S
] jdbcUrl:[jdbc:oracle:thin:@//xxxxx:13521/XE].
2023-02-07 20:10:24.812 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Finished read record by Sql: [select ID,PHOTO from T_PHOTOS_S
] jdbcUrl:[jdbc:oracle:thin:@//xxxxxx:13521/XE].
2023-02-07 20:10:25.365 [0-0-0-writer] INFO  CommonRdbmsWriter$Task - write Oracle using update(ID) mode
2023-02-07 20:10:26.413 [       job-0] INFO  AbstractScheduler    - Scheduler accomplished all tasks.
2023-02-07 20:10:26.414 [       job-0] INFO  JobContainer         - Addax Writer.Job [oraclewriter] do post work.
2023-02-07 20:10:26.415 [       job-0] INFO  JobContainer         - Addax Reader.Job [oraclereader] do post work.
2023-02-07 20:10:26.417 [       job-0] INFO  JobContainer         - PerfTrace not enable!
2023-02-07 20:10:26.418 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 1 records, 6 bytes | Speed 2B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2023-02-07 20:10:26.419 [       job-0] INFO  JobContainer         -
任务启动时刻                    : 2023-02-07 20:10:18
任务结束时刻                    : 2023-02-07 20:10:26
任务总计耗时                    :                  7s
任务平均流量                    :                2B/s
记录写入速度                    :              0rec/s
读出记录总数                    :                   1
读写失败总数                    :                   0
```

后续分别测试了以下场景均成功：

1. T_PHOTOS_S 有数据，T_PHOTOS_T 无数据
2. T_PHOTOS_S 有数据，T_PHOTOS_T 有相同数据
3. T_PHOTOS_S 有数据，T_PHOTOS_T 有ID相同，但 photo 字段不同的数据

**Comment by wutao0914** [comment]
图片数据有问题。
