### ISSUE TITLE
[Bug]: speed 新增了byte和record参数后报错

### ISSUE THREAD

**Issue by zeusYi** [wgzhao/Addax#725]
### What happened?

配置参数：
    "setting": {
      "speed": {
        "channel": 2,
                 "byte": 100,
                 "record": 5000,
      }
    },

### Version

4.0.10 (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
2023-02-04 16:02:16.788 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2023-02-04 16:02:16.788 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2023-02-04 16:02:16.789 [        main] INFO  JobContainer         - Set jobId = 0
2023-02-04 16:02:17.573 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:mysql://10.10.20.176:3306/testdb?yearIsDateType=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&useSSL=false.
2023-02-04 16:02:17.838 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[t_user] all columns:[id,name,age,create_time,update_time].
2023-02-04 16:02:17.839 [       job-0] WARN  OriginalConfPretreatmentUtil - 您的配置文件中的列配置信息存在风险. 因为您配置的写入数据库表的列为*，当您的表字段个数、类型有变动时，可能影响任务正确性甚至会运行出错。请检查您的配置并作出修改.
2023-02-04 16:02:17.842 [       job-0] INFO  OriginalConfPretreatmentUtil - Write data [insert INTO %s ( id,name,age,create_time,update_time) VALUES ( ?,?,?,?,? )], which jdbcUrl [jdbc:mysql://10.10.20.177:3306/testdb?useSSL=false&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&tinyInt1isBit=false]
2023-02-04 16:02:17.843 [       job-0] INFO  JobContainer         - Addax Reader.Job [mysqlreader] do prepare work .
2023-02-04 16:02:17.845 [       job-0] INFO  JobContainer         - Addax Writer.Job [mysqlwriter] do prepare work .
2023-02-04 16:02:17.863 [       job-0] INFO  CommonRdbmsWriter$Job - Begin to execute preSqls:[truncate table t_user]. context info:jdbc:mysql://10.10.20.177:3306/testdb?useSSL=false&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&tinyInt1isBit=false.
2023-02-04 16:02:17.954 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-03], Description:[Addax 引擎配置错误，该问题通常是由于Addax 安装错误引起，请联系您的运维解决 .].  - 在有总bps限速条件下，单个channel的bps值不能为空，也不能为非正数
        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.core.job.JobContainer.adjustChannelNumber(JobContainer.java:427)
        at com.wgzhao.addax.core.job.JobContainer.split(JobContainer.java:390)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:135)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)
```

**Comment by wgzhao** [comment]
如果要设定 channel 的速度，你需要同时设定 `conf/core.json` 里

```json
"transport": {
    "channel": {
      "speed": {
        "byte": -1,
        "record": -1
      }
```

中 `byte` 的值为非 -1 即可

**Comment by zeusYi** [comment]
改了以后还是报错

```shell

# cat conf/core.json 
{
  "entry": {
    "jvm": "-Xms32M -Xmx1G",
    "environment": {}
  },
  "common": {
    "column": {
      "datetimeFormat": "yyyy-MM-dd HH:mm:ss",
      "timeFormat": "HH:mm:ss",
      "dateFormat": "yyyy-MM-dd",
      "extraFormats": [
        "yyyyMMdd"
      ],
      "timeZone": "PRC",
      "encoding": "utf-8"
    }
  },
  "core": {
    "server": {
      "address": "",
      "timeout": 5
    },
    "transport": {
      "channel": {
        "speed": {
          "byte": 100,
          "record": -1
        },
        "flowControlInterval": 20,
        "capacity": 512,
        "byteCapacity": 67108864
      }
    },
    "container": {
      "job": {
        "reportInterval": 10000,
        "sleepInterval": 3000
      },
      "taskGroup": {
        "channel": 5
      }
    }
  }
}

```




```log

com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-03], Description:[Addax 引擎配置错误，该问题通常是由于Addax 安装错误引起，请联系您的运维解决 .].  - 在有总tps限速条件下，单个channel的tps值不能为空，也不能为非正数
        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.core.job.JobContainer.adjustChannelNumber(JobContainer.java:442)
        at com.wgzhao.addax.core.job.JobContainer.split(JobContainer.java:390)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:135)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)
[root@host-10-10-20-176 addax]# 
```

**Comment by wgzhao** [comment]
现在的报错是 `tps` 的报错，之前是 `bps` 的报错，同样的道理，你的 job 里如果配置了 `speed.record` 参数，那么 `core.json` 里的 `speed.record` 也要配置

下面是例子：

`conf/core.json`

```json
{
  "entry": {
    "jvm": "-Xms32M -Xmx1G",
    "environment": {}
  },
  "common": {
    "column": {
      "datetimeFormat": "yyyy-MM-dd HH:mm:ss",
      "timeFormat": "HH:mm:ss",
      "dateFormat": "yyyy-MM-dd",
      "extraFormats": [
        "yyyyMMdd"
      ],
      "timeZone": "PRC",
      "encoding": "utf-8"
    }
  },
  "core": {
    "server": {
      "address": "",
      "timeout": 5
    },
    "transport": {
      "channel": {
        "speed": {
          "byte": 100,
          "record": 2000
        },
        "flowControlInterval": 20,
        "capacity": 512,
        "byteCapacity": 67108864
      }
    },
    "container": {
      "job": {
        "reportInterval": 10000,
        "sleepInterval": 3000
      },
      "taskGroup": {
        "channel": 5
      }
    }
  }
}
```

`job/job.json`

```json
{
  "job": {
    "setting": {
      "speed": {
        "byte": 100,
        "channel": 2,
        "record": 2000
      }
    },
    "content": 
      {
        "reader": {
          "name": "streamreader",
          "parameter": {
            "column": [
              {
                "value": "DataX",
                "type": "string"
              },
              {
                "value": 19890604,
                "type": "long"
              },
              {
                "value": "1989-06-04 11:22:33 123456",
                "type": "date",
		            "dateFormat": "yyyy-MM-dd HH:mm:ss SSSSSS"
              },
              {
                "value": true,
                "type": "bool"
              },
              {
                "value": "test",
                "type": "bytes"
              }
            ],
            "sliceRecordCount": 10
          }
        },
        "writer": {
          "name": "streamwriter",
          "parameter": {
            "print": true,
            "encoding": "UTF-8"
          }
        }
      }
  }
}
```

运行结果：

```
2023-02-05 10:19:40.896 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2023-02-05 10:19:40.923 [        main] INFO  Engine               - 
{
	"setting":{
		"speed":{
			"byte":100,
			"channel":2
		}
	},
	"content":{
		"reader":{
			"name":"streamreader",
			"parameter":{
				"column":[
					{
						"value":"DataX",
						"type":"string"
					},
					{
						"value":19890604,
						"type":"long"
					},
					{
						"value":"1989-06-04 11:22:33 123456",
						"type":"date",
						"dateFormat":"yyyy-MM-dd HH:mm:ss SSSSSS"
					},
					{
						"value":true,
						"type":"bool"
					},
					{
						"value":"test",
						"type":"bytes"
					}
				],
				"sliceRecordCount":10
			}
		},
		"writer":{
			"name":"streamwriter",
			"parameter":{
				"print":true,
				"encoding":"UTF-8"
			}
		}
	}
}

2023-02-05 10:19:40.955 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2023-02-05 10:19:40.955 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2023-02-05 10:19:40.956 [        main] INFO  JobContainer         - Set jobId = 0
2023-02-05 10:19:40.969 [       job-0] INFO  JobContainer         - Addax Reader.Job [streamreader] do prepare work .
2023-02-05 10:19:40.969 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] do prepare work .
2023-02-05 10:19:40.969 [       job-0] INFO  JobContainer         - Job set Max-Byte-Speed to 100 bytes.
2023-02-05 10:19:40.970 [       job-0] INFO  JobContainer         - Addax Reader.Job [streamreader] splits to [1] tasks.
2023-02-05 10:19:40.971 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] splits to [1] tasks.
2023-02-05 10:19:41.003 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2023-02-05 10:19:41.013 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2023-02-05 10:19:41.015 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to 100.
2023-02-05 10:19:41.015 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2023-02-05 10:19:44.028 [       job-0] INFO  AbstractScheduler    - Scheduler accomplished all tasks.
2023-02-05 10:19:44.029 [       job-0] INFO  JobContainer         - Addax Writer.Job [streamwriter] do post work.
2023-02-05 10:19:44.029 [       job-0] INFO  JobContainer         - Addax Reader.Job [streamreader] do post work.
2023-02-05 10:19:44.032 [       job-0] INFO  JobContainer         - PerfTrace not enable!
2023-02-05 10:19:44.034 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 10 records, 260 bytes | Speed 86B/s, 3 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2023-02-05 10:19:44.034 [       job-0] INFO  JobContainer         - 
任务启动时刻                    : 2023-02-05 10:19:40
任务结束时刻                    : 2023-02-05 10:19:44
任务总计耗时                    :                  3s
任务平均流量                    :               86B/s
记录写入速度                    :              3rec/s
读出记录总数                    :                  10
读写失败总数                    :                   0
```

**Comment by zeusYi** [comment]
有一个疑问，core.json是全局的吧？ 如果我配了这个文件，还能不能创建一个不限速的job呢？

**Comment by wgzhao** [comment]
> 有一个疑问，core.json是全局的吧？ 如果我配了这个文件，还能不能创建一个不限速的job呢？

可以的，其逻辑是，当且仅当 job 配置了限速，则 `core` 需要配置。反之则没有要求。
