### ISSUE TITLE
[Bug]: 4.0.10版本，使用kerberos时执行引擎报错

### ISSUE THREAD

**Issue by haichenleo** [wgzhao/Addax#727]
### What happened?

配置kerberos相关参数后，执行报错。相同配置文件使用原版datax不会报错

### Version

4.0.10 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
2023-02-09 14:32:14.632 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2023-02-09 14:32:14.632 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2023-02-09 14:32:14.633 [        main] INFO  JobContainer         - Set jobId = 0
2023-02-09 14:32:14.805 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[Framework-02], Description:[Addax 引擎运行过程出错，具体原因请参看Addax 运行结束时的错误诊断信息  .].  - java.lang.IndexOutOfBoundsException: position (1) must be less than the number of elements that remained (1)
        at com.google.common.collect.Iterators.get(Iterators.java:801)
        at com.google.common.collect.Iterables.get(Iterables.java:729)
        at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.getFileSystem(HdfsHelper.java:274)
        at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Job.init(HdfsWriter.java:80)
        at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:647)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:311)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:131)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)
 - java.lang.IndexOutOfBoundsException: position (1) must be less than the number of elements that remained (1)
        at com.google.common.collect.Iterators.get(Iterators.java:801)
        at com.google.common.collect.Iterables.get(Iterables.java:729)
        at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.getFileSystem(HdfsHelper.java:274)
        at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Job.init(HdfsWriter.java:80)
        at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:647)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:311)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:131)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:178)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)
Caused by: java.lang.IndexOutOfBoundsException: position (1) must be less than the number of elements that remained (1)
        at com.google.common.collect.Iterators.get(Iterators.java:801)
        at com.google.common.collect.Iterables.get(Iterables.java:729)
        at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsHelper.getFileSystem(HdfsHelper.java:274)
        at com.wgzhao.addax.plugin.writer.hdfswriter.HdfsWriter$Job.init(HdfsWriter.java:80)
        at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:647)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:311)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:131)
        ... 3 more
```

**Comment by haichenleo** [comment]
配置文件：

```json
{
    "job": {
        "setting": {
            "speed": {
                "channel": 2
            }
        },
        "content": [
            {
                "reader": {
                    "name": "streamreader",
                    "parameter": {
                        "column": [
                            {
                                "value": "Addax",
                                "type": "string"
                            },
                            {
                                "value": 19890604,
                                "type": "long"
                            },
                            {
                                "value": "1989-06-04 00:00:00",
                                "type": "date"
                            },
                            {
                                "value": true,
                                "type": "bool"
                            },
                            {
                                "value": "test",
                                "type": "bytes"
                            }
                        ],
                        "sliceRecordCount": 1000
                    }
                },
                "writer": {
                    "name": "hdfswriter",
                    "parameter": {
                        "defaultFS": "hdfs://xxxxxxx:8020",
                        "fileType": "orc",
                        "path": "/user/hive/warehouse/xxxx.db/tmp_dataxtest",
                        "fileName": "filename",
                        "column": [
                            {
                                "name": "col1",
                                "type": "string"
                            },
                            {
                                "name": "col2",
                                "type": "int"
                            },
                            {
                                "name": "col3",
                                "type": "string"
                            },
                            {
                                "name": "col4",
                                "type": "boolean"
                            },
                            {
                                "name": "col5",
                                "type": "string"
                            }
                        ],
                        "writeMode": "overwrite",
                        "fieldDelimiter": "\u0001",
                        "haveKerberos": "true",
                        "kerberosKeytabFilePath": "/home/xxxx/xxxx.keytab",
                        "kerberosPrincipal": "xxxx"
                    }
                }
            }
        ]
    }
}
```

**Comment by wgzhao** [comment]
用提供的 json 文件，本地测试无问题。

kerberos 下 HDFS  读写是一个基础功能，在我的生产环境每天要运行上千个任务，均无问题。

**Comment by haichenleo** [comment]
解决了，添加如下配置
```json
"hadoopConfig": {
        "dfs.namenode.kerberos.principal": "xxx/_HOST/@xxxx.com"
}
```
