### ISSUE TITLE
[Bug]: Error 'ORA-00972: identifier is too long' when reading oracle library data

### ISSUE THREAD

**Issue by QJG666** [wgzhao/Addax#748]
### What happened?

**Basic operating environment:**
- jdk: 1.8
- addax: 4.0.11/4.0.10

The following error occurs when I use addax 4.0.10 or addax 4.0.11 to synchronize oracle library table data:
```text
java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long
```

Incidentally, I did not report the above error when synchronizing oracle library tables with addax 4.0.7 or addax 4.0.8 or addax 4.0.9.

### Version

4.0.10 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
2023-02-22 13:46:34.644 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2023-02-22 13:46:34.645 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2023-02-22 13:46:34.645 [        main] INFO  JobContainer         - Set jobId = 0
2023-02-22 13:46:35.046 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:oracle:thin:@192.168.200.101:5566/test.
2023-02-22 13:46:35.240 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[jtf.jtf_rs_resource_extns] has columns:[RESOURCE_ID,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN,CATEGORY,RESOURCE_NUMBER,SOURCE_ID,ADDRESS_ID,CONTACT_ID,MANAGING_EMPLOYEE_ID,START_DATE_ACTIVE,END_DATE_ACTIVE,TIME_ZONE,COST_PER_HR,PRIMARY_LANGUAGE,SECONDARY_LANGUAGE,IES_AGENT_LOGIN,SERVER_GROUP_ID,ASSIGNED_TO_GROUP_ID,COST_CENTER,CHARGE_TO_COST_CENTER,COMPENSATION_CURRENCY_CODE,COMMISSIONABLE_FLAG,HOLD_REASON_CODE,HOLD_PAYMENT,COMP_SERVICE_TEAM_ID,TRANSACTION_NUMBER,OBJECT_VERSION_NUMBER,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,ATTRIBUTE_CATEGORY,USER_ID,SUPPORT_SITE_ID,LOCATION,SECURITY_GROUP_ID,SUPPORT_SITE,SOURCE_NAME,SOURCE_NUMBER,SOURCE_JOB_TITLE,SOURCE_EMAIL,SOURCE_PHONE,SOURCE_ORG_ID,SOURCE_ORG_NAME,SOURCE_ADDRESS1,SOURCE_ADDRESS2,SOURCE_ADDRESS3,SOURCE_ADDRESS4,SOURCE_CITY,SOURCE_POSTAL_CODE,SOURCE_STATE,SOURCE_PROVINCE,SOURCE_COUNTY,SOURCE_COUNTRY,SOURCE_MGR_ID,SOURCE_MGR_NAME,SOURCE_BUSINESS_GRP_ID,SOURCE_BUSINESS_GRP_NAME,SOURCE_FIRST_NAME,SOURCE_MIDDLE_NAME,SOURCE_LAST_NAME,SOURCE_CATEGORY,SOURCE_STATUS,USER_NAME,SOURCE_OFFICE,SOURCE_LOCATION,SOURCE_MAILSTOP,SOURCE_MOBILE_PHONE,SOURCE_PAGER,PERSON_PARTY_ID,SOURCE_JOB_ID,FS_SETUP_COMPLETE].
2023-02-22 13:46:35.413 [       job-0] WARN  NativeCodeLoader     - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2023-02-22 13:46:35.761 [       job-0] INFO  JobContainer         - Addax Reader.Job [oraclereader] do prepare work .
2023-02-22 13:46:35.761 [       job-0] INFO  JobContainer         - Addax Writer.Job [hdfswriter] do prepare work .
2023-02-22 13:46:35.823 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2023-02-22 13:46:35.825 [       job-0] INFO  JobContainer         - Addax Reader.Job [oraclereader] splits to [1] tasks.
2023-02-22 13:46:35.825 [       job-0] INFO  HdfsWriter$Job       - begin splitting ...
2023-02-22 13:46:35.835 [       job-0] INFO  HdfsWriter$Job       - split wrote file name:[/user/hive/warehouse/stg.db/stg_ebs_jtf_rs_resource_extns/dt=2023-02-21/.d370979f_160b_4454_8e5c_c7906358c16b/stg_ebs_jtf_rs_resource_extns_2023-02-21_20230222_134635_834_b6nq6xhn.orc]
2023-02-22 13:46:35.835 [       job-0] INFO  HdfsWriter$Job       - end splitting.
2023-02-22 13:46:35.835 [       job-0] INFO  JobContainer         - Addax Writer.Job [hdfswriter] splits to [1] tasks.
2023-02-22 13:46:35.854 [       job-0] INFO  JobContainer         - Scheduler starts [1] taskGroups.
2023-02-22 13:46:35.860 [ taskGroup-0] INFO  TaskGroupContainer   - taskGroupId=[0] start [1] channels for [1] tasks.
2023-02-22 13:46:35.862 [ taskGroup-0] INFO  Channel              - Channel set byte_speed_limit to -1, No bps activated.
2023-02-22 13:46:35.862 [ taskGroup-0] INFO  Channel              - Channel set record_speed_limit to -1, No tps activated.
2023-02-22 13:46:35.868 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Begin to read record by Sql: [select "RESOURCE_ID","CREATED_BY","CREATION_DATE","LAST_UPDATED_BY","LAST_UPDATE_DATE","LAST_UPDATE_LOGIN","CATEGORY","RESOURCE_NUMBER","SOURCE_ID","ADDRESS_ID","CONTACT_ID","MANAGING_EMPLOYEE_ID","START_DATE_ACTIVE","END_DATE_ACTIVE","TIME_ZONE","COST_PER_HR","PRIMARY_LANGUAGE","SECONDARY_LANGUAGE","IES_AGENT_LOGIN","SERVER_GROUP_ID","ASSIGNED_TO_GROUP_ID","COST_CENTER","CHARGE_TO_COST_CENTER","COMPENSATION_CURRENCY_CODE","COMMISSIONABLE_FLAG","HOLD_REASON_CODE","HOLD_PAYMENT","COMP_SERVICE_TEAM_ID","TRANSACTION_NUMBER","OBJECT_VERSION_NUMBER","ATTRIBUTE1","ATTRIBUTE2","ATTRIBUTE3","ATTRIBUTE4","ATTRIBUTE5","ATTRIBUTE6","ATTRIBUTE7","ATTRIBUTE8","ATTRIBUTE9","ATTRIBUTE10","ATTRIBUTE11","ATTRIBUTE12","ATTRIBUTE13","ATTRIBUTE14","ATTRIBUTE15","ATTRIBUTE_CATEGORY","USER_ID","SUPPORT_SITE_ID","to_char(sdo_util.to_wktgeometry(location)) as location","SECURITY_GROUP_ID","SUPPORT_SITE","SOURCE_NAME","SOURCE_NUMBER","SOURCE_JOB_TITLE","SOURCE_EMAIL","SOURCE_PHONE","SOURCE_ORG_ID","SOURCE_ORG_NAME","SOURCE_ADDRESS1","SOURCE_ADDRESS2","SOURCE_ADDRESS3","SOURCE_ADDRESS4","SOURCE_CITY","SOURCE_POSTAL_CODE","SOURCE_STATE","SOURCE_PROVINCE","SOURCE_COUNTY","SOURCE_COUNTRY","SOURCE_MGR_ID","SOURCE_MGR_NAME","SOURCE_BUSINESS_GRP_ID","SOURCE_BUSINESS_GRP_NAME","SOURCE_FIRST_NAME","SOURCE_MIDDLE_NAME","SOURCE_LAST_NAME","SOURCE_CATEGORY","SOURCE_STATUS","USER_NAME","SOURCE_OFFICE","SOURCE_LOCATION","SOURCE_MAILSTOP","SOURCE_MOBILE_PHONE","SOURCE_PAGER","PERSON_PARTY_ID","SOURCE_JOB_ID","FS_SETUP_COMPLETE" from jtf.jtf_rs_resource_extns where (1=1)
] jdbcUrl:[jdbc:oracle:thin:@192.168.200.101:5566/test].
2023-02-22 13:46:35.872 [0-0-0-writer] INFO  HdfsWriter$Task      - write to file : [/user/hive/warehouse/stg.db/stg_ebs_jtf_rs_resource_extns/dt=2023-02-21/.d370979f_160b_4454_8e5c_c7906358c16b/stg_ebs_jtf_rs_resource_extns_2023-02-21_20230222_134635_834_b6nq6xhn.orc]
2023-02-22 13:46:35.889 [0-0-0-writer] INFO  HadoopShimsCurrent   - Can't get KeyProvider for ORC encryption from hadoop.security.key.provider.path.
2023-02-22 13:46:35.925 [0-0-0-writer] INFO  PhysicalFsWriter     - ORC writer created for path: /user/hive/warehouse/stg.db/stg_ebs_jtf_rs_resource_extns/dt=2023-02-21/.d370979f_160b_4454_8e5c_c7906358c16b/stg_ebs_jtf_rs_resource_extns_2023-02-21_20230222_134635_834_b6nq6xhn.orc with stripeSize: 67108864 blockSize: 268435456 compression: Compress: SNAPPY buffer: 65536
2023-02-22 13:46:35.941 [0-0-0-reader] ERROR ReaderRunner         - Reader runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select "RESOURCE_ID","CREATED_BY","CREATION_DATE","LAST_UPDATED_BY","LAST_UPDATE_DATE","LAST_UPDATE_LOGIN","CATEGORY","RESOURCE_NUMBER","SOURCE_ID","ADDRESS_ID","CONTACT_ID","MANAGING_EMPLOYEE_ID","START_DATE_ACTIVE","END_DATE_ACTIVE","TIME_ZONE","COST_PER_HR","PRIMARY_LANGUAGE","SECONDARY_LANGUAGE","IES_AGENT_LOGIN","SERVER_GROUP_ID","ASSIGNED_TO_GROUP_ID","COST_CENTER","CHARGE_TO_COST_CENTER","COMPENSATION_CURRENCY_CODE","COMMISSIONABLE_FLAG","HOLD_REASON_CODE","HOLD_PAYMENT","COMP_SERVICE_TEAM_ID","TRANSACTION_NUMBER","OBJECT_VERSION_NUMBER","ATTRIBUTE1","ATTRIBUTE2","ATTRIBUTE3","ATTRIBUTE4","ATTRIBUTE5","ATTRIBUTE6","ATTRIBUTE7","ATTRIBUTE8","ATTRIBUTE9","ATTRIBUTE10","ATTRIBUTE11","ATTRIBUTE12","ATTRIBUTE13","ATTRIBUTE14","ATTRIBUTE15","ATTRIBUTE_CATEGORY","USER_ID","SUPPORT_SITE_ID","to_char(sdo_util.to_wktgeometry(location)) as location","SECURITY_GROUP_ID","SUPPORT_SITE","SOURCE_NAME","SOURCE_NUMBER","SOURCE_JOB_TITLE","SOURCE_EMAIL","SOURCE_PHONE","SOURCE_ORG_ID","SOURCE_ORG_NAME","SOURCE_ADDRESS1","SOURCE_ADDRESS2","SOURCE_ADDRESS3","SOURCE_ADDRESS4","SOURCE_CITY","SOURCE_POSTAL_CODE","SOURCE_STATE","SOURCE_PROVINCE","SOURCE_COUNTY","SOURCE_COUNTRY","SOURCE_MGR_ID","SOURCE_MGR_NAME","SOURCE_BUSINESS_GRP_ID","SOURCE_BUSINESS_GRP_NAME","SOURCE_FIRST_NAME","SOURCE_MIDDLE_NAME","SOURCE_LAST_NAME","SOURCE_CATEGORY","SOURCE_STATUS","USER_NAME","SOURCE_OFFICE","SOURCE_LOCATION","SOURCE_MAILSTOP","SOURCE_MOBILE_PHONE","SOURCE_PAGER","PERSON_PARTY_ID","SOURCE_JOB_ID","FS_SETUP_COMPLETE" from jtf.jtf_rs_resource_extns where (1=1) 具体错误信息为：java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
        at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:249)
        at com.wgzhao.addax.plugin.reader.oraclereader.OracleReader$Task.startRead(OracleReader.java:137)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
2023-02-22 13:46:35.945 [0-0-0-writer] INFO  WriterImpl           - ORC writer created for path: /user/hive/warehouse/stg.db/stg_ebs_jtf_rs_resource_extns/dt=2023-02-21/.d370979f_160b_4454_8e5c_c7906358c16b/stg_ebs_jtf_rs_resource_extns_2023-02-21_20230222_134635_834_b6nq6xhn.orc with stripeSize: 67108864 options: Compress: SNAPPY buffer: 65536
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select "RESOURCE_ID","CREATED_BY","CREATION_DATE","LAST_UPDATED_BY","LAST_UPDATE_DATE","LAST_UPDATE_LOGIN","CATEGORY","RESOURCE_NUMBER","SOURCE_ID","ADDRESS_ID","CONTACT_ID","MANAGING_EMPLOYEE_ID","START_DATE_ACTIVE","END_DATE_ACTIVE","TIME_ZONE","COST_PER_HR","PRIMARY_LANGUAGE","SECONDARY_LANGUAGE","IES_AGENT_LOGIN","SERVER_GROUP_ID","ASSIGNED_TO_GROUP_ID","COST_CENTER","CHARGE_TO_COST_CENTER","COMPENSATION_CURRENCY_CODE","COMMISSIONABLE_FLAG","HOLD_REASON_CODE","HOLD_PAYMENT","COMP_SERVICE_TEAM_ID","TRANSACTION_NUMBER","OBJECT_VERSION_NUMBER","ATTRIBUTE1","ATTRIBUTE2","ATTRIBUTE3","ATTRIBUTE4","ATTRIBUTE5","ATTRIBUTE6","ATTRIBUTE7","ATTRIBUTE8","ATTRIBUTE9","ATTRIBUTE10","ATTRIBUTE11","ATTRIBUTE12","ATTRIBUTE13","ATTRIBUTE14","ATTRIBUTE15","ATTRIBUTE_CATEGORY","USER_ID","SUPPORT_SITE_ID","to_char(sdo_util.to_wktgeometry(location)) as location","SECURITY_GROUP_ID","SUPPORT_SITE","SOURCE_NAME","SOURCE_NUMBER","SOURCE_JOB_TITLE","SOURCE_EMAIL","SOURCE_PHONE","SOURCE_ORG_ID","SOURCE_ORG_NAME","SOURCE_ADDRESS1","SOURCE_ADDRESS2","SOURCE_ADDRESS3","SOURCE_ADDRESS4","SOURCE_CITY","SOURCE_POSTAL_CODE","SOURCE_STATE","SOURCE_PROVINCE","SOURCE_COUNTY","SOURCE_COUNTRY","SOURCE_MGR_ID","SOURCE_MGR_NAME","SOURCE_BUSINESS_GRP_ID","SOURCE_BUSINESS_GRP_NAME","SOURCE_FIRST_NAME","SOURCE_MIDDLE_NAME","SOURCE_LAST_NAME","SOURCE_CATEGORY","SOURCE_STATUS","USER_NAME","SOURCE_OFFICE","SOURCE_LOCATION","SOURCE_MAILSTOP","SOURCE_MOBILE_PHONE","SOURCE_PAGER","PERSON_PARTY_ID","SOURCE_JOB_ID","FS_SETUP_COMPLETE" from jtf.jtf_rs_resource_extns where (1=1) 具体错误信息为：java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
        at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:249)
        at com.wgzhao.addax.plugin.reader.oraclereader.OracleReader$Task.startRead(OracleReader.java:137)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
2023-02-22 13:46:38.867 [       job-0] ERROR JobContainer         - 运行scheduler出错.
2023-02-22 13:46:38.867 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-06], Description:[执行数据库 Sql 失败, 请检查您的配置的 column/table/where/querySql或者向 DBA 寻求帮助.].  - 执行的SQL为: select "RESOURCE_ID","CREATED_BY","CREATION_DATE","LAST_UPDATED_BY","LAST_UPDATE_DATE","LAST_UPDATE_LOGIN","CATEGORY","RESOURCE_NUMBER","SOURCE_ID","ADDRESS_ID","CONTACT_ID","MANAGING_EMPLOYEE_ID","START_DATE_ACTIVE","END_DATE_ACTIVE","TIME_ZONE","COST_PER_HR","PRIMARY_LANGUAGE","SECONDARY_LANGUAGE","IES_AGENT_LOGIN","SERVER_GROUP_ID","ASSIGNED_TO_GROUP_ID","COST_CENTER","CHARGE_TO_COST_CENTER","COMPENSATION_CURRENCY_CODE","COMMISSIONABLE_FLAG","HOLD_REASON_CODE","HOLD_PAYMENT","COMP_SERVICE_TEAM_ID","TRANSACTION_NUMBER","OBJECT_VERSION_NUMBER","ATTRIBUTE1","ATTRIBUTE2","ATTRIBUTE3","ATTRIBUTE4","ATTRIBUTE5","ATTRIBUTE6","ATTRIBUTE7","ATTRIBUTE8","ATTRIBUTE9","ATTRIBUTE10","ATTRIBUTE11","ATTRIBUTE12","ATTRIBUTE13","ATTRIBUTE14","ATTRIBUTE15","ATTRIBUTE_CATEGORY","USER_ID","SUPPORT_SITE_ID","to_char(sdo_util.to_wktgeometry(location)) as location","SECURITY_GROUP_ID","SUPPORT_SITE","SOURCE_NAME","SOURCE_NUMBER","SOURCE_JOB_TITLE","SOURCE_EMAIL","SOURCE_PHONE","SOURCE_ORG_ID","SOURCE_ORG_NAME","SOURCE_ADDRESS1","SOURCE_ADDRESS2","SOURCE_ADDRESS3","SOURCE_ADDRESS4","SOURCE_CITY","SOURCE_POSTAL_CODE","SOURCE_STATE","SOURCE_PROVINCE","SOURCE_COUNTY","SOURCE_COUNTRY","SOURCE_MGR_ID","SOURCE_MGR_NAME","SOURCE_BUSINESS_GRP_ID","SOURCE_BUSINESS_GRP_NAME","SOURCE_FIRST_NAME","SOURCE_MIDDLE_NAME","SOURCE_LAST_NAME","SOURCE_CATEGORY","SOURCE_STATUS","USER_NAME","SOURCE_OFFICE","SOURCE_LOCATION","SOURCE_MAILSTOP","SOURCE_MOBILE_PHONE","SOURCE_PAGER","PERSON_PARTY_ID","SOURCE_JOB_ID","FS_SETUP_COMPLETE" from jtf.jtf_rs_resource_extns where (1=1) 具体错误信息为：java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
        at com.wgzhao.addax.rdbms.util.RdbmsException.asQueryException(RdbmsException.java:45)
        at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:249)
        at com.wgzhao.addax.plugin.reader.oraclereader.OracleReader$Task.startRead(OracleReader.java:137)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by wgzhao** [comment]
Please remove the double quotes from the field names, specifically `"to_char(sdo_util.to_wktgeometry(location)) as location"`.

If you try to execute `select to_char(sdo_util.to_wktgeometry(location)) as location" directly from jtf.jtf_rs_resource_extns where (1=1)`, you will get the  ORA-00972 error

**Comment by QJG666** [comment]
Through your answer, the problem of reporting errors has been solved. Thank you very much for your help.
