### ISSUE TITLE
[Bug]: java.lang.ArrayIndexOutOfBoundsException: 2304

### ISSUE THREAD

**Issue by denghaibin92** [wgzhao/Addax#753]
### What happened?

jdk: 1.8
addax: 4.0.11/4.0.10
The following error occurs when I use addax 4.0.10 or addax 4.0.11 to synchronize oracle library table data:

java.lang.ArrayIndexOutOfBoundsException: 2304   

### Version

4.0.10 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output
	
	java.lang.ArrayIndexOutOfBoundsException: 2304
		at com.alibaba.fastjson2.JSONWriterUTF16JDK8.writeString(JSONWriterUTF16JDK8.java:138)
		at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:401)
		at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:430)
		at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:430)
		at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:278)
		at com.alibaba.fastjson2.JSONArray.toString(JSONArray.java:872)
		at java.lang.String.valueOf(String.java:2994)
		at com.wgzhao.addax.common.util.Configuration.getString(Configuration.java:256)
		at com.wgzhao.addax.core.util.ConfigParser.upgradeJobConfig(ConfigParser.java:103)
		at com.wgzhao.addax.core.util.ConfigParser.parse(ConfigParser.java:55)
		at com.wgzhao.addax.core.Engine.entry(Engine.java:115)
		at com.wgzhao.addax.core.Engine.main(Engine.java:163)
	DataX 任务执行失败!
[INFO] 2023-02-23 11:43:22.235 +0800 - FINALIZE_SESSION

**Comment by denghaibin92** [comment]
java.lang.ArrayIndexOutOfBoundsException: 2304
		at com.alibaba.fastjson2.JSONWriterUTF16JDK8.writeString(JSONWriterUTF16JDK8.java:138)
		at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:401)
		at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:430)
		at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:430)
		at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:278)
		at com.alibaba.fastjson2.JSONArray.toString(JSONArray.java:872)
		at java.lang.String.valueOf(String.java:2994)
		at com.wgzhao.addax.common.util.Configuration.getString(Configuration.java:256)
		at com.wgzhao.addax.core.util.ConfigParser.upgradeJobConfig(ConfigParser.java:103)
		at com.wgzhao.addax.core.util.ConfigParser.parse(ConfigParser.java:55)
		at com.wgzhao.addax.core.Engine.entry(Engine.java:115)
		at com.wgzhao.addax.core.Engine.main(Engine.java:163)
	DataX 任务执行失败!
[INFO] 2023-02-23 11:43:22.235 +0800 - FINALIZE_SESSION

**Comment by wgzhao** [comment]
Please paste the complete console output

**Comment by denghaibin92** [comment]
11:43:22,033 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [/opt/app/addax-4.0.11/log//addax_sync_full_ekp_ekp_lease_fixed_price_main_20230223_114321_51324.log]
	11:43:22,034 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
	11:43:22,034 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
	11:43:22,034 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [FILE] to Logger[ROOT]
	11:43:22,034 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@3632be31 - End of configuration.
	11:43:22,035 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5abca1e0 - Registering current configuration as safe fallback point
	
	
	  ___      _     _            
	 / _ \    | |   | |           
	/ /_\ \ __| | __| | __ ___  __
	|  _  |/ _` |/ _` |/ _` \ \/ /
	| | | | (_| | (_| | (_| |>  < 
	\_| |_/\__,_|\__,_|\__,_/_/\_\
	
	:: Addax version ::    (v4.0.11)
	
	java.lang.ArrayIndexOutOfBoundsException: 2304
		at com.alibaba.fastjson2.JSONWriterUTF16JDK8.writeString(JSONWriterUTF16JDK8.java:138)
		at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:401)
		at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:430)
		at com.alibaba.fastjson2.writer.ObjectWriterImplMap.write(ObjectWriterImplMap.java:430)
		at com.alibaba.fastjson2.writer.ObjectWriterImplList.write(ObjectWriterImplList.java:278)
		at com.alibaba.fastjson2.JSONArray.toString(JSONArray.java:872)
		at java.lang.String.valueOf(String.java:2994)
		at com.wgzhao.addax.common.util.Configuration.getString(Configuration.java:256)
		at com.wgzhao.addax.core.util.ConfigParser.upgradeJobConfig(ConfigParser.java:103)
		at com.wgzhao.addax.core.util.ConfigParser.parse(ConfigParser.java:55)
		at com.wgzhao.addax.core.Engine.entry(Engine.java:115)
		at com.wgzhao.addax.core.Engine.main(Engine.java:163)
	DataX 任务执行失败!
[INFO] 2023-02-23 11:43:22.235 +0800 - FINALIZE_SESSION

**Comment by denghaibin92** [comment]
怀疑fastjson2 格式化问题，在Configuration.java下fastjson2 替换为fastjon 不会有异常。

**Comment by wgzhao** [comment]
请贴出完整的日志

**Comment by denghaibin92** [comment]
上面的这就是完整日志，是字段含有数字加字符，导致异常 。

**Comment by denghaibin92** [comment]
上面的这就是完整日志，是字段含有数字加字符，导致异常 。
