### ISSUE TITLE
[Bug]: mysqlwriter plug-in: An error occurs when the database name contains '-' characters in the jdbc string

### ISSUE THREAD

**Issue by QJG666** [wgzhao/Addax#796]
### What happened?

Version information
- addax v4.0.13-SNAPSHOT

An error occurred while I was synchronizing oracle data to mysql

### Version

4.0.12 (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
/ _ \    | |   | |
/ /_\ \ __| | __| | __ ___  __
|  _  |/ _` |/ _` |/ _` \ \/ /
| | | | (_| | (_| | (_| |>  <
\_| |_/\__,_|\__,_|\__,_/_/\_\

:: Addax version ::    (v4.0.13-SNAPSHOT)

2023-04-17 14:58:48.289 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2023-04-17 14:58:48.304 [        main] INFO  Engine               -
{
        "setting":{
                "speed":{
                        "channel":1
                }
        },
        "content":{
                "reader":{
                        "name":"oraclereader",
                        "parameter":{
                                "column":[
                                        "SOURCE_ID",
                                        "LEDGER_NAME",
                                        "OU_NAME",
                                        "ORG_ID",
                                        "INV_NAME",
                                        "BUYER",
                                        "TERM_NAME",
                                        "PAY_METHOD",
                                        "TRANSACTION_DATE",
                                        "PO_NUM",
                                        "WAREHOUSE_NUM",
                                        "DELIVERY_NUM",
                                        "ITEM_NUM",
                                        "ITEM_DESC",
                                        "PRIMARY_UNIT_OF_MEASURE",
                                        "QUANTITY",
                                        "QUANTITY_INVOICED",
                                        "NORAT_AMOUNT",
                                        "AMOUNT",
                                        "CURRENCY_CODE",
                                        "VENDOR_NAME",
                                        "TAX_RATE",
                                        "TAX_CODE",
                                        "UNIT_PRICE",
                                        "MARKET_PRICE",
                                        "CONTACT_PERSON",
                                        "CONTACT_PHONE",
                                        "DELIVERY_TYPE",
                                        "AP_ATTRIBUTE1",
                                        "AP_ATTRIBUTE2",
                                        "AP_ATTRIBUTE3",
                                        "PR_REMARK",
                                        "COMMENTS",
                                        "PO_CLOSE_STATUS",
                                        "VENDOR_ID",
                                        "VENDOR_NUMBER",
                                        "VENDOR_SITE_ID",
                                        "TERMS_ID",
                                        "PAY_METHOD_CODE",
                                        "PO_HEADER_ID",
                                        "PO_LINE_ID",
                                        "PO_LINE_LOCATION_ID",
                                        "RCV_RECEIPT_NUM",
                                        "RCV_LINE_NUM",
                                        "CREATION_DATE",
                                        "CREATED_BY",
                                        "LAST_UPDATED_BY",
                                        "LAST_UPDATE_DATE",
                                        "PROCESS_STATUS",
                                        "PROCESS_MSG",
                                        "RCV_UPDATE_DATE",
                                        "DECLARE_NO",
                                        "DOMESTIC_RECEIVER",
                                        "TRADE_MODE"
                                ],
                                "connection":[
                                        {
                                                "jdbcUrl":[
                                                        "jdbc:oracle:thin:@192.168.232.201:1521:uat"
                                                ],
                                                "table":[
                                                        "cux.cux_sccp_ap_lines_t"
                                                ]
                                        }
                                ],
                                "password":"*****",
                                "username":"ebsread",
                                "splitPk":"SOURCE_ID",
                                "where":"1=1",
                                "partitionCol":"",
                                "PartitionByCol":""
                        }
                },
                "writer":{
                        "name":"mysqlwriter",
                        "parameter":{
                                "writeMode":"insert",
                                "username":"root",
                                "password":"*****",
                                "column":[
                                        "SOURCE_ID",
                                        "LEDGER_NAME",
                                        "OU_NAME",
                                        "ORG_ID",
                                        "INV_NAME",
                                        "BUYER",
                                        "TERM_NAME",
                                        "PAY_METHOD",
                                        "TRANSACTION_DATE",
                                        "PO_NUM",
                                        "WAREHOUSE_NUM",
                                        "DELIVERY_NUM",
                                        "ITEM_NUM",
                                        "ITEM_DESC",
                                        "PRIMARY_UNIT_OF_MEASURE",
                                        "QUANTITY",
                                        "QUANTITY_INVOICED",
                                        "NORAT_AMOUNT",
                                        "AMOUNT",
                                        "CURRENCY_CODE",
                                        "VENDOR_NAME",
                                        "TAX_RATE",
                                        "TAX_CODE",
                                        "UNIT_PRICE",
                                        "MARKET_PRICE",
                                        "CONTACT_PERSON",
                                        "CONTACT_PHONE",
                                        "DELIVERY_TYPE",
                                        "AP_ATTRIBUTE1",
                                        "AP_ATTRIBUTE2",
                                        "AP_ATTRIBUTE3",
                                        "PR_REMARK",
                                        "COMMENTS",
                                        "PO_CLOSE_STATUS",
                                        "VENDOR_ID",
                                        "VENDOR_NUMBER",
                                        "VENDOR_SITE_ID",
                                        "TERMS_ID",
                                        "PAY_METHOD_CODE",
                                        "PO_HEADER_ID",
                                        "PO_LINE_ID",
                                        "PO_LINE_LOCATION_ID",
                                        "RCV_RECEIPT_NUM",
                                        "RCV_LINE_NUM",
                                        "CREATION_DATE",
                                        "CREATED_BY",
                                        "LAST_UPDATED_BY",
                                        "LAST_UPDATE_DATE",
                                        "PROCESS_STATUS",
                                        "PROCESS_MSG",
                                        "RCV_UPDATE_DATE",
                                        "DECLARE_NO",
                                        "DOMESTIC_RECEIVER",
                                        "TRADE_MODE"
                                ],
                                "preSql":[
                                        "truncate table settle-center-uat.erp_settle_record"
                                ],
                                "connection":[
                                        {
                                                "jdbcUrl":"jdbc:mysql://192.168.232.201:3306/settle-center-uat?useUnicode=true&characterEncoding=UTF-8&useSSL=false&yearIsDateType=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&tinyInt1isBit=false",
                                                "table":[
                                                        "settle-center-uat.erp_settle_record"
                                                ],
                                                "driver":"com.mysql.cj.jdbc.Driver"
                                        }
                                ]
                        }
                }
        }
}

2023-04-17 14:58:48.319 [        main] INFO  PerfTrace            - PerfTrace traceId=job_-1, isEnable=false, priority=0
2023-04-17 14:58:48.320 [        main] INFO  JobContainer         - Addax jobContainer starts job.
2023-04-17 14:58:48.320 [        main] INFO  JobContainer         - Set jobId = 0
2023-04-17 14:58:48.804 [       job-0] INFO  OriginalConfPretreatmentUtil - Available jdbcUrl:jdbc:oracle:thin:@192.168.12.161:1521:uat.
2023-04-17 14:58:48.998 [       job-0] INFO  OriginalConfPretreatmentUtil - table:[cux.cux_sccp_ap_lines_t] has columns:[SOURCE_ID,LEDGER_NAME,OU_NAME,ORG_ID,INV_NAME,BUYER,TERM_NAME,PAY_METHOD,TRANSACTION_DATE,PO_NUM,WAREHOUSE_NUM,DELIVERY_NUM,ITEM_NUM,ITEM_DESC,PRIMARY_UNIT_OF_MEASURE,QUANTITY,QUANTITY_INVOICED,NORAT_AMOUNT,AMOUNT,CURRENCY_CODE,VENDOR_NAME,TAX_RATE,TAX_CODE,UNIT_PRICE,MARKET_PRICE,CONTACT_PERSON,CONTACT_PHONE,DELIVERY_TYPE,AP_ATTRIBUTE1,AP_ATTRIBUTE2,AP_ATTRIBUTE3,PR_REMARK,COMMENTS,PO_CLOSE_STATUS,VENDOR_ID,VENDOR_NUMBER,VENDOR_SITE_ID,TERMS_ID,PAY_METHOD_CODE,PO_HEADER_ID,PO_LINE_ID,PO_LINE_LOCATION_ID,RCV_RECEIPT_NUM,RCV_LINE_NUM,CREATION_DATE,CREATED_BY,LAST_UPDATED_BY,LAST_UPDATE_DATE,PROCESS_STATUS,PROCESS_MSG,RCV_UPDATE_DATE,DECLARE_NO,DOMESTIC_RECEIVER,TRADE_MODE].
2023-04-17 14:58:49.004 [       job-0] WARN  OriginalConfPretreatmentUtil - use specified driver class: com.mysql.cj.jdbc.Driver
2023-04-17 14:58:49.189 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: Code:[DBUtilErrorCode-01], Description:[获取表字段相关信息失败.].  - 获取表:settle-center-uat.erp_settle_record 的字段的元信息时失败. 请联系 DBA 核查该库、表信息. - java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-center-uat.erp_settle_record WHERE 1 = 2' at line 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1201)
        at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
        at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
        at com.wgzhao.addax.rdbms.util.DBUtil.getColumnMetaData(DBUtil.java:424)
        at com.wgzhao.addax.rdbms.util.DBUtil.getTableColumnsByConn(DBUtil.java:394)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:145)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:181)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:70)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:67)
        at com.wgzhao.addax.plugin.writer.mysqlwriter.MysqlWriter$Job.init(MysqlWriter.java:57)
        at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:647)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:311)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:131)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:58)
        at com.wgzhao.addax.rdbms.util.DBUtil.getColumnMetaData(DBUtil.java:439)
        at com.wgzhao.addax.rdbms.util.DBUtil.getTableColumnsByConn(DBUtil.java:394)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:145)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:181)
        at com.wgzhao.addax.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:70)
        at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:67)
        at com.wgzhao.addax.plugin.writer.mysqlwriter.MysqlWriter$Job.init(MysqlWriter.java:57)
        at com.wgzhao.addax.core.job.JobContainer.initJobWriter(JobContainer.java:647)
        at com.wgzhao.addax.core.job.JobContainer.init(JobContainer.java:311)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:131)
        at com.wgzhao.addax.core.Engine.start(Engine.java:75)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:132)
        at com.wgzhao.addax.core.Engine.main(Engine.java:163)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-center-uat.erp_settle_record WHERE 1 = 2' at line 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1201)
        at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
        at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
        at com.wgzhao.addax.rdbms.util.DBUtil.getColumnMetaData(DBUtil.java:424)
        ... 12 more
```

**Comment by wgzhao** [comment]
This is because your MySQL does not support database names containing hyphens (-). You can connect to the database using the MySQL client and execute "create database settle-center-uat". This should result in the following error message: 
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-center-uat' at line 1
```

If your database name must contain hyphens (-), you can enclose it with backticks (```) as shown below:

```sql
mysql> create database settle-center-uat;
Query OK, 1 row affected (0.00 sec)
```
Therefore, you can modify the following configuration accordingly.

```
"table":[  "settle-center-uat.erp_settle_record"  ]
```
into
```
"table":[  "`settle-center-uat`.`erp_settle_record`"  ]
```

**Comment by QJG666** [comment]
Thanks for answering your questions.
