### ISSUE TITLE
[Bug]: hdfsReader to clickhouse 出现 jackson/databind  NoClassDefFoundError 

### ISSUE THREAD

**Issue by ekeyme** [wgzhao/Addax#849]
### What happened?

- java   -version

```
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

```

- Addax Version: `4.1.1`

- OS: `CentOS Linux release 7.7.1908 (Core)`

问题：

使用 hdfsReader 同步 hive表到 clickhouse, 报缺 jackson/databind 包。

期待：

没有该错误。

### Version

4.1.1 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

### Relevant log output

```shell-script
2023-07-24 11:35:22.385 [        main] INFO  Engine               - 
{
        "content":{
                "reader":{
                        "name":"hdfsreader",
                        "parameter":{
                                "column":[
                                        {
                                                "index":0,
                                                "type":"long"
                                        },
                                        {
                                                "index":1,
                                                "type":"string"
                                        },
                                        {
                                                "index":2,
                                                "type":"double"
                                        }
                                ],
                                "defaultFS":"hdfs://hdfsunity",
                                "fileType":"PARQUET",
                                "hadoopConfig":{
                                        ...
                                        "dfs.nameservices":"hdfsunity",
                                        "fs.defaultFS":"hdfs://hdfsunity"
                                },
                                "haveKerberos":true,
                                "kerberosKeytabFilePath":"/home/dev/*****.keytab",
                                "kerberosKrb5FilePath":"/home/dev/krb5.conf",
                                "kerberosPrincipal":"*****@*****.****.******",
                                "path":"/data/*****/hive/warehouse/tmp_*****.db/xxxxxxxxx_to_delete"
                        }
                },
                "writer":{
                        "name":"clickhousewriter",
                        "parameter":{
                                "column":[
                                        "user_id",
                                        "name",
                                        "age"
                                ],
                                "connection":[
                                        {
                                                "jdbcUrl":"jdbc:clickhouse://******:25001/********",
                                                "table":[
                                                        "xxxxxxxxx_to_delete"
                                                ]
                                        }
                                ],
                                "password":"*****",
                                "username":"*****"
                        }
                }
        },
        "setting":{
                "errorLimit":{
                        "percentage":0,
                        "record":0
                }
        }
}

2023-07-24 11:35:22.404 [        main] INFO  JobContainer         - The jobContainer begins to process the job.
2023-07-24 11:35:22.416 [       job-0] INFO  HdfsReader$Job       - init() begin...
2023-07-24 11:35:22.609 [       job-0] WARN  NativeCodeLoader     - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2023-07-24 11:35:22.861 [       job-0] INFO  UserGroupInformation - Login successful for user dev_****@*****.****.****** using keytab file /home/dev/dev_****.keytab
2023-07-24 11:35:22.900 [       job-0] INFO  HdfsReader$Job       - init() ok and end...
2023-07-24 11:35:23.221 [       job-0] INFO  OriginalConfPretreatmentUtil - The table [xxxxxxxxx_to_delete] has columns [user_id,name,age].
2023-07-24 11:35:23.244 [       job-0] INFO  OriginalConfPretreatmentUtil - Writing data using [INSERT INTO %s ( user_id,name,age) VALUES ( ?,?,? )].
2023-07-24 11:35:23.245 [       job-0] INFO  JobContainer         - The Reader.Job [hdfsreader] perform prepare work .
2023-07-24 11:35:23.245 [       job-0] INFO  HdfsReader$Job       - prepare(), start to getAllFiles...
2023-07-24 11:35:23.245 [       job-0] INFO  DFSUtil              - get HDFS all files in path = [/data/dev_****/hive/warehouse/tmp_dev_****.db/xxxxxxxxx_to_delete]
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2023-07-24 11:35:24.271 [       job-0] INFO  InternalParquetRecordReader - RecordReader initialized will read a total of 1 records.
2023-07-24 11:35:24.271 [       job-0] INFO  InternalParquetRecordReader - at row 0. reading next block
2023-07-24 11:35:24.295 [       job-0] INFO  InternalParquetRecordReader - block read in memory in 24 ms. row count = 1
2023-07-24 11:35:24.443 [       job-0] INFO  DFSUtil              - The file [hdfs://hdfsunity/data/dev_****/hive/warehouse/tmp_dev_****.db/xxxxxxxxx_to_delete/000000_0] format is [PARQUET], add it to source files list.
2023-07-24 11:35:24.443 [       job-0] INFO  HdfsReader$Job       - It will reading #1 file(s), including [[hdfs://hdfsunity/data/dev_****/hive/warehouse/tmp_dev_****.db/xxxxxxxxx_to_delete/000000_0]}.
2023-07-24 11:35:24.444 [       job-0] INFO  JobContainer         - The Writer.Job [clickhousewriter] perform prepare work .
2023-07-24 11:35:24.444 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2023-07-24 11:35:24.444 [       job-0] INFO  HdfsReader$Job       - split() begin...
2023-07-24 11:35:24.452 [       job-0] INFO  JobContainer         - The Reader.Job [hdfsreader] is divided into [1] task(s).
2023-07-24 11:35:24.452 [       job-0] INFO  JobContainer         - The Writer.Job [clickhousewriter] is divided into [1] task(s).
2023-07-24 11:35:24.459 [       job-0] INFO  JobContainer         - The Scheduler launches [1] taskGroup(s).
2023-07-24 11:35:24.470 [ taskGroup-0] INFO  TaskGroupContainer   - The taskGroupId=[0] started [1] channels for [1] tasks.
2023-07-24 11:35:24.473 [ taskGroup-0] INFO  Channel              - The Channel set byte_speed_limit to -1, No bps activated.
2023-07-24 11:35:24.474 [ taskGroup-0] INFO  Channel              - The Channel set record_speed_limit to -1, No tps activated.
2023-07-24 11:35:24.499 [  reader-0-0] INFO  UserGroupInformation - Login successful for user dev_****@*****.****.****** using keytab file /home/dev/dev_****.keytab
2023-07-24 11:35:24.500 [  reader-0-0] INFO  HdfsReader$Task      - Being to read.
2023-07-24 11:35:24.501 [  reader-0-0] INFO  HdfsReader$Task      - Reading the file [hdfs://hdfsunity/data/dev_****/hive/warehouse/tmp_dev_****.db/xxxxxxxxx_to_delete/000000_0]
2023-07-24 11:35:24.501 [  reader-0-0] INFO  DFSUtil              - Begin to read the parquet-file [hdfs://hdfsunity/data/dev_****/hive/warehouse/tmp_dev_****.db/xxxxxxxxx_to_delete/000000_0].
2023-07-24 11:35:24.524 [  reader-0-0] ERROR ReaderRunner         - Reader runner Received Exceptions:
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
        at org.apache.avro.generic.GenericData.<clinit>(GenericData.java:1207)
        at com.wgzhao.addax.plugin.reader.hdfsreader.DFSUtil.parquetFileStartRead(DFSUtil.java:486)
        at com.wgzhao.addax.plugin.reader.hdfsreader.HdfsReader$Task.startRead(HdfsReader.java:277)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonNode
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 common frames omitted
Exception in thread "taskGroup-0" com.wgzhao.addax.common.exception.AddaxException: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
        at org.apache.avro.generic.GenericData.<clinit>(GenericData.java:1207)
        at com.wgzhao.addax.plugin.reader.hdfsreader.DFSUtil.parquetFileStartRead(DFSUtil.java:486)
        at com.wgzhao.addax.plugin.reader.hdfsreader.HdfsReader$Task.startRead(HdfsReader.java:277)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonNode
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.taskgroup.TaskGroupContainer.start(TaskGroupContainer.java:188)
        at com.wgzhao.addax.core.taskgroup.runner.TaskGroupContainerRunner.run(TaskGroupContainerRunner.java:44)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
        at org.apache.avro.generic.GenericData.<clinit>(GenericData.java:1207)
        at com.wgzhao.addax.plugin.reader.hdfsreader.DFSUtil.parquetFileStartRead(DFSUtil.java:486)
        at com.wgzhao.addax.plugin.reader.hdfsreader.HdfsReader$Task.startRead(HdfsReader.java:277)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonNode
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more
2023-07-24 11:35:27.477 [       job-0] ERROR JobContainer         - The scheduler failed to run.
2023-07-24 11:35:27.480 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
com.wgzhao.addax.common.exception.AddaxException: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
        at org.apache.avro.generic.GenericData.<clinit>(GenericData.java:1207)
        at com.wgzhao.addax.plugin.reader.hdfsreader.DFSUtil.parquetFileStartRead(DFSUtil.java:486)
        at com.wgzhao.addax.plugin.reader.hdfsreader.HdfsReader$Task.startRead(HdfsReader.java:277)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonNode
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

        at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:66)
        at com.wgzhao.addax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:63)
        at com.wgzhao.addax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:107)
        at com.wgzhao.addax.core.job.JobContainer.schedule(JobContainer.java:440)
        at com.wgzhao.addax.core.job.JobContainer.start(JobContainer.java:128)
        at com.wgzhao.addax.core.Engine.start(Engine.java:61)
        at com.wgzhao.addax.core.Engine.entry(Engine.java:112)
        at com.wgzhao.addax.core.Engine.main(Engine.java:139)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
        at org.apache.avro.generic.GenericData.<clinit>(GenericData.java:1207)
        at com.wgzhao.addax.plugin.reader.hdfsreader.DFSUtil.parquetFileStartRead(DFSUtil.java:486)
        at com.wgzhao.addax.plugin.reader.hdfsreader.HdfsReader$Task.startRead(HdfsReader.java:277)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonNode
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more
2023-07-24 11:35:27.480 [       job-0] ERROR Engine               - com.wgzhao.addax.common.exception.AddaxException: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonNode
        at org.apache.avro.generic.GenericData.<clinit>(GenericData.java:1207)
        at com.wgzhao.addax.plugin.reader.hdfsreader.DFSUtil.parquetFileStartRead(DFSUtil.java:486)
        at com.wgzhao.addax.plugin.reader.hdfsreader.HdfsReader$Task.startRead(HdfsReader.java:277)
        at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonNode
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more
```

**Comment by ekeyme** [comment]
看到依赖上有 专门 excluded ackson-databind 的jar, 好奇开发的时候没有遇到这个错误。

```
           <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>${hadoop.common.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
```

**Comment by wgzhao** [comment]
感谢反馈
这里特意排除时因为内嵌的 jackson 有高危漏洞，需要单独引入，这里估计是忘记引入了。
我稍后处理
