### ISSUE TITLE
oracle在使用"writeMode": "update(id)"模式下写入，表有clob大字段时报错[Bug]: 

### ISSUE THREAD

**Issue by zxf5570** [wgzhao/Addax#905]
### What happened?

oracle在使用"writeMode": "update(id)"模式下写入，表有clob大字段时报错，
Rolling back the write, try to write one line at a time. because: IO 错误
Caused by: java.sql.SQLRecoverableException: 关闭的连接
	at oracle.jdbc.driver.PhysicalConnection.getAutoCommit(PhysicalConnection.java:2089)
	at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2218)
	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:781)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.doBatchInsert(CommonRdbmsWriter.java:408)
	at com.wgzhao.addax.rdbms.writer.CommonRdbmsWriter$Task.startWriteWithConnection(CommonRdbmsWriter.java:322)
	... 4 common frames omitted

### Version

4.1.1 (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
感谢反馈
请给出任务执行的完整输出，谢谢

**Comment by zxf5570** [comment]
[addax_jobjobTmp-a5462963a8cb422ab2efd2b6b83b5673_20230906_181346_20052.log](https://github.com/wgzhao/Addax/files/12543440/addax_jobjobTmp-a5462963a8cb422ab2efd2b6b83b5673_20230906_181346_20052.log)

**Comment by wgzhao** [comment]
从字段命名来看， `FILE_BLOB` 这个字段应该是 `BLOB` 类型而不是 `CLOB` 类型吧，麻烦给出表 `TESTQW` 的建表语句，我这边看能否复现

**Comment by zxf5570** [comment]
CREATE TABLE "TESTQW" (
  "FILE_ID" VARCHAR2(38 ) NOT NULL,
  "SET_YEAR" NVARCHAR2(4),
  "MOF_DIV_CODE" NVARCHAR2(9),
  "MOF_DIV_NAME" VARCHAR2(360 ),
  "DW_CODE" VARCHAR2(30 ),
  "DW_NAME" VARCHAR2(300 ),
  "FILE_NAME" VARCHAR2(600 ),
  "FULL_PATH" VARCHAR2(300 ),
  "FILE_BLOB" BLOB,
  "REPORT_TYPE" VARCHAR2(6 ),
  "UPDATE_TIME" DATE,
  "IS_DELETED" NUMBER(1,0) NOT NULL,
  "CREATE_TIME" DATE,
  "IS_LAST_INST" NUMBER(1,0),
  "SEND_DATE" DATE NOT NULL
)

**Comment by wgzhao** [comment]
我本次测试了没有复现你的情况，我使用 `streamreader` 生成数据，写入到 Oracle 11g XE 版本中。下面是执行的日志

```
2023-09-13 15:47:35.486 [        main] INFO  VMInfo               - VMInfo# operatingSystem class => sun.management.OperatingSystemImpl
2023-09-13 15:47:35.500 [        main] INFO  Engine               - 
{
	"content":{
		"reader":{
			"name":"streamreader",
			"parameter":{
				"column":[
					{
						"value":"2023-09-13 12:13:14",
						"type":"date"
					},
					{
						"value":"1234",
						"type":"string"
					},
					{
						"value":"dw name version 2",
						"type":"string"
					},
					{
						"value":"file content version 2",
						"type":"string"
					},
					{
						"incr":"1,1",
						"type":"long"
					},
					{
						"value":"file name",
						"type":"string"
					},
					{
						"value":"full path",
						"type":"string"
					}
				],
				"sliceRecordCount":10
			}
		},
		"writer":{
			"name":"oraclewriter",
			"parameter":{
				"column":[
					"CREATE_TIME",
					"DW_CODE",
					"DW_NAME",
					"FILE_BLOB",
					"FILE_ID",
					"FILE_NAME",
					"FULL_PATH"
				],
				"connection":[
					{
						"jdbcUrl":"jdbc:oracle:thin:@10.90.71.89:13521/XE",
						"table":[
							"HR.TESTQW"
						]
					}
				],
				"username":"system",
				"password":"*****",
				"writeMode":"update(FILE_ID)"
			}
		}
	},
	"setting":{
		"speed":{
			"bytes":-1,
			"channel":1
		}
	}
}

2023-09-13 15:47:35.522 [        main] INFO  JobContainer         - The jobContainer begins to process the job.
2023-09-13 15:47:38.334 [       job-0] INFO  OriginalConfPretreatmentUtil - The table [HR.TESTQW] has columns [FILE_ID,DW_CODE,DW_NAME,FILE_NAME,FULL_PATH,FILE_BLOB,CREATE_TIME].
2023-09-13 15:47:39.613 [       job-0] INFO  OriginalConfPretreatmentUtil - Writing data using [MERGE INTO %s A USING ( SELECT ? AS FILE_ID FROM DUAL ) TMP ON (TMP.FILE_ID = A.FILE_ID ) WHEN MATCHED THEN UPDATE SET CREATE_TIME = ?,DW_CODE = ?,DW_NAME = ?,FILE_BLOB = ?,FILE_NAME = ?,FULL_PATH = ? WHEN NOT MATCHED THEN INSERT (CREATE_TIME,DW_CODE,DW_NAME,FILE_BLOB,FILE_ID,FILE_NAME,FULL_PATH) VALUES ( ?,?,?,?,?,?,? )].
2023-09-13 15:47:39.614 [       job-0] INFO  JobContainer         - The Reader.Job [streamreader] perform prepare work .
2023-09-13 15:47:39.615 [       job-0] INFO  JobContainer         - The Writer.Job [oraclewriter] perform prepare work .
2023-09-13 15:47:39.615 [       job-0] INFO  JobContainer         - Job set Channel-Number to 1 channel(s).
2023-09-13 15:47:39.616 [       job-0] INFO  JobContainer         - The Reader.Job [streamreader] is divided into [1] task(s).
2023-09-13 15:47:39.616 [       job-0] INFO  JobContainer         - The Writer.Job [oraclewriter] is divided into [1] task(s).
2023-09-13 15:47:39.640 [       job-0] INFO  JobContainer         - The Scheduler launches [1] taskGroup(s).
2023-09-13 15:47:39.654 [ taskGroup-0] INFO  TaskGroupContainer   - The taskGroupId=[0] started [1] channels for [1] tasks.
2023-09-13 15:47:39.656 [ taskGroup-0] INFO  Channel              - The Channel set byte_speed_limit to -1, No bps activated.
2023-09-13 15:47:39.657 [ taskGroup-0] INFO  Channel              - The Channel set record_speed_limit to -1, No tps activated.
2023-09-13 15:47:51.677 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 10 records, 770 bytes | Speed 64B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2023-09-13 15:48:03.694 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 10 records, 770 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2023-09-13 15:48:15.713 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 10 records, 770 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2023-09-13 15:48:27.722 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 10 records, 770 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2023-09-13 15:48:39.737 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 10 records, 770 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
2023-09-13 15:48:49.314 [  writer-0-0] INFO  CommonRdbmsWriter$Task - write Oracle using update(FILE_ID) mode
2023-09-13 15:48:51.750 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 10 records, 770 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2023-09-13 15:48:51.751 [       job-0] INFO  AbstractScheduler    - The scheduler has completed all tasks.
2023-09-13 15:48:51.751 [       job-0] INFO  JobContainer         - The Writer.Job [oraclewriter] perform post work.
2023-09-13 15:48:51.751 [       job-0] INFO  JobContainer         - The Reader.Job [streamreader] perform post work.
2023-09-13 15:48:51.753 [       job-0] INFO  StandAloneJobContainerCommunicator - Total 10 records, 770 bytes | Speed 10B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 100.00%
2023-09-13 15:48:51.754 [       job-0] INFO  JobContainer         - The jobResultReportUrl: http://localhost:5001/fsapi/addax/v1/jobReport
2023-09-13 15:48:51.754 [       job-0] INFO  JobContainer         - Upload the job run statistics to [http://localhost:5001/fsapi/addax/v1/jobReport]
2023-09-13 15:48:51.905 [       job-0] WARN  JobContainer         - Uploading the job results failed with an exception: Connect to localhost:5001 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
2023-09-13 15:48:51.905 [       job-0] INFO  JobContainer         - 
Job start  at             : 2023-09-13 15:47:35
Job end    at             : 2023-09-13 15:48:51
Job took secs             :                 76s
Average   bps             :               10B/s
Average   rps             :              0rec/s
Number of rec             :                  10
Failed record             :                   0

```

如果方便，你可以导出你 MySQL 表以及几条样本数据吗？我本地可以再策划看看。
