### ISSUE TITLE
[Bug]: 部署在墨西哥当地机器的时候，数据源连接自动生成的时区参数错误，异常退出

### ISSUE THREAD

**Issue by tangguoqiang172528725** [wgzhao/Addax#906]
### What happened?

A bug happened! When I deploy in mexico server it generate a wrong parameter.

2023-09-06 07:51:19.390 [  reader-0-0] ERROR ReaderRunner         - Reader runner Received Exceptions:
com.wgzhao.addax.common.exception.AddaxException: Cannot create PoolableConnectionFactory (No timezone mapping entry for 'GMT--6')
	at com.wgzhao.addax.common.exception.AddaxException.asAddaxException(AddaxException.java:50)
	at com.wgzhao.addax.rdbms.util.RdbmsException.asConnException(RdbmsException.java:40)
	at com.wgzhao.addax.rdbms.util.DBUtil.connect(DBUtil.java:292)
	at com.wgzhao.addax.rdbms.util.DBUtil.lambda$getConnection$2(DBUtil.java:227)
	at com.wgzhao.addax.common.util.RetryUtil$Retry.call(RetryUtil.java:203)
	at com.wgzhao.addax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:147)
	at com.wgzhao.addax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:59)
	at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:227)
	at com.wgzhao.addax.rdbms.util.DBUtil.getConnection(DBUtil.java:220)
	at com.wgzhao.addax.rdbms.reader.CommonRdbmsReader$Task.startRead(CommonRdbmsReader.java:215)
	at com.wgzhao.addax.plugin.reader.mysqlreader.MysqlReader$Task.startRead(MysqlReader.java:126)
	at com.wgzhao.addax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:82)
	at java.lang.Thread.run(Thread.java:748)

### Version

4.1.1 (Default)

### OS Type

Linux (Default)

### Java JDK Version

Oracle JDK 1.8.0

**Comment by wgzhao** [comment]
看报错是时区配置不正确
请给出完整的输出日志

**Comment by tangguoqiang172528725** [comment]
你那个数据源画蛇添足 读取数据源的时候自动生成的Gmt--6 当地时区-6

**Comment by tangguoqiang172528725** [comment]
com.wgzhao.addax.common.exception.AddaxException: Cannot create PoolableConnectionFactory (No timezone mapping entry for 'GMT--6'  GMT--06是addax自己加上的

**Comment by wgzhao** [comment]
请贴出完整日志

**Comment by tangguoqiang172528725** [comment]
已解决
